// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mlp,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu3eg-sbva484-1-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.507000,HLS_SYN_LAT=8645,HLS_SYN_TPT=none,HLS_SYN_MEM=5,HLS_SYN_DSP=13,HLS_SYN_FF=2201,HLS_SYN_LUT=5803,HLS_VERSION=2019_1}" *)

module mlp (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_V_address0,
        input_V_ce0,
        input_V_q0,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0,
        output_r_q0
);

parameter    ap_ST_fsm_state1 = 53'd1;
parameter    ap_ST_fsm_state2 = 53'd2;
parameter    ap_ST_fsm_state3 = 53'd4;
parameter    ap_ST_fsm_state4 = 53'd8;
parameter    ap_ST_fsm_state5 = 53'd16;
parameter    ap_ST_fsm_state6 = 53'd32;
parameter    ap_ST_fsm_state7 = 53'd64;
parameter    ap_ST_fsm_state8 = 53'd128;
parameter    ap_ST_fsm_state9 = 53'd256;
parameter    ap_ST_fsm_state10 = 53'd512;
parameter    ap_ST_fsm_state11 = 53'd1024;
parameter    ap_ST_fsm_state12 = 53'd2048;
parameter    ap_ST_fsm_state13 = 53'd4096;
parameter    ap_ST_fsm_state14 = 53'd8192;
parameter    ap_ST_fsm_state15 = 53'd16384;
parameter    ap_ST_fsm_state16 = 53'd32768;
parameter    ap_ST_fsm_state17 = 53'd65536;
parameter    ap_ST_fsm_state18 = 53'd131072;
parameter    ap_ST_fsm_state19 = 53'd262144;
parameter    ap_ST_fsm_state20 = 53'd524288;
parameter    ap_ST_fsm_state21 = 53'd1048576;
parameter    ap_ST_fsm_state22 = 53'd2097152;
parameter    ap_ST_fsm_state23 = 53'd4194304;
parameter    ap_ST_fsm_state24 = 53'd8388608;
parameter    ap_ST_fsm_state25 = 53'd16777216;
parameter    ap_ST_fsm_state26 = 53'd33554432;
parameter    ap_ST_fsm_state27 = 53'd67108864;
parameter    ap_ST_fsm_state28 = 53'd134217728;
parameter    ap_ST_fsm_state29 = 53'd268435456;
parameter    ap_ST_fsm_state30 = 53'd536870912;
parameter    ap_ST_fsm_state31 = 53'd1073741824;
parameter    ap_ST_fsm_state32 = 53'd2147483648;
parameter    ap_ST_fsm_state33 = 53'd4294967296;
parameter    ap_ST_fsm_state34 = 53'd8589934592;
parameter    ap_ST_fsm_state35 = 53'd17179869184;
parameter    ap_ST_fsm_state36 = 53'd34359738368;
parameter    ap_ST_fsm_state37 = 53'd68719476736;
parameter    ap_ST_fsm_state38 = 53'd137438953472;
parameter    ap_ST_fsm_state39 = 53'd274877906944;
parameter    ap_ST_fsm_state40 = 53'd549755813888;
parameter    ap_ST_fsm_state41 = 53'd1099511627776;
parameter    ap_ST_fsm_state42 = 53'd2199023255552;
parameter    ap_ST_fsm_state43 = 53'd4398046511104;
parameter    ap_ST_fsm_state44 = 53'd8796093022208;
parameter    ap_ST_fsm_state45 = 53'd17592186044416;
parameter    ap_ST_fsm_state46 = 53'd35184372088832;
parameter    ap_ST_fsm_state47 = 53'd70368744177664;
parameter    ap_ST_fsm_state48 = 53'd140737488355328;
parameter    ap_ST_fsm_state49 = 53'd281474976710656;
parameter    ap_ST_fsm_state50 = 53'd562949953421312;
parameter    ap_ST_fsm_state51 = 53'd1125899906842624;
parameter    ap_ST_fsm_state52 = 53'd2251799813685248;
parameter    ap_ST_fsm_state53 = 53'd4503599627370496;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] input_V_address0;
output   input_V_ce0;
input  [19:0] input_V_q0;
output  [3:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [31:0] output_r_d0;
input  [31:0] output_r_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_V_ce0;
reg[3:0] output_r_address0;
reg output_r_ce0;
reg output_r_we0;
reg[31:0] output_r_d0;

(* fsm_encoding = "none" *) reg   [52:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] B1_V_address0;
reg    B1_V_ce0;
wire   [12:0] B1_V_q0;
wire   [11:0] W1_V_address0;
reg    W1_V_ce0;
wire  signed [15:0] W1_V_q0;
wire   [2:0] B2_V_address0;
reg    B2_V_ce0;
wire   [14:0] B2_V_q0;
wire   [5:0] W2_V_address0;
reg    W2_V_ce0;
wire  signed [15:0] W2_V_q0;
wire   [2:0] B3_V_address0;
reg    B3_V_ce0;
wire   [15:0] B3_V_q0;
wire   [5:0] W3_V_address0;
reg    W3_V_ce0;
wire  signed [14:0] W3_V_q0;
wire   [3:0] B4_V_address0;
reg    B4_V_ce0;
wire   [15:0] B4_V_q0;
wire   [6:0] W4_V_address0;
reg    W4_V_ce0;
wire  signed [15:0] W4_V_q0;
wire   [19:0] grp_fu_709_p3;
reg   [19:0] reg_727;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state21;
wire   [0:0] grp_fu_689_p2;
wire   [11:0] add_ln88_fu_731_p2;
reg   [11:0] add_ln88_reg_2184;
wire    ap_CS_fsm_state2;
wire   [2:0] j_fu_743_p2;
reg   [2:0] j_reg_2192;
wire   [63:0] zext_ln89_fu_749_p1;
reg   [63:0] zext_ln89_reg_2197;
wire   [0:0] icmp_ln88_fu_737_p2;
wire   [19:0] zext_ln89_1_fu_754_p1;
wire    ap_CS_fsm_state3;
wire   [9:0] i_fu_764_p2;
reg   [9:0] i_reg_2215;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln68_fu_758_p2;
wire    ap_CS_fsm_state5;
wire   [3:0] j_1_fu_842_p2;
reg   [3:0] j_1_reg_2238;
wire    ap_CS_fsm_state6;
wire   [63:0] zext_ln94_fu_848_p1;
reg   [63:0] zext_ln94_reg_2243;
wire   [0:0] icmp_ln93_fu_836_p2;
wire   [6:0] add_ln1117_fu_869_p2;
reg   [6:0] add_ln1117_reg_2253;
wire    ap_CS_fsm_state7;
wire  signed [19:0] sext_ln94_fu_875_p1;
wire   [2:0] i_1_fu_885_p2;
reg   [2:0] i_1_reg_2266;
wire    ap_CS_fsm_state8;
wire   [0:0] icmp_ln68_1_fu_879_p2;
wire    ap_CS_fsm_state9;
wire   [3:0] j_2_fu_962_p2;
reg   [3:0] j_2_reg_2289;
wire    ap_CS_fsm_state10;
wire   [63:0] zext_ln99_fu_968_p1;
reg   [63:0] zext_ln99_reg_2294;
wire   [0:0] icmp_ln98_fu_956_p2;
wire   [7:0] zext_ln99_1_fu_981_p1;
reg   [7:0] zext_ln99_1_reg_2304;
wire    ap_CS_fsm_state11;
wire  signed [19:0] sext_ln99_fu_985_p1;
wire   [3:0] i_2_fu_995_p2;
reg   [3:0] i_2_reg_2317;
wire    ap_CS_fsm_state12;
wire   [0:0] icmp_ln68_2_fu_989_p2;
wire    ap_CS_fsm_state13;
wire   [3:0] j_3_fu_1072_p2;
reg   [3:0] j_3_reg_2340;
wire    ap_CS_fsm_state14;
wire   [63:0] zext_ln104_fu_1078_p1;
reg   [63:0] zext_ln104_reg_2345;
wire   [0:0] icmp_ln103_fu_1066_p2;
wire   [7:0] zext_ln104_1_fu_1091_p1;
reg   [7:0] zext_ln104_1_reg_2360;
wire    ap_CS_fsm_state15;
wire  signed [19:0] sext_ln104_fu_1095_p1;
wire   [3:0] i_3_fu_1105_p2;
reg   [3:0] i_3_reg_2373;
wire    ap_CS_fsm_state16;
wire   [0:0] icmp_ln68_3_fu_1099_p2;
wire    ap_CS_fsm_state17;
reg   [0:0] icmp_ln935_reg_2393;
wire   [0:0] grp_fu_695_p3;
reg   [0:0] p_Result_21_reg_2398;
wire   [31:0] sub_ln944_fu_1171_p2;
reg   [31:0] sub_ln944_reg_2403;
wire   [31:0] or_ln_fu_1281_p3;
reg   [31:0] or_ln_reg_2409;
wire   [0:0] icmp_ln958_fu_1289_p2;
reg   [0:0] icmp_ln958_reg_2414;
wire   [7:0] trunc_ln943_fu_1295_p1;
reg   [7:0] trunc_ln943_reg_2419;
wire   [31:0] select_ln935_fu_1421_p3;
reg   [31:0] select_ln935_reg_2424;
wire    ap_CS_fsm_state19;
wire   [63:0] zext_ln110_fu_1434_p1;
reg   [63:0] zext_ln110_reg_2433;
wire    ap_CS_fsm_state20;
wire   [0:0] icmp_ln109_fu_1428_p2;
wire   [19:0] z4_V_q0;
reg   [19:0] tmp_V_11_reg_2444;
reg   [0:0] icmp_ln935_1_reg_2451;
reg   [0:0] p_Result_24_reg_2456;
wire   [31:0] sub_ln944_1_fu_1455_p2;
reg   [31:0] sub_ln944_1_reg_2461;
wire   [31:0] or_ln949_2_fu_1565_p3;
reg   [31:0] or_ln949_2_reg_2467;
wire   [0:0] icmp_ln958_1_fu_1573_p2;
reg   [0:0] icmp_ln958_1_reg_2472;
wire   [7:0] trunc_ln943_1_fu_1579_p1;
reg   [7:0] trunc_ln943_1_reg_2477;
wire   [31:0] bitcast_ln739_1_fu_1701_p1;
wire    ap_CS_fsm_state22;
wire   [3:0] j_5_fu_1706_p2;
reg   [3:0] j_5_reg_2487;
wire   [0:0] icmp_ln111_fu_1730_p2;
reg   [0:0] icmp_ln111_reg_2492;
wire    ap_CS_fsm_state23;
wire   [0:0] icmp_ln111_1_fu_1736_p2;
reg   [0:0] icmp_ln111_1_reg_2497;
wire   [0:0] p_Result_27_fu_1742_p3;
reg   [0:0] p_Result_27_reg_2502;
wire   [19:0] tmp_V_13_fu_1754_p3;
reg   [19:0] tmp_V_13_reg_2507;
wire   [31:0] sub_ln944_2_fu_1787_p2;
reg   [31:0] sub_ln944_2_reg_2513;
wire   [31:0] or_ln949_4_fu_1897_p3;
reg   [31:0] or_ln949_4_reg_2519;
wire   [0:0] icmp_ln958_2_fu_1905_p2;
reg   [0:0] icmp_ln958_2_reg_2524;
wire   [7:0] trunc_ln943_2_fu_1911_p1;
reg   [7:0] trunc_ln943_2_reg_2529;
wire   [31:0] select_ln111_1_fu_2106_p3;
wire    ap_CS_fsm_state24;
wire   [3:0] j_4_fu_2120_p2;
reg   [3:0] j_4_reg_2542;
wire    ap_CS_fsm_state25;
wire   [63:0] zext_ln119_fu_2126_p1;
reg   [63:0] zext_ln119_reg_2547;
wire   [0:0] icmp_ln118_fu_2114_p2;
wire   [31:0] logits_q0;
wire    ap_CS_fsm_state26;
wire   [31:0] grp_fu_665_p2;
reg   [31:0] tmp_reg_2562;
wire    ap_CS_fsm_state29;
wire   [31:0] grp_fu_683_p2;
reg   [31:0] e_reg_2567;
wire    ap_CS_fsm_state37;
wire    ap_CS_fsm_state41;
wire   [3:0] j_6_fu_2137_p2;
reg   [3:0] j_6_reg_2580;
wire    ap_CS_fsm_state42;
reg   [3:0] output_addr_1_reg_2585;
wire   [0:0] icmp_ln124_fu_2131_p2;
reg   [31:0] output_load_reg_2590;
wire    ap_CS_fsm_state43;
wire   [31:0] grp_fu_672_p2;
reg   [31:0] tmp_2_reg_2595;
wire    ap_CS_fsm_state52;
reg   [2:0] a1_V_address0;
reg    a1_V_ce0;
reg    a1_V_we0;
wire   [18:0] a1_V_d0;
wire   [18:0] a1_V_q0;
reg   [2:0] a2_V_address0;
reg    a2_V_ce0;
reg    a2_V_we0;
wire   [18:0] a2_V_d0;
wire   [18:0] a2_V_q0;
reg   [2:0] a3_V_address0;
reg    a3_V_ce0;
reg    a3_V_we0;
wire   [18:0] a3_V_d0;
wire   [18:0] a3_V_q0;
reg   [3:0] z4_V_address0;
reg    z4_V_ce0;
reg    z4_V_we0;
reg   [3:0] logits_address0;
reg    logits_ce0;
reg    logits_we0;
reg   [31:0] logits_d0;
reg   [2:0] j_0_reg_453;
reg   [11:0] phi_mul_reg_464;
reg   [19:0] p_Val2_1_reg_476;
reg   [9:0] i_0_i_reg_486;
reg   [3:0] j4_0_reg_497;
reg   [19:0] p_Val2_4_reg_509;
reg   [2:0] i_0_i10_reg_519;
reg   [3:0] j5_0_reg_530;
reg   [19:0] p_Val2_9_reg_542;
reg   [3:0] i_0_i26_reg_552;
reg   [3:0] j6_0_reg_563;
reg   [19:0] p_Val2_14_reg_575;
reg   [3:0] i_0_i42_reg_586;
reg   [31:0] maxv_0_reg_597;
reg   [3:0] j7_0_reg_607;
reg   [31:0] p_0202_reg_619;
reg   [31:0] sum_0_reg_631;
reg   [3:0] j8_0_reg_643;
reg   [3:0] j9_0_reg_654;
wire    ap_CS_fsm_state53;
wire   [63:0] zext_ln1117_3_fu_785_p1;
wire   [63:0] zext_ln69_fu_770_p1;
wire   [63:0] zext_ln1117_5_fu_905_p1;
wire   [63:0] zext_ln69_1_fu_891_p1;
wire   [63:0] zext_ln1117_7_fu_1015_p1;
wire   [63:0] zext_ln69_2_fu_1001_p1;
wire   [63:0] zext_ln1117_9_fu_1125_p1;
wire   [63:0] zext_ln69_3_fu_1111_p1;
wire   [3:0] logits_addr_1_gep_fu_418_p3;
wire   [63:0] zext_ln125_fu_2143_p1;
reg   [31:0] grp_fu_665_p0;
reg   [31:0] grp_fu_665_p1;
wire    ap_CS_fsm_state38;
wire    ap_CS_fsm_state44;
wire    ap_CS_fsm_state30;
wire   [19:0] grp_fu_703_p2;
wire   [11:0] zext_ln1117_2_fu_775_p1;
wire   [11:0] add_ln1117_1_fu_779_p2;
wire   [0:0] tmp_10_fu_794_p3;
wire   [18:0] empty_16_fu_790_p1;
wire  signed [33:0] grp_fu_2148_p3;
wire   [5:0] tmp_7_fu_857_p3;
wire   [6:0] zext_ln1117_fu_853_p1;
wire   [6:0] zext_ln1117_1_fu_865_p1;
wire   [6:0] zext_ln1117_4_fu_896_p1;
wire   [6:0] add_ln1117_2_fu_900_p2;
wire   [0:0] tmp_11_fu_914_p3;
wire   [18:0] empty_19_fu_910_p1;
wire  signed [33:0] grp_fu_2157_p3;
wire   [6:0] tmp_8_fu_973_p3;
wire   [7:0] zext_ln1117_6_fu_1006_p1;
wire   [7:0] add_ln1117_3_fu_1010_p2;
wire   [0:0] tmp_16_fu_1024_p3;
wire   [18:0] empty_22_fu_1020_p1;
wire  signed [33:0] grp_fu_2166_p3;
wire   [6:0] tmp_9_fu_1083_p3;
wire   [7:0] zext_ln1117_8_fu_1116_p1;
wire   [7:0] add_ln1117_4_fu_1120_p2;
wire  signed [33:0] grp_fu_2175_p3;
reg   [19:0] grp_fu_717_p4;
wire   [31:0] p_Result_22_fu_1155_p3;
reg   [31:0] l_fu_1163_p3;
wire   [31:0] lsb_index_fu_1181_p2;
wire   [30:0] tmp_13_fu_1187_p4;
wire   [4:0] trunc_ln947_fu_1203_p1;
wire   [4:0] sub_ln947_fu_1207_p2;
wire   [19:0] zext_ln947_fu_1213_p1;
wire   [19:0] lshr_ln947_fu_1217_p2;
wire   [19:0] p_Result_4_fu_1223_p2;
wire   [0:0] icmp_ln947_fu_1197_p2;
wire   [0:0] icmp_ln947_1_fu_1229_p2;
wire   [0:0] tmp_14_fu_1241_p3;
wire   [19:0] trunc_ln944_fu_1177_p1;
wire   [19:0] add_ln949_fu_1255_p2;
wire   [0:0] p_Result_3_fu_1261_p3;
wire   [0:0] xor_ln949_fu_1249_p2;
wire   [0:0] and_ln949_fu_1269_p2;
wire   [0:0] a_fu_1235_p2;
wire   [0:0] or_ln949_fu_1275_p2;
wire   [31:0] zext_ln957_1_fu_1303_p1;
wire   [31:0] add_ln958_fu_1307_p2;
wire   [31:0] lshr_ln958_fu_1312_p2;
wire   [31:0] sub_ln958_fu_1322_p2;
wire   [63:0] m_fu_1299_p1;
wire   [63:0] zext_ln958_1_fu_1327_p1;
wire   [63:0] zext_ln958_fu_1318_p1;
wire   [63:0] shl_ln958_fu_1331_p2;
wire   [63:0] m_1_fu_1337_p3;
wire   [63:0] zext_ln961_fu_1344_p1;
wire   [63:0] m_2_fu_1347_p2;
wire   [62:0] m_s_fu_1353_p4;
wire   [0:0] tmp_15_fu_1367_p3;
wire   [7:0] select_ln964_fu_1375_p3;
wire   [7:0] sub_ln964_fu_1383_p2;
wire   [7:0] add_ln964_fu_1388_p2;
wire   [63:0] m_26_fu_1363_p1;
wire   [8:0] tmp_s_fu_1394_p3;
wire   [63:0] p_Result_23_fu_1401_p5;
wire   [31:0] trunc_ln738_fu_1413_p1;
wire   [31:0] bitcast_ln739_fu_1417_p1;
wire   [31:0] p_Result_25_fu_1439_p3;
reg   [31:0] l_1_fu_1447_p3;
wire   [31:0] lsb_index_1_fu_1465_p2;
wire   [30:0] tmp_18_fu_1471_p4;
wire   [4:0] trunc_ln947_1_fu_1487_p1;
wire   [4:0] sub_ln947_1_fu_1491_p2;
wire   [19:0] zext_ln947_1_fu_1497_p1;
wire   [19:0] lshr_ln947_1_fu_1501_p2;
wire   [19:0] p_Result_12_fu_1507_p2;
wire   [0:0] icmp_ln947_2_fu_1481_p2;
wire   [0:0] icmp_ln947_3_fu_1513_p2;
wire   [0:0] tmp_19_fu_1525_p3;
wire   [19:0] trunc_ln944_1_fu_1461_p1;
wire   [19:0] add_ln949_1_fu_1539_p2;
wire   [0:0] p_Result_13_fu_1545_p3;
wire   [0:0] xor_ln949_1_fu_1533_p2;
wire   [0:0] and_ln949_1_fu_1553_p2;
wire   [0:0] a_1_fu_1519_p2;
wire   [0:0] or_ln949_1_fu_1559_p2;
wire   [31:0] zext_ln957_2_fu_1587_p1;
wire   [31:0] add_ln958_1_fu_1591_p2;
wire   [31:0] lshr_ln958_1_fu_1596_p2;
wire   [31:0] sub_ln958_1_fu_1606_p2;
wire   [63:0] m_15_fu_1583_p1;
wire   [63:0] zext_ln958_3_fu_1611_p1;
wire   [63:0] zext_ln958_2_fu_1602_p1;
wire   [63:0] shl_ln958_1_fu_1615_p2;
wire   [63:0] m_16_fu_1621_p3;
wire   [63:0] zext_ln961_1_fu_1628_p1;
wire   [63:0] m_17_fu_1631_p2;
wire   [62:0] m_3_fu_1637_p4;
wire   [0:0] tmp_20_fu_1651_p3;
wire   [7:0] select_ln964_1_fu_1659_p3;
wire   [7:0] sub_ln964_1_fu_1667_p2;
wire   [7:0] add_ln964_1_fu_1672_p2;
wire   [63:0] m_27_fu_1647_p1;
wire   [8:0] tmp_4_fu_1678_p3;
wire   [63:0] p_Result_26_fu_1685_p5;
wire   [31:0] trunc_ln738_1_fu_1697_p1;
wire   [31:0] bitcast_ln111_fu_1712_p1;
wire   [7:0] tmp_1_fu_1716_p4;
wire   [22:0] trunc_ln111_fu_1726_p1;
wire   [19:0] tmp_V_7_fu_1749_p2;
reg   [19:0] p_Result_16_fu_1761_p4;
wire   [31:0] p_Result_28_fu_1771_p3;
reg   [31:0] l_2_fu_1779_p3;
wire   [31:0] lsb_index_2_fu_1797_p2;
wire   [30:0] tmp_22_fu_1803_p4;
wire   [4:0] trunc_ln947_2_fu_1819_p1;
wire   [4:0] sub_ln947_2_fu_1823_p2;
wire   [19:0] zext_ln947_2_fu_1829_p1;
wire   [19:0] lshr_ln947_2_fu_1833_p2;
wire   [19:0] p_Result_18_fu_1839_p2;
wire   [0:0] icmp_ln947_4_fu_1813_p2;
wire   [0:0] icmp_ln947_5_fu_1845_p2;
wire   [0:0] tmp_23_fu_1857_p3;
wire   [19:0] trunc_ln944_2_fu_1793_p1;
wire   [19:0] add_ln949_2_fu_1871_p2;
wire   [0:0] p_Result_19_fu_1877_p3;
wire   [0:0] xor_ln949_2_fu_1865_p2;
wire   [0:0] and_ln949_2_fu_1885_p2;
wire   [0:0] a_2_fu_1851_p2;
wire   [0:0] or_ln949_3_fu_1891_p2;
wire   [31:0] bitcast_ln111_1_fu_1915_p1;
wire   [7:0] tmp_3_fu_1919_p4;
wire   [22:0] trunc_ln111_1_fu_1929_p1;
wire   [0:0] icmp_ln111_3_fu_1943_p2;
wire   [0:0] icmp_ln111_2_fu_1937_p2;
wire   [0:0] or_ln111_1_fu_1933_p2;
wire   [0:0] or_ln111_2_fu_1949_p2;
wire   [0:0] and_ln111_fu_1955_p2;
wire   [0:0] grp_fu_677_p2;
wire   [0:0] and_ln111_1_fu_1961_p2;
wire   [0:0] xor_ln111_fu_1967_p2;
wire   [31:0] zext_ln957_3_fu_1989_p1;
wire   [31:0] add_ln958_2_fu_1992_p2;
wire   [31:0] lshr_ln958_2_fu_1997_p2;
wire   [31:0] sub_ln958_2_fu_2007_p2;
wire   [63:0] m_21_fu_1986_p1;
wire   [63:0] zext_ln958_5_fu_2012_p1;
wire   [63:0] zext_ln958_4_fu_2003_p1;
wire   [63:0] shl_ln958_2_fu_2016_p2;
wire   [63:0] m_22_fu_2022_p3;
wire   [63:0] zext_ln961_2_fu_2029_p1;
wire   [63:0] m_23_fu_2032_p2;
wire   [62:0] m_4_fu_2038_p4;
wire   [0:0] tmp_24_fu_2052_p3;
wire   [7:0] select_ln964_2_fu_2060_p3;
wire   [7:0] sub_ln964_2_fu_2068_p2;
wire   [7:0] add_ln964_2_fu_2073_p2;
wire   [63:0] m_28_fu_2048_p1;
wire   [8:0] tmp_6_fu_2079_p3;
wire   [63:0] p_Result_29_fu_2086_p5;
wire   [31:0] trunc_ln738_2_fu_2098_p1;
wire   [0:0] or_ln111_fu_1973_p2;
wire   [31:0] select_ln111_fu_1978_p3;
wire   [31:0] bitcast_ln739_2_fu_2102_p1;
wire   [33:0] grp_fu_2148_p2;
wire   [18:0] grp_fu_2157_p0;
wire   [33:0] grp_fu_2157_p2;
wire   [18:0] grp_fu_2166_p0;
wire   [33:0] grp_fu_2166_p2;
wire   [18:0] grp_fu_2175_p0;
wire   [33:0] grp_fu_2175_p2;
reg   [1:0] grp_fu_665_opcode;
reg   [52:0] ap_NS_fsm;
wire   [33:0] grp_fu_2157_p00;
wire   [33:0] grp_fu_2166_p00;
wire   [33:0] grp_fu_2175_p00;

// power-on initialization
initial begin
#0 ap_CS_fsm = 53'd1;
end

mlp_B1_V #(
    .DataWidth( 13 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
B1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(B1_V_address0),
    .ce0(B1_V_ce0),
    .q0(B1_V_q0)
);

mlp_W1_V #(
    .DataWidth( 16 ),
    .AddressRange( 3920 ),
    .AddressWidth( 12 ))
W1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W1_V_address0),
    .ce0(W1_V_ce0),
    .q0(W1_V_q0)
);

mlp_B2_V #(
    .DataWidth( 15 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
B2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(B2_V_address0),
    .ce0(B2_V_ce0),
    .q0(B2_V_q0)
);

mlp_W2_V #(
    .DataWidth( 16 ),
    .AddressRange( 40 ),
    .AddressWidth( 6 ))
W2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W2_V_address0),
    .ce0(W2_V_ce0),
    .q0(W2_V_q0)
);

mlp_B3_V #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
B3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(B3_V_address0),
    .ce0(B3_V_ce0),
    .q0(B3_V_q0)
);

mlp_W3_V #(
    .DataWidth( 15 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
W3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W3_V_address0),
    .ce0(W3_V_ce0),
    .q0(W3_V_q0)
);

mlp_B4_V #(
    .DataWidth( 16 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
B4_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(B4_V_address0),
    .ce0(B4_V_ce0),
    .q0(B4_V_q0)
);

mlp_W4_V #(
    .DataWidth( 16 ),
    .AddressRange( 80 ),
    .AddressWidth( 7 ))
W4_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W4_V_address0),
    .ce0(W4_V_ce0),
    .q0(W4_V_q0)
);

mlp_a1_V #(
    .DataWidth( 19 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
a1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(a1_V_address0),
    .ce0(a1_V_ce0),
    .we0(a1_V_we0),
    .d0(a1_V_d0),
    .q0(a1_V_q0)
);

mlp_a2_V #(
    .DataWidth( 19 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
a2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(a2_V_address0),
    .ce0(a2_V_ce0),
    .we0(a2_V_we0),
    .d0(a2_V_d0),
    .q0(a2_V_q0)
);

mlp_a2_V #(
    .DataWidth( 19 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
a3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(a3_V_address0),
    .ce0(a3_V_ce0),
    .we0(a3_V_we0),
    .d0(a3_V_d0),
    .q0(a3_V_q0)
);

mlp_z4_V #(
    .DataWidth( 20 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
z4_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(z4_V_address0),
    .ce0(z4_V_ce0),
    .we0(z4_V_we0),
    .d0(p_Val2_14_reg_575),
    .q0(z4_V_q0)
);

mlp_logits #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
logits_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(logits_address0),
    .ce0(logits_ce0),
    .we0(logits_we0),
    .d0(logits_d0),
    .q0(logits_q0)
);

mlp_faddfsub_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mlp_faddfsub_32ns_32ns_32_4_full_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_665_p0),
    .din1(grp_fu_665_p1),
    .opcode(grp_fu_665_opcode),
    .ce(1'b1),
    .dout(grp_fu_665_p2)
);

mlp_fdiv_32ns_32ns_32_9_1 #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mlp_fdiv_32ns_32ns_32_9_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(output_load_reg_2590),
    .din1(sum_0_reg_631),
    .ce(1'b1),
    .dout(grp_fu_672_p2)
);

mlp_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
mlp_fcmp_32ns_32ns_1_2_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0202_reg_619),
    .din1(maxv_0_reg_597),
    .ce(1'b1),
    .opcode(5'd2),
    .dout(grp_fu_677_p2)
);

mlp_fexp_32ns_32ns_32_8_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mlp_fexp_32ns_32ns_32_8_full_dsp_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(tmp_reg_2562),
    .ce(1'b1),
    .dout(grp_fu_683_p2)
);

mlp_mac_muladd_20s_16s_34ns_34_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 34 ),
    .dout_WIDTH( 34 ))
mlp_mac_muladd_20s_16s_34ns_34_1_1_U5(
    .din0(input_V_q0),
    .din1(W1_V_q0),
    .din2(grp_fu_2148_p2),
    .dout(grp_fu_2148_p3)
);

mlp_mac_muladd_19ns_16s_34ns_34_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 19 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 34 ),
    .dout_WIDTH( 34 ))
mlp_mac_muladd_19ns_16s_34ns_34_1_1_U6(
    .din0(grp_fu_2157_p0),
    .din1(W2_V_q0),
    .din2(grp_fu_2157_p2),
    .dout(grp_fu_2157_p3)
);

mlp_mac_muladd_19ns_15s_34ns_34_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 19 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 34 ),
    .dout_WIDTH( 34 ))
mlp_mac_muladd_19ns_15s_34ns_34_1_1_U7(
    .din0(grp_fu_2166_p0),
    .din1(W3_V_q0),
    .din2(grp_fu_2166_p2),
    .dout(grp_fu_2166_p3)
);

mlp_mac_muladd_19ns_16s_34ns_34_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 19 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 34 ),
    .dout_WIDTH( 34 ))
mlp_mac_muladd_19ns_16s_34ns_34_1_1_U8(
    .din0(grp_fu_2175_p0),
    .din1(W4_V_q0),
    .din2(grp_fu_2175_p2),
    .dout(grp_fu_2175_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        i_0_i10_reg_519 <= i_1_reg_2266;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        i_0_i10_reg_519 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        i_0_i26_reg_552 <= i_2_reg_2317;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        i_0_i26_reg_552 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        i_0_i42_reg_586 <= i_3_reg_2373;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        i_0_i42_reg_586 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i_0_i_reg_486 <= i_reg_2215;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        i_0_i_reg_486 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln88_fu_737_p2 == 1'd1))) begin
        j4_0_reg_497 <= 4'd0;
    end else if (((icmp_ln68_1_fu_879_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        j4_0_reg_497 <= j_1_reg_2238;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln93_fu_836_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        j5_0_reg_530 <= 4'd0;
    end else if (((icmp_ln68_2_fu_989_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
        j5_0_reg_530 <= j_2_reg_2289;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln98_fu_956_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        j6_0_reg_563 <= 4'd0;
    end else if (((icmp_ln68_3_fu_1099_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        j6_0_reg_563 <= j_3_reg_2340;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        j7_0_reg_607 <= 4'd1;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        j7_0_reg_607 <= j_5_reg_2487;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        j8_0_reg_643 <= j_4_reg_2542;
    end else if (((icmp_ln109_fu_1428_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20))) begin
        j8_0_reg_643 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln118_fu_2114_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state25))) begin
        j9_0_reg_654 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state53)) begin
        j9_0_reg_654 <= j_6_reg_2580;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        j_0_reg_453 <= 3'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln68_fu_758_p2 == 1'd1))) begin
        j_0_reg_453 <= j_reg_2192;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        maxv_0_reg_597 <= select_ln935_fu_1421_p3;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        maxv_0_reg_597 <= select_ln111_1_fu_2106_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state21) & (grp_fu_689_p2 == 1'd1))) begin
        p_0202_reg_619 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state22) & (icmp_ln935_1_reg_2451 == 1'd0))) begin
        p_0202_reg_619 <= bitcast_ln739_1_fu_1701_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        p_Val2_14_reg_575 <= {{grp_fu_2175_p3[33:14]}};
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        p_Val2_14_reg_575 <= sext_ln104_fu_1095_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_Val2_1_reg_476 <= {{grp_fu_2148_p3[33:14]}};
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        p_Val2_1_reg_476 <= zext_ln89_1_fu_754_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        p_Val2_4_reg_509 <= {{grp_fu_2157_p3[33:14]}};
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        p_Val2_4_reg_509 <= sext_ln94_fu_875_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        p_Val2_9_reg_542 <= {{grp_fu_2166_p3[33:14]}};
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        p_Val2_9_reg_542 <= sext_ln99_fu_985_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_mul_reg_464 <= 12'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln68_fu_758_p2 == 1'd1))) begin
        phi_mul_reg_464 <= add_ln88_reg_2184;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        sum_0_reg_631 <= grp_fu_665_p2;
    end else if (((icmp_ln109_fu_1428_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20))) begin
        sum_0_reg_631 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln1117_reg_2253 <= add_ln1117_fu_869_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln88_reg_2184 <= add_ln88_fu_731_p2;
        j_reg_2192 <= j_fu_743_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        e_reg_2567 <= grp_fu_683_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        i_1_reg_2266 <= i_1_fu_885_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        i_2_reg_2317 <= i_2_fu_995_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        i_3_reg_2373 <= i_3_fu_1105_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        i_reg_2215 <= i_fu_764_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        icmp_ln111_1_reg_2497 <= icmp_ln111_1_fu_1736_p2;
        icmp_ln111_reg_2492 <= icmp_ln111_fu_1730_p2;
        icmp_ln958_2_reg_2524 <= icmp_ln958_2_fu_1905_p2;
        or_ln949_4_reg_2519[0] <= or_ln949_4_fu_1897_p3[0];
        p_Result_27_reg_2502 <= tmp_V_11_reg_2444[32'd19];
        sub_ln944_2_reg_2513 <= sub_ln944_2_fu_1787_p2;
        tmp_V_13_reg_2507 <= tmp_V_13_fu_1754_p3;
        trunc_ln943_2_reg_2529 <= trunc_ln943_2_fu_1911_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        icmp_ln935_1_reg_2451 <= grp_fu_689_p2;
        tmp_V_11_reg_2444 <= z4_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        icmp_ln935_reg_2393 <= grp_fu_689_p2;
        icmp_ln958_reg_2414 <= icmp_ln958_fu_1289_p2;
        or_ln_reg_2409[0] <= or_ln_fu_1281_p3[0];
        p_Result_21_reg_2398 <= z4_V_q0[32'd19];
        sub_ln944_reg_2403 <= sub_ln944_fu_1171_p2;
        trunc_ln943_reg_2419 <= trunc_ln943_fu_1295_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state21) & (grp_fu_689_p2 == 1'd0))) begin
        icmp_ln958_1_reg_2472 <= icmp_ln958_1_fu_1573_p2;
        or_ln949_2_reg_2467[0] <= or_ln949_2_fu_1565_p3[0];
        p_Result_24_reg_2456 <= z4_V_q0[32'd19];
        sub_ln944_1_reg_2461 <= sub_ln944_1_fu_1455_p2;
        trunc_ln943_1_reg_2477 <= trunc_ln943_1_fu_1579_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        j_1_reg_2238 <= j_1_fu_842_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        j_2_reg_2289 <= j_2_fu_962_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        j_3_reg_2340 <= j_3_fu_1072_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        j_4_reg_2542 <= j_4_fu_2120_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        j_5_reg_2487 <= j_5_fu_1706_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        j_6_reg_2580 <= j_6_fu_2137_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state42) & (icmp_ln124_fu_2131_p2 == 1'd0))) begin
        output_addr_1_reg_2585 <= zext_ln125_fu_2143_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        output_load_reg_2590 <= output_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state18) | ((1'b1 == ap_CS_fsm_state21) & (grp_fu_689_p2 == 1'd0)))) begin
        reg_727 <= grp_fu_709_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        select_ln935_reg_2424 <= select_ln935_fu_1421_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state52)) begin
        tmp_2_reg_2595 <= grp_fu_672_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        tmp_reg_2562 <= grp_fu_665_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        zext_ln104_1_reg_2360[6 : 3] <= zext_ln104_1_fu_1091_p1[6 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & (icmp_ln103_fu_1066_p2 == 1'd0))) begin
        zext_ln104_reg_2345[3 : 0] <= zext_ln104_fu_1078_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state20) & (icmp_ln109_fu_1428_p2 == 1'd0))) begin
        zext_ln110_reg_2433[3 : 0] <= zext_ln110_fu_1434_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state25) & (icmp_ln118_fu_2114_p2 == 1'd0))) begin
        zext_ln119_reg_2547[3 : 0] <= zext_ln119_fu_2126_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln88_fu_737_p2 == 1'd0))) begin
        zext_ln89_reg_2197[2 : 0] <= zext_ln89_fu_749_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln93_fu_836_p2 == 1'd0))) begin
        zext_ln94_reg_2243[3 : 0] <= zext_ln94_fu_848_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        zext_ln99_1_reg_2304[6 : 3] <= zext_ln99_1_fu_981_p1[6 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln98_fu_956_p2 == 1'd0))) begin
        zext_ln99_reg_2294[3 : 0] <= zext_ln99_fu_968_p1[3 : 0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        B1_V_ce0 = 1'b1;
    end else begin
        B1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B2_V_ce0 = 1'b1;
    end else begin
        B2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        B3_V_ce0 = 1'b1;
    end else begin
        B3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        B4_V_ce0 = 1'b1;
    end else begin
        B4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        W1_V_ce0 = 1'b1;
    end else begin
        W1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        W2_V_ce0 = 1'b1;
    end else begin
        W2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        W3_V_ce0 = 1'b1;
    end else begin
        W3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        W4_V_ce0 = 1'b1;
    end else begin
        W4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        a1_V_address0 = zext_ln69_1_fu_891_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        a1_V_address0 = zext_ln89_reg_2197;
    end else begin
        a1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state4))) begin
        a1_V_ce0 = 1'b1;
    end else begin
        a1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln68_fu_758_p2 == 1'd1))) begin
        a1_V_we0 = 1'b1;
    end else begin
        a1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        a2_V_address0 = zext_ln69_2_fu_1001_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        a2_V_address0 = zext_ln94_reg_2243;
    end else begin
        a2_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state8))) begin
        a2_V_ce0 = 1'b1;
    end else begin
        a2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln68_1_fu_879_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        a2_V_we0 = 1'b1;
    end else begin
        a2_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        a3_V_address0 = zext_ln69_3_fu_1111_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        a3_V_address0 = zext_ln99_reg_2294;
    end else begin
        a3_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state12))) begin
        a3_V_ce0 = 1'b1;
    end else begin
        a3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln68_2_fu_989_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
        a3_V_we0 = 1'b1;
    end else begin
        a3_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln124_fu_2131_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state42))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln124_fu_2131_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state42))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        grp_fu_665_opcode = 2'd1;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        grp_fu_665_opcode = 2'd0;
    end else begin
        grp_fu_665_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        grp_fu_665_p0 = sum_0_reg_631;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        grp_fu_665_p0 = logits_q0;
    end else begin
        grp_fu_665_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        grp_fu_665_p1 = e_reg_2567;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        grp_fu_665_p1 = maxv_0_reg_597;
    end else begin
        grp_fu_665_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_V_ce0 = 1'b1;
    end else begin
        input_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        logits_address0 = zext_ln119_fu_2126_p1;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        logits_address0 = logits_addr_1_gep_fu_418_p3;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        logits_address0 = zext_ln110_reg_2433;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        logits_address0 = 64'd0;
    end else begin
        logits_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state21))) begin
        logits_ce0 = 1'b1;
    end else begin
        logits_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        logits_d0 = bitcast_ln739_1_fu_1701_p1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        logits_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        logits_d0 = select_ln935_reg_2424;
    end else begin
        logits_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state22) & (icmp_ln935_1_reg_2451 == 1'd0)) | ((icmp_ln109_fu_1428_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20)) | ((1'b1 == ap_CS_fsm_state21) & (grp_fu_689_p2 == 1'd1)))) begin
        logits_we0 = 1'b1;
    end else begin
        logits_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state53)) begin
        output_r_address0 = output_addr_1_reg_2585;
    end else if ((1'b1 == ap_CS_fsm_state42)) begin
        output_r_address0 = zext_ln125_fu_2143_p1;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        output_r_address0 = zext_ln119_reg_2547;
    end else begin
        output_r_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state37))) begin
        output_r_ce0 = 1'b1;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state53)) begin
        output_r_d0 = tmp_2_reg_2595;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        output_r_d0 = grp_fu_683_p2;
    end else begin
        output_r_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state37))) begin
        output_r_we0 = 1'b1;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        z4_V_address0 = zext_ln110_fu_1434_p1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        z4_V_address0 = zext_ln104_reg_2345;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        z4_V_address0 = 64'd0;
    end else begin
        z4_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state14))) begin
        z4_V_ce0 = 1'b1;
    end else begin
        z4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln68_3_fu_1099_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        z4_V_we0 = 1'b1;
    end else begin
        z4_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln88_fu_737_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln68_fu_758_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state6 : begin
            if (((icmp_ln93_fu_836_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((icmp_ln68_1_fu_879_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state10 : begin
            if (((icmp_ln98_fu_956_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((icmp_ln68_2_fu_989_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state14 : begin
            if (((icmp_ln103_fu_1066_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((icmp_ln68_3_fu_1099_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((icmp_ln109_fu_1428_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state25 : begin
            if (((icmp_ln118_fu_2114_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state25))) begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state42 : begin
            if (((icmp_ln124_fu_2131_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state42))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state43;
            end
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B1_V_address0 = zext_ln89_fu_749_p1;

assign B2_V_address0 = zext_ln94_fu_848_p1;

assign B3_V_address0 = zext_ln99_fu_968_p1;

assign B4_V_address0 = zext_ln104_fu_1078_p1;

assign W1_V_address0 = zext_ln1117_3_fu_785_p1;

assign W2_V_address0 = zext_ln1117_5_fu_905_p1;

assign W3_V_address0 = zext_ln1117_7_fu_1015_p1;

assign W4_V_address0 = zext_ln1117_9_fu_1125_p1;

assign a1_V_d0 = ((tmp_10_fu_794_p3[0:0] === 1'b1) ? 19'd0 : empty_16_fu_790_p1);

assign a2_V_d0 = ((tmp_11_fu_914_p3[0:0] === 1'b1) ? 19'd0 : empty_19_fu_910_p1);

assign a3_V_d0 = ((tmp_16_fu_1024_p3[0:0] === 1'b1) ? 19'd0 : empty_22_fu_1020_p1);

assign a_1_fu_1519_p2 = (icmp_ln947_3_fu_1513_p2 & icmp_ln947_2_fu_1481_p2);

assign a_2_fu_1851_p2 = (icmp_ln947_5_fu_1845_p2 & icmp_ln947_4_fu_1813_p2);

assign a_fu_1235_p2 = (icmp_ln947_fu_1197_p2 & icmp_ln947_1_fu_1229_p2);

assign add_ln1117_1_fu_779_p2 = (zext_ln1117_2_fu_775_p1 + phi_mul_reg_464);

assign add_ln1117_2_fu_900_p2 = (zext_ln1117_4_fu_896_p1 + add_ln1117_reg_2253);

assign add_ln1117_3_fu_1010_p2 = (zext_ln1117_6_fu_1006_p1 + zext_ln99_1_reg_2304);

assign add_ln1117_4_fu_1120_p2 = (zext_ln1117_8_fu_1116_p1 + zext_ln104_1_reg_2360);

assign add_ln1117_fu_869_p2 = (zext_ln1117_fu_853_p1 + zext_ln1117_1_fu_865_p1);

assign add_ln88_fu_731_p2 = (phi_mul_reg_464 + 12'd784);

assign add_ln949_1_fu_1539_p2 = ($signed(20'd1048552) + $signed(trunc_ln944_1_fu_1461_p1));

assign add_ln949_2_fu_1871_p2 = ($signed(20'd1048552) + $signed(trunc_ln944_2_fu_1793_p1));

assign add_ln949_fu_1255_p2 = ($signed(20'd1048552) + $signed(trunc_ln944_fu_1177_p1));

assign add_ln958_1_fu_1591_p2 = ($signed(32'd4294967271) + $signed(sub_ln944_1_reg_2461));

assign add_ln958_2_fu_1992_p2 = ($signed(32'd4294967271) + $signed(sub_ln944_2_reg_2513));

assign add_ln958_fu_1307_p2 = ($signed(32'd4294967271) + $signed(sub_ln944_reg_2403));

assign add_ln964_1_fu_1672_p2 = (select_ln964_1_fu_1659_p3 + sub_ln964_1_fu_1667_p2);

assign add_ln964_2_fu_2073_p2 = (select_ln964_2_fu_2060_p3 + sub_ln964_2_fu_2068_p2);

assign add_ln964_fu_1388_p2 = (select_ln964_fu_1375_p3 + sub_ln964_fu_1383_p2);

assign and_ln111_1_fu_1961_p2 = (grp_fu_677_p2 & and_ln111_fu_1955_p2);

assign and_ln111_fu_1955_p2 = (or_ln111_2_fu_1949_p2 & or_ln111_1_fu_1933_p2);

assign and_ln949_1_fu_1553_p2 = (xor_ln949_1_fu_1533_p2 & p_Result_13_fu_1545_p3);

assign and_ln949_2_fu_1885_p2 = (xor_ln949_2_fu_1865_p2 & p_Result_19_fu_1877_p3);

assign and_ln949_fu_1269_p2 = (xor_ln949_fu_1249_p2 & p_Result_3_fu_1261_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state52 = ap_CS_fsm[32'd51];

assign ap_CS_fsm_state53 = ap_CS_fsm[32'd52];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign bitcast_ln111_1_fu_1915_p1 = maxv_0_reg_597;

assign bitcast_ln111_fu_1712_p1 = p_0202_reg_619;

assign bitcast_ln739_1_fu_1701_p1 = trunc_ln738_1_fu_1697_p1;

assign bitcast_ln739_2_fu_2102_p1 = trunc_ln738_2_fu_2098_p1;

assign bitcast_ln739_fu_1417_p1 = trunc_ln738_fu_1413_p1;

assign empty_16_fu_790_p1 = p_Val2_1_reg_476[18:0];

assign empty_19_fu_910_p1 = p_Val2_4_reg_509[18:0];

assign empty_22_fu_1020_p1 = p_Val2_9_reg_542[18:0];

assign grp_fu_2148_p2 = {{p_Val2_1_reg_476}, {14'd0}};

assign grp_fu_2157_p0 = grp_fu_2157_p00;

assign grp_fu_2157_p00 = a1_V_q0;

assign grp_fu_2157_p2 = {{p_Val2_4_reg_509}, {14'd0}};

assign grp_fu_2166_p0 = grp_fu_2166_p00;

assign grp_fu_2166_p00 = a2_V_q0;

assign grp_fu_2166_p2 = {{p_Val2_9_reg_542}, {14'd0}};

assign grp_fu_2175_p0 = grp_fu_2175_p00;

assign grp_fu_2175_p00 = a3_V_q0;

assign grp_fu_2175_p2 = {{p_Val2_14_reg_575}, {14'd0}};

assign grp_fu_689_p2 = ((z4_V_q0 == 20'd0) ? 1'b1 : 1'b0);

assign grp_fu_695_p3 = z4_V_q0[32'd19];

assign grp_fu_703_p2 = (20'd0 - z4_V_q0);

assign grp_fu_709_p3 = ((grp_fu_695_p3[0:0] === 1'b1) ? grp_fu_703_p2 : z4_V_q0);

integer ap_tvar_int_0;

always @ (grp_fu_709_p3) begin
    for (ap_tvar_int_0 = 20 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 19 - 0) begin
            grp_fu_717_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            grp_fu_717_p4[ap_tvar_int_0] = grp_fu_709_p3[19 - ap_tvar_int_0];
        end
    end
end

assign i_1_fu_885_p2 = (i_0_i10_reg_519 + 3'd1);

assign i_2_fu_995_p2 = (i_0_i26_reg_552 + 4'd1);

assign i_3_fu_1105_p2 = (i_0_i42_reg_586 + 4'd1);

assign i_fu_764_p2 = (i_0_i_reg_486 + 10'd1);

assign icmp_ln103_fu_1066_p2 = ((j6_0_reg_563 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln109_fu_1428_p2 = ((j7_0_reg_607 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln111_1_fu_1736_p2 = ((trunc_ln111_fu_1726_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln111_2_fu_1937_p2 = ((tmp_3_fu_1919_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln111_3_fu_1943_p2 = ((trunc_ln111_1_fu_1929_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln111_fu_1730_p2 = ((tmp_1_fu_1716_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln118_fu_2114_p2 = ((j8_0_reg_643 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln124_fu_2131_p2 = ((j9_0_reg_654 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln68_1_fu_879_p2 = ((i_0_i10_reg_519 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln68_2_fu_989_p2 = ((i_0_i26_reg_552 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln68_3_fu_1099_p2 = ((i_0_i42_reg_586 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln68_fu_758_p2 = ((i_0_i_reg_486 == 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln88_fu_737_p2 = ((j_0_reg_453 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln93_fu_836_p2 = ((j4_0_reg_497 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln947_1_fu_1229_p2 = ((p_Result_4_fu_1223_p2 != 20'd0) ? 1'b1 : 1'b0);

assign icmp_ln947_2_fu_1481_p2 = (($signed(tmp_18_fu_1471_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln947_3_fu_1513_p2 = ((p_Result_12_fu_1507_p2 != 20'd0) ? 1'b1 : 1'b0);

assign icmp_ln947_4_fu_1813_p2 = (($signed(tmp_22_fu_1803_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln947_5_fu_1845_p2 = ((p_Result_18_fu_1839_p2 != 20'd0) ? 1'b1 : 1'b0);

assign icmp_ln947_fu_1197_p2 = (($signed(tmp_13_fu_1187_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln958_1_fu_1573_p2 = (($signed(lsb_index_1_fu_1465_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln958_2_fu_1905_p2 = (($signed(lsb_index_2_fu_1797_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln958_fu_1289_p2 = (($signed(lsb_index_fu_1181_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln98_fu_956_p2 = ((j5_0_reg_530 == 4'd8) ? 1'b1 : 1'b0);

assign input_V_address0 = zext_ln69_fu_770_p1;

assign j_1_fu_842_p2 = (j4_0_reg_497 + 4'd1);

assign j_2_fu_962_p2 = (j5_0_reg_530 + 4'd1);

assign j_3_fu_1072_p2 = (j6_0_reg_563 + 4'd1);

assign j_4_fu_2120_p2 = (j8_0_reg_643 + 4'd1);

assign j_5_fu_1706_p2 = (4'd1 + j7_0_reg_607);

assign j_6_fu_2137_p2 = (j9_0_reg_654 + 4'd1);

assign j_fu_743_p2 = (j_0_reg_453 + 3'd1);


always @ (p_Result_25_fu_1439_p3) begin
    if (p_Result_25_fu_1439_p3[0] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd0;
    end else if (p_Result_25_fu_1439_p3[1] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd1;
    end else if (p_Result_25_fu_1439_p3[2] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd2;
    end else if (p_Result_25_fu_1439_p3[3] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd3;
    end else if (p_Result_25_fu_1439_p3[4] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd4;
    end else if (p_Result_25_fu_1439_p3[5] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd5;
    end else if (p_Result_25_fu_1439_p3[6] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd6;
    end else if (p_Result_25_fu_1439_p3[7] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd7;
    end else if (p_Result_25_fu_1439_p3[8] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd8;
    end else if (p_Result_25_fu_1439_p3[9] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd9;
    end else if (p_Result_25_fu_1439_p3[10] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd10;
    end else if (p_Result_25_fu_1439_p3[11] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd11;
    end else if (p_Result_25_fu_1439_p3[12] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd12;
    end else if (p_Result_25_fu_1439_p3[13] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd13;
    end else if (p_Result_25_fu_1439_p3[14] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd14;
    end else if (p_Result_25_fu_1439_p3[15] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd15;
    end else if (p_Result_25_fu_1439_p3[16] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd16;
    end else if (p_Result_25_fu_1439_p3[17] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd17;
    end else if (p_Result_25_fu_1439_p3[18] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd18;
    end else if (p_Result_25_fu_1439_p3[19] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd19;
    end else if (p_Result_25_fu_1439_p3[20] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd20;
    end else if (p_Result_25_fu_1439_p3[21] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd21;
    end else if (p_Result_25_fu_1439_p3[22] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd22;
    end else if (p_Result_25_fu_1439_p3[23] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd23;
    end else if (p_Result_25_fu_1439_p3[24] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd24;
    end else if (p_Result_25_fu_1439_p3[25] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd25;
    end else if (p_Result_25_fu_1439_p3[26] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd26;
    end else if (p_Result_25_fu_1439_p3[27] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd27;
    end else if (p_Result_25_fu_1439_p3[28] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd28;
    end else if (p_Result_25_fu_1439_p3[29] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd29;
    end else if (p_Result_25_fu_1439_p3[30] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd30;
    end else if (p_Result_25_fu_1439_p3[31] == 1'b1) begin
        l_1_fu_1447_p3 = 32'd31;
    end else begin
        l_1_fu_1447_p3 = 32'd32;
    end
end


always @ (p_Result_28_fu_1771_p3) begin
    if (p_Result_28_fu_1771_p3[0] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd0;
    end else if (p_Result_28_fu_1771_p3[1] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd1;
    end else if (p_Result_28_fu_1771_p3[2] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd2;
    end else if (p_Result_28_fu_1771_p3[3] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd3;
    end else if (p_Result_28_fu_1771_p3[4] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd4;
    end else if (p_Result_28_fu_1771_p3[5] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd5;
    end else if (p_Result_28_fu_1771_p3[6] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd6;
    end else if (p_Result_28_fu_1771_p3[7] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd7;
    end else if (p_Result_28_fu_1771_p3[8] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd8;
    end else if (p_Result_28_fu_1771_p3[9] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd9;
    end else if (p_Result_28_fu_1771_p3[10] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd10;
    end else if (p_Result_28_fu_1771_p3[11] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd11;
    end else if (p_Result_28_fu_1771_p3[12] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd12;
    end else if (p_Result_28_fu_1771_p3[13] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd13;
    end else if (p_Result_28_fu_1771_p3[14] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd14;
    end else if (p_Result_28_fu_1771_p3[15] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd15;
    end else if (p_Result_28_fu_1771_p3[16] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd16;
    end else if (p_Result_28_fu_1771_p3[17] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd17;
    end else if (p_Result_28_fu_1771_p3[18] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd18;
    end else if (p_Result_28_fu_1771_p3[19] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd19;
    end else if (p_Result_28_fu_1771_p3[20] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd20;
    end else if (p_Result_28_fu_1771_p3[21] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd21;
    end else if (p_Result_28_fu_1771_p3[22] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd22;
    end else if (p_Result_28_fu_1771_p3[23] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd23;
    end else if (p_Result_28_fu_1771_p3[24] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd24;
    end else if (p_Result_28_fu_1771_p3[25] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd25;
    end else if (p_Result_28_fu_1771_p3[26] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd26;
    end else if (p_Result_28_fu_1771_p3[27] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd27;
    end else if (p_Result_28_fu_1771_p3[28] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd28;
    end else if (p_Result_28_fu_1771_p3[29] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd29;
    end else if (p_Result_28_fu_1771_p3[30] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd30;
    end else if (p_Result_28_fu_1771_p3[31] == 1'b1) begin
        l_2_fu_1779_p3 = 32'd31;
    end else begin
        l_2_fu_1779_p3 = 32'd32;
    end
end


always @ (p_Result_22_fu_1155_p3) begin
    if (p_Result_22_fu_1155_p3[0] == 1'b1) begin
        l_fu_1163_p3 = 32'd0;
    end else if (p_Result_22_fu_1155_p3[1] == 1'b1) begin
        l_fu_1163_p3 = 32'd1;
    end else if (p_Result_22_fu_1155_p3[2] == 1'b1) begin
        l_fu_1163_p3 = 32'd2;
    end else if (p_Result_22_fu_1155_p3[3] == 1'b1) begin
        l_fu_1163_p3 = 32'd3;
    end else if (p_Result_22_fu_1155_p3[4] == 1'b1) begin
        l_fu_1163_p3 = 32'd4;
    end else if (p_Result_22_fu_1155_p3[5] == 1'b1) begin
        l_fu_1163_p3 = 32'd5;
    end else if (p_Result_22_fu_1155_p3[6] == 1'b1) begin
        l_fu_1163_p3 = 32'd6;
    end else if (p_Result_22_fu_1155_p3[7] == 1'b1) begin
        l_fu_1163_p3 = 32'd7;
    end else if (p_Result_22_fu_1155_p3[8] == 1'b1) begin
        l_fu_1163_p3 = 32'd8;
    end else if (p_Result_22_fu_1155_p3[9] == 1'b1) begin
        l_fu_1163_p3 = 32'd9;
    end else if (p_Result_22_fu_1155_p3[10] == 1'b1) begin
        l_fu_1163_p3 = 32'd10;
    end else if (p_Result_22_fu_1155_p3[11] == 1'b1) begin
        l_fu_1163_p3 = 32'd11;
    end else if (p_Result_22_fu_1155_p3[12] == 1'b1) begin
        l_fu_1163_p3 = 32'd12;
    end else if (p_Result_22_fu_1155_p3[13] == 1'b1) begin
        l_fu_1163_p3 = 32'd13;
    end else if (p_Result_22_fu_1155_p3[14] == 1'b1) begin
        l_fu_1163_p3 = 32'd14;
    end else if (p_Result_22_fu_1155_p3[15] == 1'b1) begin
        l_fu_1163_p3 = 32'd15;
    end else if (p_Result_22_fu_1155_p3[16] == 1'b1) begin
        l_fu_1163_p3 = 32'd16;
    end else if (p_Result_22_fu_1155_p3[17] == 1'b1) begin
        l_fu_1163_p3 = 32'd17;
    end else if (p_Result_22_fu_1155_p3[18] == 1'b1) begin
        l_fu_1163_p3 = 32'd18;
    end else if (p_Result_22_fu_1155_p3[19] == 1'b1) begin
        l_fu_1163_p3 = 32'd19;
    end else if (p_Result_22_fu_1155_p3[20] == 1'b1) begin
        l_fu_1163_p3 = 32'd20;
    end else if (p_Result_22_fu_1155_p3[21] == 1'b1) begin
        l_fu_1163_p3 = 32'd21;
    end else if (p_Result_22_fu_1155_p3[22] == 1'b1) begin
        l_fu_1163_p3 = 32'd22;
    end else if (p_Result_22_fu_1155_p3[23] == 1'b1) begin
        l_fu_1163_p3 = 32'd23;
    end else if (p_Result_22_fu_1155_p3[24] == 1'b1) begin
        l_fu_1163_p3 = 32'd24;
    end else if (p_Result_22_fu_1155_p3[25] == 1'b1) begin
        l_fu_1163_p3 = 32'd25;
    end else if (p_Result_22_fu_1155_p3[26] == 1'b1) begin
        l_fu_1163_p3 = 32'd26;
    end else if (p_Result_22_fu_1155_p3[27] == 1'b1) begin
        l_fu_1163_p3 = 32'd27;
    end else if (p_Result_22_fu_1155_p3[28] == 1'b1) begin
        l_fu_1163_p3 = 32'd28;
    end else if (p_Result_22_fu_1155_p3[29] == 1'b1) begin
        l_fu_1163_p3 = 32'd29;
    end else if (p_Result_22_fu_1155_p3[30] == 1'b1) begin
        l_fu_1163_p3 = 32'd30;
    end else if (p_Result_22_fu_1155_p3[31] == 1'b1) begin
        l_fu_1163_p3 = 32'd31;
    end else begin
        l_fu_1163_p3 = 32'd32;
    end
end

assign logits_addr_1_gep_fu_418_p3 = zext_ln110_reg_2433;

assign lsb_index_1_fu_1465_p2 = ($signed(32'd4294967272) + $signed(sub_ln944_1_fu_1455_p2));

assign lsb_index_2_fu_1797_p2 = ($signed(32'd4294967272) + $signed(sub_ln944_2_fu_1787_p2));

assign lsb_index_fu_1181_p2 = ($signed(32'd4294967272) + $signed(sub_ln944_fu_1171_p2));

assign lshr_ln947_1_fu_1501_p2 = 20'd1048575 >> zext_ln947_1_fu_1497_p1;

assign lshr_ln947_2_fu_1833_p2 = 20'd1048575 >> zext_ln947_2_fu_1829_p1;

assign lshr_ln947_fu_1217_p2 = 20'd1048575 >> zext_ln947_fu_1213_p1;

assign lshr_ln958_1_fu_1596_p2 = zext_ln957_2_fu_1587_p1 >> add_ln958_1_fu_1591_p2;

assign lshr_ln958_2_fu_1997_p2 = zext_ln957_3_fu_1989_p1 >> add_ln958_2_fu_1992_p2;

assign lshr_ln958_fu_1312_p2 = zext_ln957_1_fu_1303_p1 >> add_ln958_fu_1307_p2;

assign m_15_fu_1583_p1 = reg_727;

assign m_16_fu_1621_p3 = ((icmp_ln958_1_reg_2472[0:0] === 1'b1) ? zext_ln958_2_fu_1602_p1 : shl_ln958_1_fu_1615_p2);

assign m_17_fu_1631_p2 = (m_16_fu_1621_p3 + zext_ln961_1_fu_1628_p1);

assign m_1_fu_1337_p3 = ((icmp_ln958_reg_2414[0:0] === 1'b1) ? zext_ln958_fu_1318_p1 : shl_ln958_fu_1331_p2);

assign m_21_fu_1986_p1 = tmp_V_13_reg_2507;

assign m_22_fu_2022_p3 = ((icmp_ln958_2_reg_2524[0:0] === 1'b1) ? zext_ln958_4_fu_2003_p1 : shl_ln958_2_fu_2016_p2);

assign m_23_fu_2032_p2 = (m_22_fu_2022_p3 + zext_ln961_2_fu_2029_p1);

assign m_26_fu_1363_p1 = m_s_fu_1353_p4;

assign m_27_fu_1647_p1 = m_3_fu_1637_p4;

assign m_28_fu_2048_p1 = m_4_fu_2038_p4;

assign m_2_fu_1347_p2 = (m_1_fu_1337_p3 + zext_ln961_fu_1344_p1);

assign m_3_fu_1637_p4 = {{m_17_fu_1631_p2[63:1]}};

assign m_4_fu_2038_p4 = {{m_23_fu_2032_p2[63:1]}};

assign m_fu_1299_p1 = reg_727;

assign m_s_fu_1353_p4 = {{m_2_fu_1347_p2[63:1]}};

assign or_ln111_1_fu_1933_p2 = (icmp_ln111_reg_2492 | icmp_ln111_1_reg_2497);

assign or_ln111_2_fu_1949_p2 = (icmp_ln111_3_fu_1943_p2 | icmp_ln111_2_fu_1937_p2);

assign or_ln111_fu_1973_p2 = (xor_ln111_fu_1967_p2 | icmp_ln935_1_reg_2451);

assign or_ln949_1_fu_1559_p2 = (and_ln949_1_fu_1553_p2 | a_1_fu_1519_p2);

assign or_ln949_2_fu_1565_p3 = {{31'd0}, {or_ln949_1_fu_1559_p2}};

assign or_ln949_3_fu_1891_p2 = (and_ln949_2_fu_1885_p2 | a_2_fu_1851_p2);

assign or_ln949_4_fu_1897_p3 = {{31'd0}, {or_ln949_3_fu_1891_p2}};

assign or_ln949_fu_1275_p2 = (and_ln949_fu_1269_p2 | a_fu_1235_p2);

assign or_ln_fu_1281_p3 = {{31'd0}, {or_ln949_fu_1275_p2}};

assign p_Result_12_fu_1507_p2 = (lshr_ln947_1_fu_1501_p2 & grp_fu_709_p3);

assign p_Result_13_fu_1545_p3 = grp_fu_709_p3[add_ln949_1_fu_1539_p2];

integer ap_tvar_int_1;

always @ (tmp_V_13_fu_1754_p3) begin
    for (ap_tvar_int_1 = 20 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 19 - 0) begin
            p_Result_16_fu_1761_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            p_Result_16_fu_1761_p4[ap_tvar_int_1] = tmp_V_13_fu_1754_p3[19 - ap_tvar_int_1];
        end
    end
end

assign p_Result_18_fu_1839_p2 = (tmp_V_13_fu_1754_p3 & lshr_ln947_2_fu_1833_p2);

assign p_Result_19_fu_1877_p3 = tmp_V_13_fu_1754_p3[add_ln949_2_fu_1871_p2];

assign p_Result_22_fu_1155_p3 = {{12'd4095}, {grp_fu_717_p4}};

assign p_Result_23_fu_1401_p5 = {{m_26_fu_1363_p1[63:32]}, {tmp_s_fu_1394_p3}, {m_26_fu_1363_p1[22:0]}};

assign p_Result_25_fu_1439_p3 = {{12'd4095}, {grp_fu_717_p4}};

assign p_Result_26_fu_1685_p5 = {{m_27_fu_1647_p1[63:32]}, {tmp_4_fu_1678_p3}, {m_27_fu_1647_p1[22:0]}};

assign p_Result_27_fu_1742_p3 = tmp_V_11_reg_2444[32'd19];

assign p_Result_28_fu_1771_p3 = {{12'd4095}, {p_Result_16_fu_1761_p4}};

assign p_Result_29_fu_2086_p5 = {{m_28_fu_2048_p1[63:32]}, {tmp_6_fu_2079_p3}, {m_28_fu_2048_p1[22:0]}};

assign p_Result_3_fu_1261_p3 = grp_fu_709_p3[add_ln949_fu_1255_p2];

assign p_Result_4_fu_1223_p2 = (lshr_ln947_fu_1217_p2 & grp_fu_709_p3);

assign select_ln111_1_fu_2106_p3 = ((or_ln111_fu_1973_p2[0:0] === 1'b1) ? select_ln111_fu_1978_p3 : bitcast_ln739_2_fu_2102_p1);

assign select_ln111_fu_1978_p3 = ((and_ln111_1_fu_1961_p2[0:0] === 1'b1) ? 32'd0 : maxv_0_reg_597);

assign select_ln935_fu_1421_p3 = ((icmp_ln935_reg_2393[0:0] === 1'b1) ? 32'd0 : bitcast_ln739_fu_1417_p1);

assign select_ln964_1_fu_1659_p3 = ((tmp_20_fu_1651_p3[0:0] === 1'b1) ? 8'd127 : 8'd126);

assign select_ln964_2_fu_2060_p3 = ((tmp_24_fu_2052_p3[0:0] === 1'b1) ? 8'd127 : 8'd126);

assign select_ln964_fu_1375_p3 = ((tmp_15_fu_1367_p3[0:0] === 1'b1) ? 8'd127 : 8'd126);

assign sext_ln104_fu_1095_p1 = $signed(B4_V_q0);

assign sext_ln94_fu_875_p1 = $signed(B2_V_q0);

assign sext_ln99_fu_985_p1 = $signed(B3_V_q0);

assign shl_ln958_1_fu_1615_p2 = m_15_fu_1583_p1 << zext_ln958_3_fu_1611_p1;

assign shl_ln958_2_fu_2016_p2 = m_21_fu_1986_p1 << zext_ln958_5_fu_2012_p1;

assign shl_ln958_fu_1331_p2 = m_fu_1299_p1 << zext_ln958_1_fu_1327_p1;

assign sub_ln944_1_fu_1455_p2 = (32'd20 - l_1_fu_1447_p3);

assign sub_ln944_2_fu_1787_p2 = (32'd20 - l_2_fu_1779_p3);

assign sub_ln944_fu_1171_p2 = (32'd20 - l_fu_1163_p3);

assign sub_ln947_1_fu_1491_p2 = (5'd13 - trunc_ln947_1_fu_1487_p1);

assign sub_ln947_2_fu_1823_p2 = (5'd13 - trunc_ln947_2_fu_1819_p1);

assign sub_ln947_fu_1207_p2 = (5'd13 - trunc_ln947_fu_1203_p1);

assign sub_ln958_1_fu_1606_p2 = (32'd25 - sub_ln944_1_reg_2461);

assign sub_ln958_2_fu_2007_p2 = (32'd25 - sub_ln944_2_reg_2513);

assign sub_ln958_fu_1322_p2 = (32'd25 - sub_ln944_reg_2403);

assign sub_ln964_1_fu_1667_p2 = (8'd6 - trunc_ln943_1_reg_2477);

assign sub_ln964_2_fu_2068_p2 = (8'd6 - trunc_ln943_2_reg_2529);

assign sub_ln964_fu_1383_p2 = (8'd6 - trunc_ln943_reg_2419);

assign tmp_10_fu_794_p3 = p_Val2_1_reg_476[32'd19];

assign tmp_11_fu_914_p3 = p_Val2_4_reg_509[32'd19];

assign tmp_13_fu_1187_p4 = {{lsb_index_fu_1181_p2[31:1]}};

assign tmp_14_fu_1241_p3 = lsb_index_fu_1181_p2[32'd31];

assign tmp_15_fu_1367_p3 = m_2_fu_1347_p2[32'd25];

assign tmp_16_fu_1024_p3 = p_Val2_9_reg_542[32'd19];

assign tmp_18_fu_1471_p4 = {{lsb_index_1_fu_1465_p2[31:1]}};

assign tmp_19_fu_1525_p3 = lsb_index_1_fu_1465_p2[32'd31];

assign tmp_1_fu_1716_p4 = {{bitcast_ln111_fu_1712_p1[30:23]}};

assign tmp_20_fu_1651_p3 = m_17_fu_1631_p2[32'd25];

assign tmp_22_fu_1803_p4 = {{lsb_index_2_fu_1797_p2[31:1]}};

assign tmp_23_fu_1857_p3 = lsb_index_2_fu_1797_p2[32'd31];

assign tmp_24_fu_2052_p3 = m_23_fu_2032_p2[32'd25];

assign tmp_3_fu_1919_p4 = {{bitcast_ln111_1_fu_1915_p1[30:23]}};

assign tmp_4_fu_1678_p3 = {{p_Result_24_reg_2456}, {add_ln964_1_fu_1672_p2}};

assign tmp_6_fu_2079_p3 = {{p_Result_27_reg_2502}, {add_ln964_2_fu_2073_p2}};

assign tmp_7_fu_857_p3 = {{j4_0_reg_497}, {2'd0}};

assign tmp_8_fu_973_p3 = {{j5_0_reg_530}, {3'd0}};

assign tmp_9_fu_1083_p3 = {{j6_0_reg_563}, {3'd0}};

assign tmp_V_13_fu_1754_p3 = ((p_Result_27_fu_1742_p3[0:0] === 1'b1) ? tmp_V_7_fu_1749_p2 : tmp_V_11_reg_2444);

assign tmp_V_7_fu_1749_p2 = (20'd0 - tmp_V_11_reg_2444);

assign tmp_s_fu_1394_p3 = {{p_Result_21_reg_2398}, {add_ln964_fu_1388_p2}};

assign trunc_ln111_1_fu_1929_p1 = bitcast_ln111_1_fu_1915_p1[22:0];

assign trunc_ln111_fu_1726_p1 = bitcast_ln111_fu_1712_p1[22:0];

assign trunc_ln738_1_fu_1697_p1 = p_Result_26_fu_1685_p5[31:0];

assign trunc_ln738_2_fu_2098_p1 = p_Result_29_fu_2086_p5[31:0];

assign trunc_ln738_fu_1413_p1 = p_Result_23_fu_1401_p5[31:0];

assign trunc_ln943_1_fu_1579_p1 = l_1_fu_1447_p3[7:0];

assign trunc_ln943_2_fu_1911_p1 = l_2_fu_1779_p3[7:0];

assign trunc_ln943_fu_1295_p1 = l_fu_1163_p3[7:0];

assign trunc_ln944_1_fu_1461_p1 = sub_ln944_1_fu_1455_p2[19:0];

assign trunc_ln944_2_fu_1793_p1 = sub_ln944_2_fu_1787_p2[19:0];

assign trunc_ln944_fu_1177_p1 = sub_ln944_fu_1171_p2[19:0];

assign trunc_ln947_1_fu_1487_p1 = sub_ln944_1_fu_1455_p2[4:0];

assign trunc_ln947_2_fu_1819_p1 = sub_ln944_2_fu_1787_p2[4:0];

assign trunc_ln947_fu_1203_p1 = sub_ln944_fu_1171_p2[4:0];

assign xor_ln111_fu_1967_p2 = (1'd1 ^ and_ln111_1_fu_1961_p2);

assign xor_ln949_1_fu_1533_p2 = (tmp_19_fu_1525_p3 ^ 1'd1);

assign xor_ln949_2_fu_1865_p2 = (tmp_23_fu_1857_p3 ^ 1'd1);

assign xor_ln949_fu_1249_p2 = (tmp_14_fu_1241_p3 ^ 1'd1);

assign zext_ln104_1_fu_1091_p1 = tmp_9_fu_1083_p3;

assign zext_ln104_fu_1078_p1 = j6_0_reg_563;

assign zext_ln110_fu_1434_p1 = j7_0_reg_607;

assign zext_ln1117_1_fu_865_p1 = tmp_7_fu_857_p3;

assign zext_ln1117_2_fu_775_p1 = i_0_i_reg_486;

assign zext_ln1117_3_fu_785_p1 = add_ln1117_1_fu_779_p2;

assign zext_ln1117_4_fu_896_p1 = i_0_i10_reg_519;

assign zext_ln1117_5_fu_905_p1 = add_ln1117_2_fu_900_p2;

assign zext_ln1117_6_fu_1006_p1 = i_0_i26_reg_552;

assign zext_ln1117_7_fu_1015_p1 = add_ln1117_3_fu_1010_p2;

assign zext_ln1117_8_fu_1116_p1 = i_0_i42_reg_586;

assign zext_ln1117_9_fu_1125_p1 = add_ln1117_4_fu_1120_p2;

assign zext_ln1117_fu_853_p1 = j4_0_reg_497;

assign zext_ln119_fu_2126_p1 = j8_0_reg_643;

assign zext_ln125_fu_2143_p1 = j9_0_reg_654;

assign zext_ln69_1_fu_891_p1 = i_0_i10_reg_519;

assign zext_ln69_2_fu_1001_p1 = i_0_i26_reg_552;

assign zext_ln69_3_fu_1111_p1 = i_0_i42_reg_586;

assign zext_ln69_fu_770_p1 = i_0_i_reg_486;

assign zext_ln89_1_fu_754_p1 = B1_V_q0;

assign zext_ln89_fu_749_p1 = j_0_reg_453;

assign zext_ln947_1_fu_1497_p1 = sub_ln947_1_fu_1491_p2;

assign zext_ln947_2_fu_1829_p1 = sub_ln947_2_fu_1823_p2;

assign zext_ln947_fu_1213_p1 = sub_ln947_fu_1207_p2;

assign zext_ln94_fu_848_p1 = j4_0_reg_497;

assign zext_ln957_1_fu_1303_p1 = reg_727;

assign zext_ln957_2_fu_1587_p1 = reg_727;

assign zext_ln957_3_fu_1989_p1 = tmp_V_13_reg_2507;

assign zext_ln958_1_fu_1327_p1 = sub_ln958_fu_1322_p2;

assign zext_ln958_2_fu_1602_p1 = lshr_ln958_1_fu_1596_p2;

assign zext_ln958_3_fu_1611_p1 = sub_ln958_1_fu_1606_p2;

assign zext_ln958_4_fu_2003_p1 = lshr_ln958_2_fu_1997_p2;

assign zext_ln958_5_fu_2012_p1 = sub_ln958_2_fu_2007_p2;

assign zext_ln958_fu_1318_p1 = lshr_ln958_fu_1312_p2;

assign zext_ln961_1_fu_1628_p1 = or_ln949_2_reg_2467;

assign zext_ln961_2_fu_2029_p1 = or_ln949_4_reg_2519;

assign zext_ln961_fu_1344_p1 = or_ln_reg_2409;

assign zext_ln99_1_fu_981_p1 = tmp_8_fu_973_p3;

assign zext_ln99_fu_968_p1 = j5_0_reg_530;

always @ (posedge ap_clk) begin
    zext_ln89_reg_2197[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln94_reg_2243[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln99_reg_2294[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln99_1_reg_2304[2:0] <= 3'b000;
    zext_ln99_1_reg_2304[7] <= 1'b0;
    zext_ln104_reg_2345[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln104_1_reg_2360[2:0] <= 3'b000;
    zext_ln104_1_reg_2360[7] <= 1'b0;
    or_ln_reg_2409[31:1] <= 31'b0000000000000000000000000000000;
    zext_ln110_reg_2433[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    or_ln949_2_reg_2467[31:1] <= 31'b0000000000000000000000000000000;
    or_ln949_4_reg_2519[31:1] <= 31'b0000000000000000000000000000000;
    zext_ln119_reg_2547[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //mlp
