// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "matrix_vector_mult.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic matrix_vector_mult::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic matrix_vector_mult::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> matrix_vector_mult::ap_ST_fsm_state1 = "1";
const sc_lv<4> matrix_vector_mult::ap_ST_fsm_state2 = "10";
const sc_lv<4> matrix_vector_mult::ap_ST_fsm_state3 = "100";
const sc_lv<4> matrix_vector_mult::ap_ST_fsm_state4 = "1000";
const sc_lv<32> matrix_vector_mult::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> matrix_vector_mult::ap_const_lv32_1 = "1";
const sc_lv<1> matrix_vector_mult::ap_const_lv1_0 = "0";
const sc_lv<32> matrix_vector_mult::ap_const_lv32_2 = "10";
const sc_lv<32> matrix_vector_mult::ap_const_lv32_3 = "11";
const sc_lv<2> matrix_vector_mult::ap_const_lv2_0 = "00";
const sc_lv<1> matrix_vector_mult::ap_const_lv1_1 = "1";
const sc_lv<2> matrix_vector_mult::ap_const_lv2_3 = "11";
const sc_lv<2> matrix_vector_mult::ap_const_lv2_1 = "1";
const bool matrix_vector_mult::ap_const_boolean_1 = true;

matrix_vector_mult::matrix_vector_mult(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln10_1_fu_161_p2);
    sensitive << ( sub_ln10_reg_191 );
    sensitive << ( zext_ln10_3_fu_157_p1 );

    SC_METHOD(thread_add_ln10_fu_177_p2);
    sensitive << ( result_load_reg_77 );
    sensitive << ( mul_ln10_fu_171_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln7_fu_101_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln7_fu_101_p2 );

    SC_METHOD(thread_i_fu_107_p2);
    sensitive << ( i_0_reg_66 );

    SC_METHOD(thread_icmp_ln7_fu_101_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_66 );

    SC_METHOD(thread_icmp_ln9_fu_140_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( j_0_reg_90 );

    SC_METHOD(thread_j_fu_146_p2);
    sensitive << ( j_0_reg_90 );

    SC_METHOD(thread_mat_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( sext_ln10_fu_166_p1 );

    SC_METHOD(thread_mat_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_mul_ln10_fu_171_p0);
    sensitive << ( vec_q0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_mul_ln10_fu_171_p1);
    sensitive << ( mat_q0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_mul_ln10_fu_171_p2);
    sensitive << ( mul_ln10_fu_171_p0 );
    sensitive << ( mul_ln10_fu_171_p1 );

    SC_METHOD(thread_result_address0);
    sensitive << ( result_addr_reg_196 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_result_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_result_d0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( result_load_reg_77 );

    SC_METHOD(thread_result_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_sext_ln10_fu_166_p1);
    sensitive << ( add_ln10_1_fu_161_p2 );

    SC_METHOD(thread_sub_ln10_fu_134_p2);
    sensitive << ( zext_ln10_2_fu_130_p1 );
    sensitive << ( zext_ln10_1_fu_118_p1 );

    SC_METHOD(thread_tmp_fu_122_p3);
    sensitive << ( i_0_reg_66 );

    SC_METHOD(thread_vec_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln10_fu_152_p1 );

    SC_METHOD(thread_vec_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_zext_ln10_1_fu_118_p1);
    sensitive << ( i_0_reg_66 );

    SC_METHOD(thread_zext_ln10_2_fu_130_p1);
    sensitive << ( tmp_fu_122_p3 );

    SC_METHOD(thread_zext_ln10_3_fu_157_p1);
    sensitive << ( j_0_reg_90 );

    SC_METHOD(thread_zext_ln10_fu_152_p1);
    sensitive << ( j_0_reg_90 );

    SC_METHOD(thread_zext_ln8_fu_113_p1);
    sensitive << ( i_0_reg_66 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln7_fu_101_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln9_fu_140_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "0001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "matrix_vector_mult_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, mat_address0, "(port)mat_address0");
    sc_trace(mVcdFile, mat_ce0, "(port)mat_ce0");
    sc_trace(mVcdFile, mat_q0, "(port)mat_q0");
    sc_trace(mVcdFile, vec_address0, "(port)vec_address0");
    sc_trace(mVcdFile, vec_ce0, "(port)vec_ce0");
    sc_trace(mVcdFile, vec_q0, "(port)vec_q0");
    sc_trace(mVcdFile, result_address0, "(port)result_address0");
    sc_trace(mVcdFile, result_ce0, "(port)result_ce0");
    sc_trace(mVcdFile, result_we0, "(port)result_we0");
    sc_trace(mVcdFile, result_d0, "(port)result_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i_fu_107_p2, "i_fu_107_p2");
    sc_trace(mVcdFile, i_reg_186, "i_reg_186");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, sub_ln10_fu_134_p2, "sub_ln10_fu_134_p2");
    sc_trace(mVcdFile, sub_ln10_reg_191, "sub_ln10_reg_191");
    sc_trace(mVcdFile, icmp_ln7_fu_101_p2, "icmp_ln7_fu_101_p2");
    sc_trace(mVcdFile, result_addr_reg_196, "result_addr_reg_196");
    sc_trace(mVcdFile, j_fu_146_p2, "j_fu_146_p2");
    sc_trace(mVcdFile, j_reg_204, "j_reg_204");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, icmp_ln9_fu_140_p2, "icmp_ln9_fu_140_p2");
    sc_trace(mVcdFile, add_ln10_fu_177_p2, "add_ln10_fu_177_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, i_0_reg_66, "i_0_reg_66");
    sc_trace(mVcdFile, result_load_reg_77, "result_load_reg_77");
    sc_trace(mVcdFile, j_0_reg_90, "j_0_reg_90");
    sc_trace(mVcdFile, zext_ln8_fu_113_p1, "zext_ln8_fu_113_p1");
    sc_trace(mVcdFile, sext_ln10_fu_166_p1, "sext_ln10_fu_166_p1");
    sc_trace(mVcdFile, zext_ln10_fu_152_p1, "zext_ln10_fu_152_p1");
    sc_trace(mVcdFile, tmp_fu_122_p3, "tmp_fu_122_p3");
    sc_trace(mVcdFile, zext_ln10_2_fu_130_p1, "zext_ln10_2_fu_130_p1");
    sc_trace(mVcdFile, zext_ln10_1_fu_118_p1, "zext_ln10_1_fu_118_p1");
    sc_trace(mVcdFile, zext_ln10_3_fu_157_p1, "zext_ln10_3_fu_157_p1");
    sc_trace(mVcdFile, add_ln10_1_fu_161_p2, "add_ln10_1_fu_161_p2");
    sc_trace(mVcdFile, mul_ln10_fu_171_p0, "mul_ln10_fu_171_p0");
    sc_trace(mVcdFile, mul_ln10_fu_171_p1, "mul_ln10_fu_171_p1");
    sc_trace(mVcdFile, mul_ln10_fu_171_p2, "mul_ln10_fu_171_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("matrix_vector_mult.hdltvin.dat");
    mHdltvoutHandle.open("matrix_vector_mult.hdltvout.dat");
}

matrix_vector_mult::~matrix_vector_mult() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void matrix_vector_mult::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln9_fu_140_p2.read(), ap_const_lv1_1))) {
        i_0_reg_66 = i_reg_186.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_66 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        j_0_reg_90 = j_reg_204.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln7_fu_101_p2.read(), ap_const_lv1_0))) {
        j_0_reg_90 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        result_load_reg_77 = add_ln10_fu_177_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln7_fu_101_p2.read(), ap_const_lv1_0))) {
        result_load_reg_77 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_186 = i_fu_107_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        j_reg_204 = j_fu_146_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln7_fu_101_p2.read(), ap_const_lv1_0))) {
        result_addr_reg_196 =  (sc_lv<2>) (zext_ln8_fu_113_p1.read());
        sub_ln10_reg_191 = sub_ln10_fu_134_p2.read();
    }
}

void matrix_vector_mult::thread_add_ln10_1_fu_161_p2() {
    add_ln10_1_fu_161_p2 = (!sub_ln10_reg_191.read().is_01() || !zext_ln10_3_fu_157_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(sub_ln10_reg_191.read()) + sc_biguint<5>(zext_ln10_3_fu_157_p1.read()));
}

void matrix_vector_mult::thread_add_ln10_fu_177_p2() {
    add_ln10_fu_177_p2 = (!mul_ln10_fu_171_p2.read().is_01() || !result_load_reg_77.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln10_fu_171_p2.read()) + sc_biguint<32>(result_load_reg_77.read()));
}

void matrix_vector_mult::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void matrix_vector_mult::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void matrix_vector_mult::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void matrix_vector_mult::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void matrix_vector_mult::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln7_fu_101_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void matrix_vector_mult::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void matrix_vector_mult::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln7_fu_101_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void matrix_vector_mult::thread_i_fu_107_p2() {
    i_fu_107_p2 = (!i_0_reg_66.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i_0_reg_66.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void matrix_vector_mult::thread_icmp_ln7_fu_101_p2() {
    icmp_ln7_fu_101_p2 = (!i_0_reg_66.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_66.read() == ap_const_lv2_3);
}

void matrix_vector_mult::thread_icmp_ln9_fu_140_p2() {
    icmp_ln9_fu_140_p2 = (!j_0_reg_90.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(j_0_reg_90.read() == ap_const_lv2_3);
}

void matrix_vector_mult::thread_j_fu_146_p2() {
    j_fu_146_p2 = (!j_0_reg_90.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(j_0_reg_90.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void matrix_vector_mult::thread_mat_address0() {
    mat_address0 =  (sc_lv<4>) (sext_ln10_fu_166_p1.read());
}

void matrix_vector_mult::thread_mat_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        mat_ce0 = ap_const_logic_1;
    } else {
        mat_ce0 = ap_const_logic_0;
    }
}

void matrix_vector_mult::thread_mul_ln10_fu_171_p0() {
    mul_ln10_fu_171_p0 = vec_q0.read();
}

void matrix_vector_mult::thread_mul_ln10_fu_171_p1() {
    mul_ln10_fu_171_p1 = mat_q0.read();
}

void matrix_vector_mult::thread_mul_ln10_fu_171_p2() {
    mul_ln10_fu_171_p2 = (!mul_ln10_fu_171_p0.read().is_01() || !mul_ln10_fu_171_p1.read().is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln10_fu_171_p0.read()) * sc_bigint<32>(mul_ln10_fu_171_p1.read());
}

void matrix_vector_mult::thread_result_address0() {
    result_address0 = result_addr_reg_196.read();
}

void matrix_vector_mult::thread_result_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        result_ce0 = ap_const_logic_1;
    } else {
        result_ce0 = ap_const_logic_0;
    }
}

void matrix_vector_mult::thread_result_d0() {
    result_d0 = result_load_reg_77.read();
}

void matrix_vector_mult::thread_result_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        result_we0 = ap_const_logic_1;
    } else {
        result_we0 = ap_const_logic_0;
    }
}

void matrix_vector_mult::thread_sext_ln10_fu_166_p1() {
    sext_ln10_fu_166_p1 = esl_sext<64,5>(add_ln10_1_fu_161_p2.read());
}

void matrix_vector_mult::thread_sub_ln10_fu_134_p2() {
    sub_ln10_fu_134_p2 = (!zext_ln10_2_fu_130_p1.read().is_01() || !zext_ln10_1_fu_118_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(zext_ln10_2_fu_130_p1.read()) - sc_biguint<5>(zext_ln10_1_fu_118_p1.read()));
}

void matrix_vector_mult::thread_tmp_fu_122_p3() {
    tmp_fu_122_p3 = esl_concat<2,2>(i_0_reg_66.read(), ap_const_lv2_0);
}

void matrix_vector_mult::thread_vec_address0() {
    vec_address0 =  (sc_lv<2>) (zext_ln10_fu_152_p1.read());
}

void matrix_vector_mult::thread_vec_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        vec_ce0 = ap_const_logic_1;
    } else {
        vec_ce0 = ap_const_logic_0;
    }
}

void matrix_vector_mult::thread_zext_ln10_1_fu_118_p1() {
    zext_ln10_1_fu_118_p1 = esl_zext<5,2>(i_0_reg_66.read());
}

void matrix_vector_mult::thread_zext_ln10_2_fu_130_p1() {
    zext_ln10_2_fu_130_p1 = esl_zext<5,4>(tmp_fu_122_p3.read());
}

void matrix_vector_mult::thread_zext_ln10_3_fu_157_p1() {
    zext_ln10_3_fu_157_p1 = esl_zext<5,2>(j_0_reg_90.read());
}

void matrix_vector_mult::thread_zext_ln10_fu_152_p1() {
    zext_ln10_fu_152_p1 = esl_zext<64,2>(j_0_reg_90.read());
}

void matrix_vector_mult::thread_zext_ln8_fu_113_p1() {
    zext_ln8_fu_113_p1 = esl_zext<64,2>(i_0_reg_66.read());
}

void matrix_vector_mult::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln7_fu_101_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln9_fu_140_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

void matrix_vector_mult::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mat_address0\" :  \"" << mat_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"mat_ce0\" :  \"" << mat_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mat_q0\" :  \"" << mat_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"vec_address0\" :  \"" << vec_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"vec_ce0\" :  \"" << vec_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"vec_q0\" :  \"" << vec_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"result_address0\" :  \"" << result_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"result_ce0\" :  \"" << result_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"result_we0\" :  \"" << result_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"result_d0\" :  \"" << result_d0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

