// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _matrix_vector_mult_HH_
#define _matrix_vector_mult_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct matrix_vector_mult : public sc_module {
    // Port declarations 16
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<4> > mat_address0;
    sc_out< sc_logic > mat_ce0;
    sc_in< sc_lv<32> > mat_q0;
    sc_out< sc_lv<2> > vec_address0;
    sc_out< sc_logic > vec_ce0;
    sc_in< sc_lv<32> > vec_q0;
    sc_out< sc_lv<2> > result_address0;
    sc_out< sc_logic > result_ce0;
    sc_out< sc_logic > result_we0;
    sc_out< sc_lv<32> > result_d0;


    // Module declarations
    matrix_vector_mult(sc_module_name name);
    SC_HAS_PROCESS(matrix_vector_mult);

    ~matrix_vector_mult();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<2> > i_fu_107_p2;
    sc_signal< sc_lv<2> > i_reg_186;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<5> > sub_ln10_fu_134_p2;
    sc_signal< sc_lv<5> > sub_ln10_reg_191;
    sc_signal< sc_lv<1> > icmp_ln7_fu_101_p2;
    sc_signal< sc_lv<2> > result_addr_reg_196;
    sc_signal< sc_lv<2> > j_fu_146_p2;
    sc_signal< sc_lv<2> > j_reg_204;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > icmp_ln9_fu_140_p2;
    sc_signal< sc_lv<32> > add_ln10_fu_177_p2;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<2> > i_0_reg_66;
    sc_signal< sc_lv<32> > result_load_reg_77;
    sc_signal< sc_lv<2> > j_0_reg_90;
    sc_signal< sc_lv<64> > zext_ln8_fu_113_p1;
    sc_signal< sc_lv<64> > sext_ln10_fu_166_p1;
    sc_signal< sc_lv<64> > zext_ln10_fu_152_p1;
    sc_signal< sc_lv<4> > tmp_fu_122_p3;
    sc_signal< sc_lv<5> > zext_ln10_2_fu_130_p1;
    sc_signal< sc_lv<5> > zext_ln10_1_fu_118_p1;
    sc_signal< sc_lv<5> > zext_ln10_3_fu_157_p1;
    sc_signal< sc_lv<5> > add_ln10_1_fu_161_p2;
    sc_signal< sc_lv<32> > mul_ln10_fu_171_p0;
    sc_signal< sc_lv<32> > mul_ln10_fu_171_p1;
    sc_signal< sc_lv<32> > mul_ln10_fu_171_p2;
    sc_signal< sc_lv<4> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<4> ap_ST_fsm_state1;
    static const sc_lv<4> ap_ST_fsm_state2;
    static const sc_lv<4> ap_ST_fsm_state3;
    static const sc_lv<4> ap_ST_fsm_state4;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln10_1_fu_161_p2();
    void thread_add_ln10_fu_177_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_i_fu_107_p2();
    void thread_icmp_ln7_fu_101_p2();
    void thread_icmp_ln9_fu_140_p2();
    void thread_j_fu_146_p2();
    void thread_mat_address0();
    void thread_mat_ce0();
    void thread_mul_ln10_fu_171_p0();
    void thread_mul_ln10_fu_171_p1();
    void thread_mul_ln10_fu_171_p2();
    void thread_result_address0();
    void thread_result_ce0();
    void thread_result_d0();
    void thread_result_we0();
    void thread_sext_ln10_fu_166_p1();
    void thread_sub_ln10_fu_134_p2();
    void thread_tmp_fu_122_p3();
    void thread_vec_address0();
    void thread_vec_ce0();
    void thread_zext_ln10_1_fu_118_p1();
    void thread_zext_ln10_2_fu_130_p1();
    void thread_zext_ln10_3_fu_157_p1();
    void thread_zext_ln10_fu_152_p1();
    void thread_zext_ln8_fu_113_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
