// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mlp,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu3eg-sbva484-1-i,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.354000,HLS_SYN_LAT=8866,HLS_SYN_TPT=none,HLS_SYN_MEM=6,HLS_SYN_DSP=13,HLS_SYN_FF=2952,HLS_SYN_LUT=6019,HLS_VERSION=2019_1}" *)

module mlp (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_V_address0,
        input_V_ce0,
        input_V_q0,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0,
        output_r_q0
);

parameter    ap_ST_fsm_state1 = 77'd1;
parameter    ap_ST_fsm_state2 = 77'd2;
parameter    ap_ST_fsm_state3 = 77'd4;
parameter    ap_ST_fsm_state4 = 77'd8;
parameter    ap_ST_fsm_state5 = 77'd16;
parameter    ap_ST_fsm_state6 = 77'd32;
parameter    ap_ST_fsm_state7 = 77'd64;
parameter    ap_ST_fsm_state8 = 77'd128;
parameter    ap_ST_fsm_state9 = 77'd256;
parameter    ap_ST_fsm_state10 = 77'd512;
parameter    ap_ST_fsm_state11 = 77'd1024;
parameter    ap_ST_fsm_state12 = 77'd2048;
parameter    ap_ST_fsm_state13 = 77'd4096;
parameter    ap_ST_fsm_state14 = 77'd8192;
parameter    ap_ST_fsm_state15 = 77'd16384;
parameter    ap_ST_fsm_state16 = 77'd32768;
parameter    ap_ST_fsm_state17 = 77'd65536;
parameter    ap_ST_fsm_state18 = 77'd131072;
parameter    ap_ST_fsm_state19 = 77'd262144;
parameter    ap_ST_fsm_state20 = 77'd524288;
parameter    ap_ST_fsm_state21 = 77'd1048576;
parameter    ap_ST_fsm_state22 = 77'd2097152;
parameter    ap_ST_fsm_state23 = 77'd4194304;
parameter    ap_ST_fsm_state24 = 77'd8388608;
parameter    ap_ST_fsm_state25 = 77'd16777216;
parameter    ap_ST_fsm_state26 = 77'd33554432;
parameter    ap_ST_fsm_state27 = 77'd67108864;
parameter    ap_ST_fsm_state28 = 77'd134217728;
parameter    ap_ST_fsm_state29 = 77'd268435456;
parameter    ap_ST_fsm_state30 = 77'd536870912;
parameter    ap_ST_fsm_state31 = 77'd1073741824;
parameter    ap_ST_fsm_state32 = 77'd2147483648;
parameter    ap_ST_fsm_state33 = 77'd4294967296;
parameter    ap_ST_fsm_state34 = 77'd8589934592;
parameter    ap_ST_fsm_state35 = 77'd17179869184;
parameter    ap_ST_fsm_state36 = 77'd34359738368;
parameter    ap_ST_fsm_state37 = 77'd68719476736;
parameter    ap_ST_fsm_state38 = 77'd137438953472;
parameter    ap_ST_fsm_state39 = 77'd274877906944;
parameter    ap_ST_fsm_state40 = 77'd549755813888;
parameter    ap_ST_fsm_state41 = 77'd1099511627776;
parameter    ap_ST_fsm_state42 = 77'd2199023255552;
parameter    ap_ST_fsm_state43 = 77'd4398046511104;
parameter    ap_ST_fsm_state44 = 77'd8796093022208;
parameter    ap_ST_fsm_state45 = 77'd17592186044416;
parameter    ap_ST_fsm_state46 = 77'd35184372088832;
parameter    ap_ST_fsm_state47 = 77'd70368744177664;
parameter    ap_ST_fsm_state48 = 77'd140737488355328;
parameter    ap_ST_fsm_state49 = 77'd281474976710656;
parameter    ap_ST_fsm_state50 = 77'd562949953421312;
parameter    ap_ST_fsm_state51 = 77'd1125899906842624;
parameter    ap_ST_fsm_state52 = 77'd2251799813685248;
parameter    ap_ST_fsm_state53 = 77'd4503599627370496;
parameter    ap_ST_fsm_state54 = 77'd9007199254740992;
parameter    ap_ST_fsm_state55 = 77'd18014398509481984;
parameter    ap_ST_fsm_state56 = 77'd36028797018963968;
parameter    ap_ST_fsm_state57 = 77'd72057594037927936;
parameter    ap_ST_fsm_state58 = 77'd144115188075855872;
parameter    ap_ST_fsm_state59 = 77'd288230376151711744;
parameter    ap_ST_fsm_state60 = 77'd576460752303423488;
parameter    ap_ST_fsm_state61 = 77'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 77'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 77'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 77'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 77'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 77'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 77'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 77'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 77'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 77'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 77'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 77'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 77'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 77'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 77'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 77'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 77'd75557863725914323419136;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] input_V_address0;
output   input_V_ce0;
input  [19:0] input_V_q0;
output  [3:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [31:0] output_r_d0;
input  [31:0] output_r_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_V_ce0;
reg[3:0] output_r_address0;
reg output_r_ce0;
reg output_r_we0;
reg[31:0] output_r_d0;

(* fsm_encoding = "none" *) reg   [76:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] B1_V_address0;
reg    B1_V_ce0;
wire   [12:0] B1_V_q0;
wire   [11:0] W1_V_address0;
reg    W1_V_ce0;
wire  signed [15:0] W1_V_q0;
wire   [2:0] B2_V_address0;
reg    B2_V_ce0;
wire   [14:0] B2_V_q0;
wire   [5:0] W2_V_address0;
reg    W2_V_ce0;
wire  signed [15:0] W2_V_q0;
wire   [2:0] B3_V_address0;
reg    B3_V_ce0;
wire   [14:0] B3_V_q0;
wire   [5:0] W3_V_address0;
reg    W3_V_ce0;
wire  signed [15:0] W3_V_q0;
wire   [3:0] B4_V_address0;
reg    B4_V_ce0;
wire   [15:0] B4_V_q0;
wire   [6:0] W4_V_address0;
reg    W4_V_ce0;
wire  signed [15:0] W4_V_q0;
wire   [19:0] z4_V_q0;
reg   [19:0] reg_701;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state23;
wire   [11:0] add_ln88_fu_706_p2;
reg   [11:0] add_ln88_reg_2194;
wire    ap_CS_fsm_state2;
wire   [2:0] j_fu_718_p2;
reg   [2:0] j_reg_2202;
wire   [63:0] zext_ln89_fu_724_p1;
reg   [63:0] zext_ln89_reg_2207;
wire   [0:0] icmp_ln88_fu_712_p2;
wire   [19:0] zext_ln89_1_fu_729_p1;
wire    ap_CS_fsm_state3;
wire   [9:0] i_fu_739_p2;
reg   [9:0] i_reg_2225;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln68_fu_733_p2;
wire    ap_CS_fsm_state5;
wire   [3:0] j_1_fu_817_p2;
reg   [3:0] j_1_reg_2248;
wire    ap_CS_fsm_state6;
wire   [63:0] zext_ln94_fu_823_p1;
reg   [63:0] zext_ln94_reg_2253;
wire   [0:0] icmp_ln93_fu_811_p2;
wire   [6:0] add_ln1117_fu_844_p2;
reg   [6:0] add_ln1117_reg_2263;
wire    ap_CS_fsm_state7;
wire  signed [19:0] sext_ln94_fu_850_p1;
wire   [2:0] i_1_fu_860_p2;
reg   [2:0] i_1_reg_2276;
wire    ap_CS_fsm_state8;
wire   [0:0] icmp_ln68_1_fu_854_p2;
wire    ap_CS_fsm_state9;
wire   [3:0] j_2_fu_937_p2;
reg   [3:0] j_2_reg_2299;
wire    ap_CS_fsm_state10;
wire   [63:0] zext_ln99_fu_943_p1;
reg   [63:0] zext_ln99_reg_2304;
wire   [0:0] icmp_ln98_fu_931_p2;
wire   [7:0] zext_ln99_1_fu_956_p1;
reg   [7:0] zext_ln99_1_reg_2314;
wire    ap_CS_fsm_state11;
wire  signed [19:0] sext_ln99_fu_960_p1;
wire   [3:0] i_2_fu_970_p2;
reg   [3:0] i_2_reg_2327;
wire    ap_CS_fsm_state12;
wire   [0:0] icmp_ln68_2_fu_964_p2;
wire    ap_CS_fsm_state13;
wire   [3:0] j_3_fu_1047_p2;
reg   [3:0] j_3_reg_2350;
wire    ap_CS_fsm_state14;
wire   [63:0] zext_ln104_fu_1053_p1;
reg   [63:0] zext_ln104_reg_2355;
wire   [0:0] icmp_ln103_fu_1041_p2;
wire   [7:0] zext_ln104_1_fu_1066_p1;
reg   [7:0] zext_ln104_1_reg_2370;
wire    ap_CS_fsm_state15;
wire  signed [19:0] sext_ln104_fu_1070_p1;
wire   [3:0] i_3_fu_1080_p2;
reg   [3:0] i_3_reg_2383;
wire    ap_CS_fsm_state16;
wire   [0:0] icmp_ln68_3_fu_1074_p2;
wire    ap_CS_fsm_state17;
wire   [0:0] grp_fu_687_p3;
reg   [0:0] p_Result_21_reg_2403;
wire   [0:0] icmp_ln935_fu_1130_p2;
reg   [0:0] icmp_ln935_reg_2409;
wire    ap_CS_fsm_state19;
wire   [19:0] tmp_V_10_fu_1142_p3;
reg   [19:0] tmp_V_10_reg_2414;
wire   [31:0] sub_ln944_fu_1175_p2;
reg   [31:0] sub_ln944_reg_2422;
wire   [19:0] trunc_ln944_fu_1181_p1;
reg   [19:0] trunc_ln944_reg_2429;
wire   [4:0] trunc_ln947_fu_1185_p1;
reg   [4:0] trunc_ln947_reg_2434;
wire   [7:0] trunc_ln943_fu_1189_p1;
reg   [7:0] trunc_ln943_reg_2439;
reg   [62:0] m_s_reg_2444;
wire    ap_CS_fsm_state20;
reg   [0:0] tmp_15_reg_2449;
wire   [31:0] select_ln935_fu_1418_p3;
reg   [31:0] select_ln935_reg_2454;
wire    ap_CS_fsm_state21;
wire   [63:0] zext_ln110_fu_1431_p1;
reg   [63:0] zext_ln110_reg_2463;
wire    ap_CS_fsm_state22;
wire   [0:0] icmp_ln109_fu_1425_p2;
wire   [0:0] icmp_ln935_1_fu_1436_p2;
reg   [0:0] icmp_ln935_1_reg_2474;
reg   [0:0] p_Result_24_reg_2479;
wire   [19:0] tmp_V_12_fu_1442_p3;
reg   [19:0] tmp_V_12_reg_2484;
reg   [31:0] l_1_fu_1468_p3;
reg   [31:0] l_1_reg_2492;
wire   [7:0] trunc_ln943_1_fu_1476_p1;
reg   [7:0] trunc_ln943_1_reg_2497;
wire   [31:0] or_ln949_2_fu_1587_p3;
reg   [31:0] or_ln949_2_reg_2502;
wire    ap_CS_fsm_state24;
wire   [0:0] icmp_ln958_1_fu_1595_p2;
reg   [0:0] icmp_ln958_1_reg_2507;
wire   [31:0] add_ln958_1_fu_1601_p2;
reg   [31:0] add_ln958_1_reg_2512;
wire   [31:0] sub_ln958_1_fu_1607_p2;
reg   [31:0] sub_ln958_1_reg_2517;
wire   [31:0] bitcast_ln739_1_fu_1717_p1;
wire    ap_CS_fsm_state25;
wire   [0:0] p_Result_27_fu_1722_p3;
reg   [0:0] p_Result_27_reg_2527;
wire   [19:0] tmp_V_13_fu_1730_p3;
reg   [19:0] tmp_V_13_reg_2532;
reg   [31:0] l_2_fu_1756_p3;
reg   [31:0] l_2_reg_2540;
wire   [7:0] trunc_ln943_2_fu_1764_p1;
reg   [7:0] trunc_ln943_2_reg_2545;
wire   [3:0] j_5_fu_1768_p2;
reg   [3:0] j_5_reg_2550;
wire   [0:0] icmp_ln111_fu_1792_p2;
reg   [0:0] icmp_ln111_reg_2555;
wire    ap_CS_fsm_state26;
wire   [0:0] icmp_ln111_1_fu_1798_p2;
reg   [0:0] icmp_ln111_1_reg_2560;
wire   [31:0] or_ln949_4_fu_1911_p3;
reg   [31:0] or_ln949_4_reg_2565;
wire   [0:0] icmp_ln958_2_fu_1919_p2;
reg   [0:0] icmp_ln958_2_reg_2570;
wire   [31:0] add_ln958_2_fu_1925_p2;
reg   [31:0] add_ln958_2_reg_2575;
wire   [31:0] sub_ln958_2_fu_1931_p2;
reg   [31:0] sub_ln958_2_reg_2580;
wire   [31:0] select_ln111_1_fu_2116_p3;
wire    ap_CS_fsm_state27;
wire   [3:0] j_4_fu_2130_p2;
reg   [3:0] j_4_reg_2593;
wire    ap_CS_fsm_state28;
wire   [63:0] zext_ln119_fu_2136_p1;
reg   [63:0] zext_ln119_reg_2598;
wire   [0:0] icmp_ln118_fu_2124_p2;
wire   [31:0] logits_q0;
reg   [31:0] logits_load_reg_2608;
wire    ap_CS_fsm_state29;
wire   [31:0] grp_fu_665_p2;
reg   [31:0] tmp_reg_2613;
wire    ap_CS_fsm_state37;
wire   [31:0] grp_fu_682_p2;
reg   [31:0] e_reg_2618;
wire    ap_CS_fsm_state50;
wire    ap_CS_fsm_state58;
wire   [3:0] j_6_fu_2147_p2;
reg   [3:0] j_6_reg_2632;
wire    ap_CS_fsm_state59;
reg   [3:0] output_addr_1_reg_2637;
wire   [0:0] icmp_ln124_fu_2141_p2;
reg   [31:0] output_load_reg_2642;
wire    ap_CS_fsm_state60;
wire   [31:0] grp_fu_671_p2;
reg   [31:0] tmp_2_reg_2647;
wire    ap_CS_fsm_state76;
reg   [2:0] a1_V_address0;
reg    a1_V_ce0;
reg    a1_V_we0;
wire   [18:0] a1_V_d0;
wire   [18:0] a1_V_q0;
reg   [2:0] a2_V_address0;
reg    a2_V_ce0;
reg    a2_V_we0;
wire   [18:0] a2_V_d0;
wire   [18:0] a2_V_q0;
reg   [2:0] a3_V_address0;
reg    a3_V_ce0;
reg    a3_V_we0;
wire   [18:0] a3_V_d0;
wire   [18:0] a3_V_q0;
reg   [3:0] z4_V_address0;
reg    z4_V_ce0;
reg    z4_V_we0;
reg   [3:0] logits_address0;
reg    logits_ce0;
reg    logits_we0;
reg   [31:0] logits_d0;
reg   [2:0] j_0_reg_453;
reg   [11:0] phi_mul_reg_464;
reg   [19:0] p_Val2_1_reg_476;
reg   [9:0] i_0_i_reg_486;
reg   [3:0] j4_0_reg_497;
reg   [19:0] p_Val2_4_reg_509;
reg   [2:0] i_0_i10_reg_519;
reg   [3:0] j5_0_reg_530;
reg   [19:0] p_Val2_9_reg_542;
reg   [3:0] i_0_i26_reg_552;
reg   [3:0] j6_0_reg_563;
reg   [19:0] p_Val2_14_reg_575;
reg   [3:0] i_0_i42_reg_586;
reg   [31:0] maxv_0_reg_597;
reg   [3:0] j7_0_reg_607;
reg   [31:0] p_0202_reg_619;
reg   [31:0] sum_0_reg_631;
reg   [3:0] j8_0_reg_643;
reg   [3:0] j9_0_reg_654;
wire    ap_CS_fsm_state77;
wire   [63:0] zext_ln1117_3_fu_760_p1;
wire   [63:0] zext_ln69_fu_745_p1;
wire   [63:0] zext_ln1117_5_fu_880_p1;
wire   [63:0] zext_ln69_1_fu_866_p1;
wire   [63:0] zext_ln1117_7_fu_990_p1;
wire   [63:0] zext_ln69_2_fu_976_p1;
wire   [63:0] zext_ln1117_9_fu_1100_p1;
wire   [63:0] zext_ln69_3_fu_1086_p1;
wire   [3:0] logits_addr_1_gep_fu_418_p3;
wire    ap_CS_fsm_state51;
wire   [63:0] zext_ln125_fu_2153_p1;
reg   [31:0] grp_fu_665_p0;
reg   [31:0] grp_fu_665_p1;
wire    ap_CS_fsm_state30;
wire    ap_CS_fsm_state61;
wire    ap_CS_fsm_state38;
reg   [19:0] grp_fu_695_p1;
wire   [11:0] zext_ln1117_2_fu_750_p1;
wire   [11:0] add_ln1117_1_fu_754_p2;
wire   [0:0] tmp_10_fu_769_p3;
wire   [18:0] empty_16_fu_765_p1;
wire  signed [33:0] grp_fu_2158_p3;
wire   [5:0] tmp_7_fu_832_p3;
wire   [6:0] zext_ln1117_fu_828_p1;
wire   [6:0] zext_ln1117_1_fu_840_p1;
wire   [6:0] zext_ln1117_4_fu_871_p1;
wire   [6:0] add_ln1117_2_fu_875_p2;
wire   [0:0] tmp_11_fu_889_p3;
wire   [18:0] empty_19_fu_885_p1;
wire  signed [33:0] grp_fu_2167_p3;
wire   [6:0] tmp_8_fu_948_p3;
wire   [7:0] zext_ln1117_6_fu_981_p1;
wire   [7:0] add_ln1117_3_fu_985_p2;
wire   [0:0] tmp_16_fu_999_p3;
wire   [18:0] empty_22_fu_995_p1;
wire  signed [33:0] grp_fu_2176_p3;
wire   [6:0] tmp_9_fu_1058_p3;
wire   [7:0] zext_ln1117_8_fu_1091_p1;
wire   [7:0] add_ln1117_4_fu_1095_p2;
wire  signed [33:0] grp_fu_2185_p3;
wire   [19:0] tmp_V_fu_1136_p2;
reg   [19:0] p_Result_s_fu_1149_p4;
wire   [31:0] p_Result_22_fu_1159_p3;
reg   [31:0] l_fu_1167_p3;
wire   [31:0] lsb_index_fu_1193_p2;
wire   [30:0] tmp_13_fu_1198_p4;
wire   [4:0] sub_ln947_fu_1214_p2;
wire   [19:0] zext_ln947_fu_1219_p1;
wire   [19:0] lshr_ln947_fu_1223_p2;
wire   [19:0] p_Result_4_fu_1229_p2;
wire   [0:0] icmp_ln947_fu_1208_p2;
wire   [0:0] icmp_ln947_1_fu_1234_p2;
wire   [0:0] tmp_14_fu_1246_p3;
wire   [19:0] add_ln949_fu_1260_p2;
wire   [0:0] p_Result_3_fu_1265_p3;
wire   [0:0] xor_ln949_fu_1254_p2;
wire   [0:0] and_ln949_fu_1272_p2;
wire   [0:0] a_fu_1240_p2;
wire   [0:0] or_ln949_fu_1278_p2;
wire   [31:0] zext_ln957_1_fu_1295_p1;
wire   [31:0] add_ln958_fu_1304_p2;
wire   [31:0] lshr_ln958_fu_1309_p2;
wire   [31:0] sub_ln958_fu_1319_p2;
wire   [63:0] m_fu_1292_p1;
wire   [63:0] zext_ln958_1_fu_1324_p1;
wire   [0:0] icmp_ln958_fu_1298_p2;
wire   [63:0] zext_ln958_fu_1315_p1;
wire   [63:0] shl_ln958_fu_1328_p2;
wire   [31:0] or_ln_fu_1284_p3;
wire   [63:0] m_1_fu_1334_p3;
wire   [63:0] zext_ln961_fu_1342_p1;
wire   [63:0] m_2_fu_1346_p2;
wire   [7:0] select_ln964_fu_1373_p3;
wire   [7:0] sub_ln964_fu_1380_p2;
wire   [7:0] add_ln964_fu_1385_p2;
wire   [63:0] m_26_fu_1370_p1;
wire   [8:0] tmp_s_fu_1391_p3;
wire   [63:0] p_Result_23_fu_1398_p5;
wire   [31:0] trunc_ln738_fu_1410_p1;
wire   [31:0] bitcast_ln739_fu_1414_p1;
wire   [19:0] grp_fu_695_p2;
reg   [19:0] p_Result_10_fu_1450_p4;
wire   [31:0] p_Result_25_fu_1460_p3;
wire   [31:0] sub_ln944_1_fu_1480_p2;
wire   [31:0] lsb_index_1_fu_1489_p2;
wire   [30:0] tmp_18_fu_1495_p4;
wire   [4:0] trunc_ln947_1_fu_1511_p1;
wire   [4:0] sub_ln947_1_fu_1515_p2;
wire   [19:0] zext_ln947_1_fu_1521_p1;
wire   [19:0] lshr_ln947_1_fu_1525_p2;
wire   [19:0] p_Result_12_fu_1531_p2;
wire   [0:0] icmp_ln947_2_fu_1505_p2;
wire   [0:0] icmp_ln947_3_fu_1536_p2;
wire   [0:0] tmp_19_fu_1548_p3;
wire   [19:0] trunc_ln944_1_fu_1485_p1;
wire   [19:0] add_ln949_1_fu_1562_p2;
wire   [0:0] p_Result_13_fu_1568_p3;
wire   [0:0] xor_ln949_1_fu_1556_p2;
wire   [0:0] and_ln949_1_fu_1575_p2;
wire   [0:0] a_1_fu_1542_p2;
wire   [0:0] or_ln949_1_fu_1581_p2;
wire   [31:0] zext_ln957_2_fu_1616_p1;
wire   [31:0] lshr_ln958_1_fu_1619_p2;
wire   [63:0] m_15_fu_1613_p1;
wire   [63:0] zext_ln958_3_fu_1628_p1;
wire   [63:0] zext_ln958_2_fu_1624_p1;
wire   [63:0] shl_ln958_1_fu_1631_p2;
wire   [63:0] m_16_fu_1637_p3;
wire   [63:0] zext_ln961_1_fu_1644_p1;
wire   [63:0] m_17_fu_1647_p2;
wire   [62:0] m_3_fu_1653_p4;
wire   [0:0] tmp_20_fu_1667_p3;
wire   [7:0] select_ln964_1_fu_1675_p3;
wire   [7:0] sub_ln964_1_fu_1683_p2;
wire   [7:0] add_ln964_1_fu_1688_p2;
wire   [63:0] m_27_fu_1663_p1;
wire   [8:0] tmp_4_fu_1694_p3;
wire   [63:0] p_Result_26_fu_1701_p5;
wire   [31:0] trunc_ln738_1_fu_1713_p1;
reg   [19:0] p_Result_16_fu_1738_p4;
wire   [31:0] p_Result_28_fu_1748_p3;
wire   [31:0] bitcast_ln111_fu_1774_p1;
wire   [7:0] tmp_1_fu_1778_p4;
wire   [22:0] trunc_ln111_fu_1788_p1;
wire   [31:0] sub_ln944_2_fu_1804_p2;
wire   [31:0] lsb_index_2_fu_1813_p2;
wire   [30:0] tmp_22_fu_1819_p4;
wire   [4:0] trunc_ln947_2_fu_1835_p1;
wire   [4:0] sub_ln947_2_fu_1839_p2;
wire   [19:0] zext_ln947_2_fu_1845_p1;
wire   [19:0] lshr_ln947_2_fu_1849_p2;
wire   [19:0] p_Result_18_fu_1855_p2;
wire   [0:0] icmp_ln947_4_fu_1829_p2;
wire   [0:0] icmp_ln947_5_fu_1860_p2;
wire   [0:0] tmp_23_fu_1872_p3;
wire   [19:0] trunc_ln944_2_fu_1809_p1;
wire   [19:0] add_ln949_2_fu_1886_p2;
wire   [0:0] p_Result_19_fu_1892_p3;
wire   [0:0] xor_ln949_2_fu_1880_p2;
wire   [0:0] and_ln949_2_fu_1899_p2;
wire   [0:0] a_2_fu_1866_p2;
wire   [0:0] or_ln949_3_fu_1905_p2;
wire   [31:0] bitcast_ln111_1_fu_1937_p1;
wire   [7:0] tmp_3_fu_1941_p4;
wire   [22:0] trunc_ln111_1_fu_1951_p1;
wire   [0:0] icmp_ln111_3_fu_1965_p2;
wire   [0:0] icmp_ln111_2_fu_1959_p2;
wire   [0:0] or_ln111_1_fu_1955_p2;
wire   [0:0] or_ln111_2_fu_1971_p2;
wire   [0:0] and_ln111_fu_1977_p2;
wire   [0:0] grp_fu_676_p2;
wire   [0:0] and_ln111_1_fu_1983_p2;
wire   [0:0] xor_ln111_fu_1989_p2;
wire   [31:0] zext_ln957_3_fu_2011_p1;
wire   [31:0] lshr_ln958_2_fu_2014_p2;
wire   [63:0] m_21_fu_2008_p1;
wire   [63:0] zext_ln958_5_fu_2023_p1;
wire   [63:0] zext_ln958_4_fu_2019_p1;
wire   [63:0] shl_ln958_2_fu_2026_p2;
wire   [63:0] m_22_fu_2032_p3;
wire   [63:0] zext_ln961_2_fu_2039_p1;
wire   [63:0] m_23_fu_2042_p2;
wire   [62:0] m_4_fu_2048_p4;
wire   [0:0] tmp_24_fu_2062_p3;
wire   [7:0] select_ln964_2_fu_2070_p3;
wire   [7:0] sub_ln964_2_fu_2078_p2;
wire   [7:0] add_ln964_2_fu_2083_p2;
wire   [63:0] m_28_fu_2058_p1;
wire   [8:0] tmp_6_fu_2089_p3;
wire   [63:0] p_Result_29_fu_2096_p5;
wire   [31:0] trunc_ln738_2_fu_2108_p1;
wire   [0:0] or_ln111_fu_1995_p2;
wire   [31:0] select_ln111_fu_2000_p3;
wire   [31:0] bitcast_ln739_2_fu_2112_p1;
wire   [33:0] grp_fu_2158_p2;
wire   [18:0] grp_fu_2167_p0;
wire   [33:0] grp_fu_2167_p2;
wire   [18:0] grp_fu_2176_p0;
wire   [33:0] grp_fu_2176_p2;
wire   [18:0] grp_fu_2185_p0;
wire   [33:0] grp_fu_2185_p2;
reg   [1:0] grp_fu_665_opcode;
reg   [76:0] ap_NS_fsm;
wire   [33:0] grp_fu_2167_p00;
wire   [33:0] grp_fu_2176_p00;
wire   [33:0] grp_fu_2185_p00;

// power-on initialization
initial begin
#0 ap_CS_fsm = 77'd1;
end

mlp_B1_V #(
    .DataWidth( 13 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
B1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(B1_V_address0),
    .ce0(B1_V_ce0),
    .q0(B1_V_q0)
);

mlp_W1_V #(
    .DataWidth( 16 ),
    .AddressRange( 3920 ),
    .AddressWidth( 12 ))
W1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W1_V_address0),
    .ce0(W1_V_ce0),
    .q0(W1_V_q0)
);

mlp_B2_V #(
    .DataWidth( 15 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
B2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(B2_V_address0),
    .ce0(B2_V_ce0),
    .q0(B2_V_q0)
);

mlp_W2_V #(
    .DataWidth( 16 ),
    .AddressRange( 40 ),
    .AddressWidth( 6 ))
W2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W2_V_address0),
    .ce0(W2_V_ce0),
    .q0(W2_V_q0)
);

mlp_B3_V #(
    .DataWidth( 15 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
B3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(B3_V_address0),
    .ce0(B3_V_ce0),
    .q0(B3_V_q0)
);

mlp_W3_V #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
W3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W3_V_address0),
    .ce0(W3_V_ce0),
    .q0(W3_V_q0)
);

mlp_B4_V #(
    .DataWidth( 16 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
B4_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(B4_V_address0),
    .ce0(B4_V_ce0),
    .q0(B4_V_q0)
);

mlp_W4_V #(
    .DataWidth( 16 ),
    .AddressRange( 80 ),
    .AddressWidth( 7 ))
W4_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W4_V_address0),
    .ce0(W4_V_ce0),
    .q0(W4_V_q0)
);

mlp_a1_V #(
    .DataWidth( 19 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
a1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(a1_V_address0),
    .ce0(a1_V_ce0),
    .we0(a1_V_we0),
    .d0(a1_V_d0),
    .q0(a1_V_q0)
);

mlp_a2_V #(
    .DataWidth( 19 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
a2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(a2_V_address0),
    .ce0(a2_V_ce0),
    .we0(a2_V_we0),
    .d0(a2_V_d0),
    .q0(a2_V_q0)
);

mlp_a2_V #(
    .DataWidth( 19 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
a3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(a3_V_address0),
    .ce0(a3_V_ce0),
    .we0(a3_V_we0),
    .d0(a3_V_d0),
    .q0(a3_V_q0)
);

mlp_z4_V #(
    .DataWidth( 20 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
z4_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(z4_V_address0),
    .ce0(z4_V_ce0),
    .we0(z4_V_we0),
    .d0(p_Val2_14_reg_575),
    .q0(z4_V_q0)
);

mlp_logits #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
logits_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(logits_address0),
    .ce0(logits_ce0),
    .we0(logits_we0),
    .d0(logits_d0),
    .q0(logits_q0)
);

mlp_faddfsub_32ns_32ns_32_8_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mlp_faddfsub_32ns_32ns_32_8_full_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_665_p0),
    .din1(grp_fu_665_p1),
    .opcode(grp_fu_665_opcode),
    .ce(1'b1),
    .dout(grp_fu_665_p2)
);

mlp_fdiv_32ns_32ns_32_16_1 #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mlp_fdiv_32ns_32ns_32_16_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(output_load_reg_2642),
    .din1(sum_0_reg_631),
    .ce(1'b1),
    .dout(grp_fu_671_p2)
);

mlp_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
mlp_fcmp_32ns_32ns_1_2_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0202_reg_619),
    .din1(maxv_0_reg_597),
    .ce(1'b1),
    .opcode(5'd2),
    .dout(grp_fu_676_p2)
);

mlp_fexp_32ns_32ns_32_13_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 13 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mlp_fexp_32ns_32ns_32_13_full_dsp_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(tmp_reg_2613),
    .ce(1'b1),
    .dout(grp_fu_682_p2)
);

mlp_mac_muladd_20s_16s_34ns_34_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 34 ),
    .dout_WIDTH( 34 ))
mlp_mac_muladd_20s_16s_34ns_34_1_1_U5(
    .din0(input_V_q0),
    .din1(W1_V_q0),
    .din2(grp_fu_2158_p2),
    .dout(grp_fu_2158_p3)
);

mlp_mac_muladd_19ns_16s_34ns_34_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 19 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 34 ),
    .dout_WIDTH( 34 ))
mlp_mac_muladd_19ns_16s_34ns_34_1_1_U6(
    .din0(grp_fu_2167_p0),
    .din1(W2_V_q0),
    .din2(grp_fu_2167_p2),
    .dout(grp_fu_2167_p3)
);

mlp_mac_muladd_19ns_16s_34ns_34_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 19 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 34 ),
    .dout_WIDTH( 34 ))
mlp_mac_muladd_19ns_16s_34ns_34_1_1_U7(
    .din0(grp_fu_2176_p0),
    .din1(W3_V_q0),
    .din2(grp_fu_2176_p2),
    .dout(grp_fu_2176_p3)
);

mlp_mac_muladd_19ns_16s_34ns_34_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 19 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 34 ),
    .dout_WIDTH( 34 ))
mlp_mac_muladd_19ns_16s_34ns_34_1_1_U8(
    .din0(grp_fu_2185_p0),
    .din1(W4_V_q0),
    .din2(grp_fu_2185_p2),
    .dout(grp_fu_2185_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        i_0_i10_reg_519 <= i_1_reg_2276;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        i_0_i10_reg_519 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        i_0_i26_reg_552 <= i_2_reg_2327;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        i_0_i26_reg_552 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        i_0_i42_reg_586 <= i_3_reg_2383;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        i_0_i42_reg_586 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i_0_i_reg_486 <= i_reg_2225;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        i_0_i_reg_486 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln88_fu_712_p2 == 1'd1))) begin
        j4_0_reg_497 <= 4'd0;
    end else if (((icmp_ln68_1_fu_854_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        j4_0_reg_497 <= j_1_reg_2248;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln93_fu_811_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        j5_0_reg_530 <= 4'd0;
    end else if (((icmp_ln68_2_fu_964_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
        j5_0_reg_530 <= j_2_reg_2299;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln98_fu_931_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        j6_0_reg_563 <= 4'd0;
    end else if (((icmp_ln68_3_fu_1074_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        j6_0_reg_563 <= j_3_reg_2350;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        j7_0_reg_607 <= 4'd1;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        j7_0_reg_607 <= j_5_reg_2550;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state58)) begin
        j8_0_reg_643 <= j_4_reg_2593;
    end else if (((icmp_ln109_fu_1425_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
        j8_0_reg_643 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln118_fu_2124_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state28))) begin
        j9_0_reg_654 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state77)) begin
        j9_0_reg_654 <= j_6_reg_2632;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        j_0_reg_453 <= 3'd0;
    end else if (((icmp_ln68_fu_733_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        j_0_reg_453 <= j_reg_2202;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        maxv_0_reg_597 <= select_ln935_fu_1418_p3;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        maxv_0_reg_597 <= select_ln111_1_fu_2116_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln935_1_fu_1436_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state23))) begin
        p_0202_reg_619 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state25) & (icmp_ln935_1_reg_2474 == 1'd0))) begin
        p_0202_reg_619 <= bitcast_ln739_1_fu_1717_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        p_Val2_14_reg_575 <= {{grp_fu_2185_p3[33:14]}};
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        p_Val2_14_reg_575 <= sext_ln104_fu_1070_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_Val2_1_reg_476 <= {{grp_fu_2158_p3[33:14]}};
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        p_Val2_1_reg_476 <= zext_ln89_1_fu_729_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        p_Val2_4_reg_509 <= {{grp_fu_2167_p3[33:14]}};
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        p_Val2_4_reg_509 <= sext_ln94_fu_850_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        p_Val2_9_reg_542 <= {{grp_fu_2176_p3[33:14]}};
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        p_Val2_9_reg_542 <= sext_ln99_fu_960_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_mul_reg_464 <= 12'd0;
    end else if (((icmp_ln68_fu_733_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        phi_mul_reg_464 <= add_ln88_reg_2194;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state58)) begin
        sum_0_reg_631 <= grp_fu_665_p2;
    end else if (((icmp_ln109_fu_1425_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
        sum_0_reg_631 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln1117_reg_2263 <= add_ln1117_fu_844_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln88_reg_2194 <= add_ln88_fu_706_p2;
        j_reg_2202 <= j_fu_718_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        add_ln958_1_reg_2512 <= add_ln958_1_fu_1601_p2;
        icmp_ln958_1_reg_2507 <= icmp_ln958_1_fu_1595_p2;
        or_ln949_2_reg_2502[0] <= or_ln949_2_fu_1587_p3[0];
        sub_ln958_1_reg_2517 <= sub_ln958_1_fu_1607_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        add_ln958_2_reg_2575 <= add_ln958_2_fu_1925_p2;
        icmp_ln111_1_reg_2560 <= icmp_ln111_1_fu_1798_p2;
        icmp_ln111_reg_2555 <= icmp_ln111_fu_1792_p2;
        icmp_ln958_2_reg_2570 <= icmp_ln958_2_fu_1919_p2;
        or_ln949_4_reg_2565[0] <= or_ln949_4_fu_1911_p3[0];
        sub_ln958_2_reg_2580 <= sub_ln958_2_fu_1931_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state50)) begin
        e_reg_2618 <= grp_fu_682_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        i_1_reg_2276 <= i_1_fu_860_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        i_2_reg_2327 <= i_2_fu_970_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        i_3_reg_2383 <= i_3_fu_1080_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        i_reg_2225 <= i_fu_739_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        icmp_ln935_1_reg_2474 <= icmp_ln935_1_fu_1436_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        icmp_ln935_reg_2409 <= icmp_ln935_fu_1130_p2;
        sub_ln944_reg_2422 <= sub_ln944_fu_1175_p2;
        tmp_V_10_reg_2414 <= tmp_V_10_fu_1142_p3;
        trunc_ln943_reg_2439 <= trunc_ln943_fu_1189_p1;
        trunc_ln944_reg_2429 <= trunc_ln944_fu_1181_p1;
        trunc_ln947_reg_2434 <= trunc_ln947_fu_1185_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        j_1_reg_2248 <= j_1_fu_817_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        j_2_reg_2299 <= j_2_fu_937_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        j_3_reg_2350 <= j_3_fu_1047_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        j_4_reg_2593 <= j_4_fu_2130_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        j_5_reg_2550 <= j_5_fu_1768_p2;
        l_2_reg_2540 <= l_2_fu_1756_p3;
        p_Result_27_reg_2527 <= reg_701[32'd19];
        tmp_V_13_reg_2532 <= tmp_V_13_fu_1730_p3;
        trunc_ln943_2_reg_2545 <= trunc_ln943_2_fu_1764_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state59)) begin
        j_6_reg_2632 <= j_6_fu_2147_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state23) & (icmp_ln935_1_fu_1436_p2 == 1'd0))) begin
        l_1_reg_2492 <= l_1_fu_1468_p3;
        p_Result_24_reg_2479 <= z4_V_q0[32'd19];
        tmp_V_12_reg_2484 <= tmp_V_12_fu_1442_p3;
        trunc_ln943_1_reg_2497 <= trunc_ln943_1_fu_1476_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        logits_load_reg_2608 <= logits_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state20) & (icmp_ln935_reg_2409 == 1'd0))) begin
        m_s_reg_2444 <= {{m_2_fu_1346_p2[63:1]}};
        tmp_15_reg_2449 <= m_2_fu_1346_p2[32'd25];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state59) & (icmp_ln124_fu_2141_p2 == 1'd0))) begin
        output_addr_1_reg_2637 <= zext_ln125_fu_2153_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state60)) begin
        output_load_reg_2642 <= output_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        p_Result_21_reg_2403 <= z4_V_q0[32'd19];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state18))) begin
        reg_701 <= z4_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        select_ln935_reg_2454 <= select_ln935_fu_1418_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state76)) begin
        tmp_2_reg_2647 <= grp_fu_671_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        tmp_reg_2613 <= grp_fu_665_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        zext_ln104_1_reg_2370[6 : 3] <= zext_ln104_1_fu_1066_p1[6 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & (icmp_ln103_fu_1041_p2 == 1'd0))) begin
        zext_ln104_reg_2355[3 : 0] <= zext_ln104_fu_1053_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state22) & (icmp_ln109_fu_1425_p2 == 1'd0))) begin
        zext_ln110_reg_2463[3 : 0] <= zext_ln110_fu_1431_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state28) & (icmp_ln118_fu_2124_p2 == 1'd0))) begin
        zext_ln119_reg_2598[3 : 0] <= zext_ln119_fu_2136_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln88_fu_712_p2 == 1'd0))) begin
        zext_ln89_reg_2207[2 : 0] <= zext_ln89_fu_724_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln93_fu_811_p2 == 1'd0))) begin
        zext_ln94_reg_2253[3 : 0] <= zext_ln94_fu_823_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        zext_ln99_1_reg_2314[6 : 3] <= zext_ln99_1_fu_956_p1[6 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln98_fu_931_p2 == 1'd0))) begin
        zext_ln99_reg_2304[3 : 0] <= zext_ln99_fu_943_p1[3 : 0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        B1_V_ce0 = 1'b1;
    end else begin
        B1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B2_V_ce0 = 1'b1;
    end else begin
        B2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        B3_V_ce0 = 1'b1;
    end else begin
        B3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        B4_V_ce0 = 1'b1;
    end else begin
        B4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        W1_V_ce0 = 1'b1;
    end else begin
        W1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        W2_V_ce0 = 1'b1;
    end else begin
        W2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        W3_V_ce0 = 1'b1;
    end else begin
        W3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        W4_V_ce0 = 1'b1;
    end else begin
        W4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        a1_V_address0 = zext_ln69_1_fu_866_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        a1_V_address0 = zext_ln89_reg_2207;
    end else begin
        a1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state4))) begin
        a1_V_ce0 = 1'b1;
    end else begin
        a1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln68_fu_733_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        a1_V_we0 = 1'b1;
    end else begin
        a1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        a2_V_address0 = zext_ln69_2_fu_976_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        a2_V_address0 = zext_ln94_reg_2253;
    end else begin
        a2_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state8))) begin
        a2_V_ce0 = 1'b1;
    end else begin
        a2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln68_1_fu_854_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        a2_V_we0 = 1'b1;
    end else begin
        a2_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        a3_V_address0 = zext_ln69_3_fu_1086_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        a3_V_address0 = zext_ln99_reg_2304;
    end else begin
        a3_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state12))) begin
        a3_V_ce0 = 1'b1;
    end else begin
        a3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln68_2_fu_964_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
        a3_V_we0 = 1'b1;
    end else begin
        a3_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln124_fu_2141_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state59))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln124_fu_2141_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state59))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_665_opcode = 2'd1;
    end else if ((1'b1 == ap_CS_fsm_state51)) begin
        grp_fu_665_opcode = 2'd0;
    end else begin
        grp_fu_665_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state51)) begin
        grp_fu_665_p0 = sum_0_reg_631;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_665_p0 = logits_load_reg_2608;
    end else begin
        grp_fu_665_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state51)) begin
        grp_fu_665_p1 = e_reg_2618;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_665_p1 = maxv_0_reg_597;
    end else begin
        grp_fu_665_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_695_p1 = reg_701;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        grp_fu_695_p1 = z4_V_q0;
    end else begin
        grp_fu_695_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_V_ce0 = 1'b1;
    end else begin
        input_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        logits_address0 = zext_ln119_fu_2136_p1;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        logits_address0 = logits_addr_1_gep_fu_418_p3;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        logits_address0 = zext_ln110_reg_2463;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        logits_address0 = 64'd0;
    end else begin
        logits_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state23))) begin
        logits_ce0 = 1'b1;
    end else begin
        logits_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        logits_d0 = bitcast_ln739_1_fu_1717_p1;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        logits_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        logits_d0 = select_ln935_reg_2454;
    end else begin
        logits_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state25) & (icmp_ln935_1_reg_2474 == 1'd0)) | ((icmp_ln109_fu_1425_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22)) | ((icmp_ln935_1_fu_1436_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state23)))) begin
        logits_we0 = 1'b1;
    end else begin
        logits_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state77)) begin
        output_r_address0 = output_addr_1_reg_2637;
    end else if ((1'b1 == ap_CS_fsm_state59)) begin
        output_r_address0 = zext_ln125_fu_2153_p1;
    end else if ((1'b1 == ap_CS_fsm_state51)) begin
        output_r_address0 = zext_ln119_reg_2598;
    end else begin
        output_r_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state59))) begin
        output_r_ce0 = 1'b1;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state77)) begin
        output_r_d0 = tmp_2_reg_2647;
    end else if ((1'b1 == ap_CS_fsm_state51)) begin
        output_r_d0 = e_reg_2618;
    end else begin
        output_r_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state77))) begin
        output_r_we0 = 1'b1;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        z4_V_address0 = zext_ln110_fu_1431_p1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        z4_V_address0 = zext_ln104_reg_2355;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        z4_V_address0 = 64'd0;
    end else begin
        z4_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state14))) begin
        z4_V_ce0 = 1'b1;
    end else begin
        z4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln68_3_fu_1074_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        z4_V_we0 = 1'b1;
    end else begin
        z4_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln88_fu_712_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln68_fu_733_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state6 : begin
            if (((icmp_ln93_fu_811_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((icmp_ln68_1_fu_854_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state10 : begin
            if (((icmp_ln98_fu_931_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((icmp_ln68_2_fu_964_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state14 : begin
            if (((icmp_ln103_fu_1041_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((icmp_ln68_3_fu_1074_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            if (((icmp_ln109_fu_1425_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state23 : begin
            if (((icmp_ln935_1_fu_1436_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state28 : begin
            if (((icmp_ln118_fu_2124_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state28))) begin
                ap_NS_fsm = ap_ST_fsm_state59;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state59 : begin
            if (((icmp_ln124_fu_2141_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state59))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state60;
            end
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B1_V_address0 = zext_ln89_fu_724_p1;

assign B2_V_address0 = zext_ln94_fu_823_p1;

assign B3_V_address0 = zext_ln99_fu_943_p1;

assign B4_V_address0 = zext_ln104_fu_1053_p1;

assign W1_V_address0 = zext_ln1117_3_fu_760_p1;

assign W2_V_address0 = zext_ln1117_5_fu_880_p1;

assign W3_V_address0 = zext_ln1117_7_fu_990_p1;

assign W4_V_address0 = zext_ln1117_9_fu_1100_p1;

assign a1_V_d0 = ((tmp_10_fu_769_p3[0:0] === 1'b1) ? 19'd0 : empty_16_fu_765_p1);

assign a2_V_d0 = ((tmp_11_fu_889_p3[0:0] === 1'b1) ? 19'd0 : empty_19_fu_885_p1);

assign a3_V_d0 = ((tmp_16_fu_999_p3[0:0] === 1'b1) ? 19'd0 : empty_22_fu_995_p1);

assign a_1_fu_1542_p2 = (icmp_ln947_3_fu_1536_p2 & icmp_ln947_2_fu_1505_p2);

assign a_2_fu_1866_p2 = (icmp_ln947_5_fu_1860_p2 & icmp_ln947_4_fu_1829_p2);

assign a_fu_1240_p2 = (icmp_ln947_fu_1208_p2 & icmp_ln947_1_fu_1234_p2);

assign add_ln1117_1_fu_754_p2 = (zext_ln1117_2_fu_750_p1 + phi_mul_reg_464);

assign add_ln1117_2_fu_875_p2 = (zext_ln1117_4_fu_871_p1 + add_ln1117_reg_2263);

assign add_ln1117_3_fu_985_p2 = (zext_ln1117_6_fu_981_p1 + zext_ln99_1_reg_2314);

assign add_ln1117_4_fu_1095_p2 = (zext_ln1117_8_fu_1091_p1 + zext_ln104_1_reg_2370);

assign add_ln1117_fu_844_p2 = (zext_ln1117_fu_828_p1 + zext_ln1117_1_fu_840_p1);

assign add_ln88_fu_706_p2 = (phi_mul_reg_464 + 12'd784);

assign add_ln949_1_fu_1562_p2 = ($signed(20'd1048552) + $signed(trunc_ln944_1_fu_1485_p1));

assign add_ln949_2_fu_1886_p2 = ($signed(20'd1048552) + $signed(trunc_ln944_2_fu_1809_p1));

assign add_ln949_fu_1260_p2 = ($signed(20'd1048552) + $signed(trunc_ln944_reg_2429));

assign add_ln958_1_fu_1601_p2 = ($signed(32'd4294967271) + $signed(sub_ln944_1_fu_1480_p2));

assign add_ln958_2_fu_1925_p2 = ($signed(32'd4294967271) + $signed(sub_ln944_2_fu_1804_p2));

assign add_ln958_fu_1304_p2 = ($signed(32'd4294967271) + $signed(sub_ln944_reg_2422));

assign add_ln964_1_fu_1688_p2 = (select_ln964_1_fu_1675_p3 + sub_ln964_1_fu_1683_p2);

assign add_ln964_2_fu_2083_p2 = (select_ln964_2_fu_2070_p3 + sub_ln964_2_fu_2078_p2);

assign add_ln964_fu_1385_p2 = (select_ln964_fu_1373_p3 + sub_ln964_fu_1380_p2);

assign and_ln111_1_fu_1983_p2 = (grp_fu_676_p2 & and_ln111_fu_1977_p2);

assign and_ln111_fu_1977_p2 = (or_ln111_2_fu_1971_p2 & or_ln111_1_fu_1955_p2);

assign and_ln949_1_fu_1575_p2 = (xor_ln949_1_fu_1556_p2 & p_Result_13_fu_1568_p3);

assign and_ln949_2_fu_1899_p2 = (xor_ln949_2_fu_1880_p2 & p_Result_19_fu_1892_p3);

assign and_ln949_fu_1272_p2 = (xor_ln949_fu_1254_p2 & p_Result_3_fu_1265_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state50 = ap_CS_fsm[32'd49];

assign ap_CS_fsm_state51 = ap_CS_fsm[32'd50];

assign ap_CS_fsm_state58 = ap_CS_fsm[32'd57];

assign ap_CS_fsm_state59 = ap_CS_fsm[32'd58];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state60 = ap_CS_fsm[32'd59];

assign ap_CS_fsm_state61 = ap_CS_fsm[32'd60];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state76 = ap_CS_fsm[32'd75];

assign ap_CS_fsm_state77 = ap_CS_fsm[32'd76];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign bitcast_ln111_1_fu_1937_p1 = maxv_0_reg_597;

assign bitcast_ln111_fu_1774_p1 = p_0202_reg_619;

assign bitcast_ln739_1_fu_1717_p1 = trunc_ln738_1_fu_1713_p1;

assign bitcast_ln739_2_fu_2112_p1 = trunc_ln738_2_fu_2108_p1;

assign bitcast_ln739_fu_1414_p1 = trunc_ln738_fu_1410_p1;

assign empty_16_fu_765_p1 = p_Val2_1_reg_476[18:0];

assign empty_19_fu_885_p1 = p_Val2_4_reg_509[18:0];

assign empty_22_fu_995_p1 = p_Val2_9_reg_542[18:0];

assign grp_fu_2158_p2 = {{p_Val2_1_reg_476}, {14'd0}};

assign grp_fu_2167_p0 = grp_fu_2167_p00;

assign grp_fu_2167_p00 = a1_V_q0;

assign grp_fu_2167_p2 = {{p_Val2_4_reg_509}, {14'd0}};

assign grp_fu_2176_p0 = grp_fu_2176_p00;

assign grp_fu_2176_p00 = a2_V_q0;

assign grp_fu_2176_p2 = {{p_Val2_9_reg_542}, {14'd0}};

assign grp_fu_2185_p0 = grp_fu_2185_p00;

assign grp_fu_2185_p00 = a3_V_q0;

assign grp_fu_2185_p2 = {{p_Val2_14_reg_575}, {14'd0}};

assign grp_fu_687_p3 = z4_V_q0[32'd19];

assign grp_fu_695_p2 = (20'd0 - grp_fu_695_p1);

assign i_1_fu_860_p2 = (i_0_i10_reg_519 + 3'd1);

assign i_2_fu_970_p2 = (i_0_i26_reg_552 + 4'd1);

assign i_3_fu_1080_p2 = (i_0_i42_reg_586 + 4'd1);

assign i_fu_739_p2 = (i_0_i_reg_486 + 10'd1);

assign icmp_ln103_fu_1041_p2 = ((j6_0_reg_563 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln109_fu_1425_p2 = ((j7_0_reg_607 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln111_1_fu_1798_p2 = ((trunc_ln111_fu_1788_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln111_2_fu_1959_p2 = ((tmp_3_fu_1941_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln111_3_fu_1965_p2 = ((trunc_ln111_1_fu_1951_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln111_fu_1792_p2 = ((tmp_1_fu_1778_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln118_fu_2124_p2 = ((j8_0_reg_643 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln124_fu_2141_p2 = ((j9_0_reg_654 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln68_1_fu_854_p2 = ((i_0_i10_reg_519 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln68_2_fu_964_p2 = ((i_0_i26_reg_552 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln68_3_fu_1074_p2 = ((i_0_i42_reg_586 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln68_fu_733_p2 = ((i_0_i_reg_486 == 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln88_fu_712_p2 = ((j_0_reg_453 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln935_1_fu_1436_p2 = ((z4_V_q0 == 20'd0) ? 1'b1 : 1'b0);

assign icmp_ln935_fu_1130_p2 = ((reg_701 == 20'd0) ? 1'b1 : 1'b0);

assign icmp_ln93_fu_811_p2 = ((j4_0_reg_497 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln947_1_fu_1234_p2 = ((p_Result_4_fu_1229_p2 != 20'd0) ? 1'b1 : 1'b0);

assign icmp_ln947_2_fu_1505_p2 = (($signed(tmp_18_fu_1495_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln947_3_fu_1536_p2 = ((p_Result_12_fu_1531_p2 != 20'd0) ? 1'b1 : 1'b0);

assign icmp_ln947_4_fu_1829_p2 = (($signed(tmp_22_fu_1819_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln947_5_fu_1860_p2 = ((p_Result_18_fu_1855_p2 != 20'd0) ? 1'b1 : 1'b0);

assign icmp_ln947_fu_1208_p2 = (($signed(tmp_13_fu_1198_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln958_1_fu_1595_p2 = (($signed(lsb_index_1_fu_1489_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln958_2_fu_1919_p2 = (($signed(lsb_index_2_fu_1813_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln958_fu_1298_p2 = (($signed(lsb_index_fu_1193_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln98_fu_931_p2 = ((j5_0_reg_530 == 4'd8) ? 1'b1 : 1'b0);

assign input_V_address0 = zext_ln69_fu_745_p1;

assign j_1_fu_817_p2 = (j4_0_reg_497 + 4'd1);

assign j_2_fu_937_p2 = (j5_0_reg_530 + 4'd1);

assign j_3_fu_1047_p2 = (j6_0_reg_563 + 4'd1);

assign j_4_fu_2130_p2 = (j8_0_reg_643 + 4'd1);

assign j_5_fu_1768_p2 = (4'd1 + j7_0_reg_607);

assign j_6_fu_2147_p2 = (j9_0_reg_654 + 4'd1);

assign j_fu_718_p2 = (j_0_reg_453 + 3'd1);


always @ (p_Result_25_fu_1460_p3) begin
    if (p_Result_25_fu_1460_p3[0] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd0;
    end else if (p_Result_25_fu_1460_p3[1] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd1;
    end else if (p_Result_25_fu_1460_p3[2] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd2;
    end else if (p_Result_25_fu_1460_p3[3] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd3;
    end else if (p_Result_25_fu_1460_p3[4] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd4;
    end else if (p_Result_25_fu_1460_p3[5] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd5;
    end else if (p_Result_25_fu_1460_p3[6] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd6;
    end else if (p_Result_25_fu_1460_p3[7] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd7;
    end else if (p_Result_25_fu_1460_p3[8] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd8;
    end else if (p_Result_25_fu_1460_p3[9] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd9;
    end else if (p_Result_25_fu_1460_p3[10] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd10;
    end else if (p_Result_25_fu_1460_p3[11] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd11;
    end else if (p_Result_25_fu_1460_p3[12] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd12;
    end else if (p_Result_25_fu_1460_p3[13] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd13;
    end else if (p_Result_25_fu_1460_p3[14] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd14;
    end else if (p_Result_25_fu_1460_p3[15] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd15;
    end else if (p_Result_25_fu_1460_p3[16] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd16;
    end else if (p_Result_25_fu_1460_p3[17] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd17;
    end else if (p_Result_25_fu_1460_p3[18] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd18;
    end else if (p_Result_25_fu_1460_p3[19] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd19;
    end else if (p_Result_25_fu_1460_p3[20] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd20;
    end else if (p_Result_25_fu_1460_p3[21] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd21;
    end else if (p_Result_25_fu_1460_p3[22] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd22;
    end else if (p_Result_25_fu_1460_p3[23] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd23;
    end else if (p_Result_25_fu_1460_p3[24] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd24;
    end else if (p_Result_25_fu_1460_p3[25] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd25;
    end else if (p_Result_25_fu_1460_p3[26] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd26;
    end else if (p_Result_25_fu_1460_p3[27] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd27;
    end else if (p_Result_25_fu_1460_p3[28] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd28;
    end else if (p_Result_25_fu_1460_p3[29] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd29;
    end else if (p_Result_25_fu_1460_p3[30] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd30;
    end else if (p_Result_25_fu_1460_p3[31] == 1'b1) begin
        l_1_fu_1468_p3 = 32'd31;
    end else begin
        l_1_fu_1468_p3 = 32'd32;
    end
end


always @ (p_Result_28_fu_1748_p3) begin
    if (p_Result_28_fu_1748_p3[0] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd0;
    end else if (p_Result_28_fu_1748_p3[1] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd1;
    end else if (p_Result_28_fu_1748_p3[2] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd2;
    end else if (p_Result_28_fu_1748_p3[3] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd3;
    end else if (p_Result_28_fu_1748_p3[4] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd4;
    end else if (p_Result_28_fu_1748_p3[5] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd5;
    end else if (p_Result_28_fu_1748_p3[6] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd6;
    end else if (p_Result_28_fu_1748_p3[7] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd7;
    end else if (p_Result_28_fu_1748_p3[8] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd8;
    end else if (p_Result_28_fu_1748_p3[9] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd9;
    end else if (p_Result_28_fu_1748_p3[10] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd10;
    end else if (p_Result_28_fu_1748_p3[11] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd11;
    end else if (p_Result_28_fu_1748_p3[12] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd12;
    end else if (p_Result_28_fu_1748_p3[13] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd13;
    end else if (p_Result_28_fu_1748_p3[14] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd14;
    end else if (p_Result_28_fu_1748_p3[15] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd15;
    end else if (p_Result_28_fu_1748_p3[16] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd16;
    end else if (p_Result_28_fu_1748_p3[17] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd17;
    end else if (p_Result_28_fu_1748_p3[18] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd18;
    end else if (p_Result_28_fu_1748_p3[19] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd19;
    end else if (p_Result_28_fu_1748_p3[20] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd20;
    end else if (p_Result_28_fu_1748_p3[21] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd21;
    end else if (p_Result_28_fu_1748_p3[22] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd22;
    end else if (p_Result_28_fu_1748_p3[23] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd23;
    end else if (p_Result_28_fu_1748_p3[24] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd24;
    end else if (p_Result_28_fu_1748_p3[25] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd25;
    end else if (p_Result_28_fu_1748_p3[26] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd26;
    end else if (p_Result_28_fu_1748_p3[27] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd27;
    end else if (p_Result_28_fu_1748_p3[28] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd28;
    end else if (p_Result_28_fu_1748_p3[29] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd29;
    end else if (p_Result_28_fu_1748_p3[30] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd30;
    end else if (p_Result_28_fu_1748_p3[31] == 1'b1) begin
        l_2_fu_1756_p3 = 32'd31;
    end else begin
        l_2_fu_1756_p3 = 32'd32;
    end
end


always @ (p_Result_22_fu_1159_p3) begin
    if (p_Result_22_fu_1159_p3[0] == 1'b1) begin
        l_fu_1167_p3 = 32'd0;
    end else if (p_Result_22_fu_1159_p3[1] == 1'b1) begin
        l_fu_1167_p3 = 32'd1;
    end else if (p_Result_22_fu_1159_p3[2] == 1'b1) begin
        l_fu_1167_p3 = 32'd2;
    end else if (p_Result_22_fu_1159_p3[3] == 1'b1) begin
        l_fu_1167_p3 = 32'd3;
    end else if (p_Result_22_fu_1159_p3[4] == 1'b1) begin
        l_fu_1167_p3 = 32'd4;
    end else if (p_Result_22_fu_1159_p3[5] == 1'b1) begin
        l_fu_1167_p3 = 32'd5;
    end else if (p_Result_22_fu_1159_p3[6] == 1'b1) begin
        l_fu_1167_p3 = 32'd6;
    end else if (p_Result_22_fu_1159_p3[7] == 1'b1) begin
        l_fu_1167_p3 = 32'd7;
    end else if (p_Result_22_fu_1159_p3[8] == 1'b1) begin
        l_fu_1167_p3 = 32'd8;
    end else if (p_Result_22_fu_1159_p3[9] == 1'b1) begin
        l_fu_1167_p3 = 32'd9;
    end else if (p_Result_22_fu_1159_p3[10] == 1'b1) begin
        l_fu_1167_p3 = 32'd10;
    end else if (p_Result_22_fu_1159_p3[11] == 1'b1) begin
        l_fu_1167_p3 = 32'd11;
    end else if (p_Result_22_fu_1159_p3[12] == 1'b1) begin
        l_fu_1167_p3 = 32'd12;
    end else if (p_Result_22_fu_1159_p3[13] == 1'b1) begin
        l_fu_1167_p3 = 32'd13;
    end else if (p_Result_22_fu_1159_p3[14] == 1'b1) begin
        l_fu_1167_p3 = 32'd14;
    end else if (p_Result_22_fu_1159_p3[15] == 1'b1) begin
        l_fu_1167_p3 = 32'd15;
    end else if (p_Result_22_fu_1159_p3[16] == 1'b1) begin
        l_fu_1167_p3 = 32'd16;
    end else if (p_Result_22_fu_1159_p3[17] == 1'b1) begin
        l_fu_1167_p3 = 32'd17;
    end else if (p_Result_22_fu_1159_p3[18] == 1'b1) begin
        l_fu_1167_p3 = 32'd18;
    end else if (p_Result_22_fu_1159_p3[19] == 1'b1) begin
        l_fu_1167_p3 = 32'd19;
    end else if (p_Result_22_fu_1159_p3[20] == 1'b1) begin
        l_fu_1167_p3 = 32'd20;
    end else if (p_Result_22_fu_1159_p3[21] == 1'b1) begin
        l_fu_1167_p3 = 32'd21;
    end else if (p_Result_22_fu_1159_p3[22] == 1'b1) begin
        l_fu_1167_p3 = 32'd22;
    end else if (p_Result_22_fu_1159_p3[23] == 1'b1) begin
        l_fu_1167_p3 = 32'd23;
    end else if (p_Result_22_fu_1159_p3[24] == 1'b1) begin
        l_fu_1167_p3 = 32'd24;
    end else if (p_Result_22_fu_1159_p3[25] == 1'b1) begin
        l_fu_1167_p3 = 32'd25;
    end else if (p_Result_22_fu_1159_p3[26] == 1'b1) begin
        l_fu_1167_p3 = 32'd26;
    end else if (p_Result_22_fu_1159_p3[27] == 1'b1) begin
        l_fu_1167_p3 = 32'd27;
    end else if (p_Result_22_fu_1159_p3[28] == 1'b1) begin
        l_fu_1167_p3 = 32'd28;
    end else if (p_Result_22_fu_1159_p3[29] == 1'b1) begin
        l_fu_1167_p3 = 32'd29;
    end else if (p_Result_22_fu_1159_p3[30] == 1'b1) begin
        l_fu_1167_p3 = 32'd30;
    end else if (p_Result_22_fu_1159_p3[31] == 1'b1) begin
        l_fu_1167_p3 = 32'd31;
    end else begin
        l_fu_1167_p3 = 32'd32;
    end
end

assign logits_addr_1_gep_fu_418_p3 = zext_ln110_reg_2463;

assign lsb_index_1_fu_1489_p2 = ($signed(32'd4294967272) + $signed(sub_ln944_1_fu_1480_p2));

assign lsb_index_2_fu_1813_p2 = ($signed(32'd4294967272) + $signed(sub_ln944_2_fu_1804_p2));

assign lsb_index_fu_1193_p2 = ($signed(32'd4294967272) + $signed(sub_ln944_reg_2422));

assign lshr_ln947_1_fu_1525_p2 = 20'd1048575 >> zext_ln947_1_fu_1521_p1;

assign lshr_ln947_2_fu_1849_p2 = 20'd1048575 >> zext_ln947_2_fu_1845_p1;

assign lshr_ln947_fu_1223_p2 = 20'd1048575 >> zext_ln947_fu_1219_p1;

assign lshr_ln958_1_fu_1619_p2 = zext_ln957_2_fu_1616_p1 >> add_ln958_1_reg_2512;

assign lshr_ln958_2_fu_2014_p2 = zext_ln957_3_fu_2011_p1 >> add_ln958_2_reg_2575;

assign lshr_ln958_fu_1309_p2 = zext_ln957_1_fu_1295_p1 >> add_ln958_fu_1304_p2;

assign m_15_fu_1613_p1 = tmp_V_12_reg_2484;

assign m_16_fu_1637_p3 = ((icmp_ln958_1_reg_2507[0:0] === 1'b1) ? zext_ln958_2_fu_1624_p1 : shl_ln958_1_fu_1631_p2);

assign m_17_fu_1647_p2 = (m_16_fu_1637_p3 + zext_ln961_1_fu_1644_p1);

assign m_1_fu_1334_p3 = ((icmp_ln958_fu_1298_p2[0:0] === 1'b1) ? zext_ln958_fu_1315_p1 : shl_ln958_fu_1328_p2);

assign m_21_fu_2008_p1 = tmp_V_13_reg_2532;

assign m_22_fu_2032_p3 = ((icmp_ln958_2_reg_2570[0:0] === 1'b1) ? zext_ln958_4_fu_2019_p1 : shl_ln958_2_fu_2026_p2);

assign m_23_fu_2042_p2 = (m_22_fu_2032_p3 + zext_ln961_2_fu_2039_p1);

assign m_26_fu_1370_p1 = m_s_reg_2444;

assign m_27_fu_1663_p1 = m_3_fu_1653_p4;

assign m_28_fu_2058_p1 = m_4_fu_2048_p4;

assign m_2_fu_1346_p2 = (m_1_fu_1334_p3 + zext_ln961_fu_1342_p1);

assign m_3_fu_1653_p4 = {{m_17_fu_1647_p2[63:1]}};

assign m_4_fu_2048_p4 = {{m_23_fu_2042_p2[63:1]}};

assign m_fu_1292_p1 = tmp_V_10_reg_2414;

assign or_ln111_1_fu_1955_p2 = (icmp_ln111_reg_2555 | icmp_ln111_1_reg_2560);

assign or_ln111_2_fu_1971_p2 = (icmp_ln111_3_fu_1965_p2 | icmp_ln111_2_fu_1959_p2);

assign or_ln111_fu_1995_p2 = (xor_ln111_fu_1989_p2 | icmp_ln935_1_reg_2474);

assign or_ln949_1_fu_1581_p2 = (and_ln949_1_fu_1575_p2 | a_1_fu_1542_p2);

assign or_ln949_2_fu_1587_p3 = {{31'd0}, {or_ln949_1_fu_1581_p2}};

assign or_ln949_3_fu_1905_p2 = (and_ln949_2_fu_1899_p2 | a_2_fu_1866_p2);

assign or_ln949_4_fu_1911_p3 = {{31'd0}, {or_ln949_3_fu_1905_p2}};

assign or_ln949_fu_1278_p2 = (and_ln949_fu_1272_p2 | a_fu_1240_p2);

assign or_ln_fu_1284_p3 = {{31'd0}, {or_ln949_fu_1278_p2}};

integer ap_tvar_int_0;

always @ (tmp_V_12_fu_1442_p3) begin
    for (ap_tvar_int_0 = 20 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 19 - 0) begin
            p_Result_10_fu_1450_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_10_fu_1450_p4[ap_tvar_int_0] = tmp_V_12_fu_1442_p3[19 - ap_tvar_int_0];
        end
    end
end

assign p_Result_12_fu_1531_p2 = (tmp_V_12_reg_2484 & lshr_ln947_1_fu_1525_p2);

assign p_Result_13_fu_1568_p3 = tmp_V_12_reg_2484[add_ln949_1_fu_1562_p2];

integer ap_tvar_int_1;

always @ (tmp_V_13_fu_1730_p3) begin
    for (ap_tvar_int_1 = 20 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 19 - 0) begin
            p_Result_16_fu_1738_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            p_Result_16_fu_1738_p4[ap_tvar_int_1] = tmp_V_13_fu_1730_p3[19 - ap_tvar_int_1];
        end
    end
end

assign p_Result_18_fu_1855_p2 = (tmp_V_13_reg_2532 & lshr_ln947_2_fu_1849_p2);

assign p_Result_19_fu_1892_p3 = tmp_V_13_reg_2532[add_ln949_2_fu_1886_p2];

assign p_Result_22_fu_1159_p3 = {{12'd4095}, {p_Result_s_fu_1149_p4}};

assign p_Result_23_fu_1398_p5 = {{m_26_fu_1370_p1[63:32]}, {tmp_s_fu_1391_p3}, {m_26_fu_1370_p1[22:0]}};

assign p_Result_25_fu_1460_p3 = {{12'd4095}, {p_Result_10_fu_1450_p4}};

assign p_Result_26_fu_1701_p5 = {{m_27_fu_1663_p1[63:32]}, {tmp_4_fu_1694_p3}, {m_27_fu_1663_p1[22:0]}};

assign p_Result_27_fu_1722_p3 = reg_701[32'd19];

assign p_Result_28_fu_1748_p3 = {{12'd4095}, {p_Result_16_fu_1738_p4}};

assign p_Result_29_fu_2096_p5 = {{m_28_fu_2058_p1[63:32]}, {tmp_6_fu_2089_p3}, {m_28_fu_2058_p1[22:0]}};

assign p_Result_3_fu_1265_p3 = tmp_V_10_reg_2414[add_ln949_fu_1260_p2];

assign p_Result_4_fu_1229_p2 = (tmp_V_10_reg_2414 & lshr_ln947_fu_1223_p2);

integer ap_tvar_int_2;

always @ (tmp_V_10_fu_1142_p3) begin
    for (ap_tvar_int_2 = 20 - 1; ap_tvar_int_2 >= 0; ap_tvar_int_2 = ap_tvar_int_2 - 1) begin
        if (ap_tvar_int_2 > 19 - 0) begin
            p_Result_s_fu_1149_p4[ap_tvar_int_2] = 1'b0;
        end else begin
            p_Result_s_fu_1149_p4[ap_tvar_int_2] = tmp_V_10_fu_1142_p3[19 - ap_tvar_int_2];
        end
    end
end

assign select_ln111_1_fu_2116_p3 = ((or_ln111_fu_1995_p2[0:0] === 1'b1) ? select_ln111_fu_2000_p3 : bitcast_ln739_2_fu_2112_p1);

assign select_ln111_fu_2000_p3 = ((and_ln111_1_fu_1983_p2[0:0] === 1'b1) ? 32'd0 : maxv_0_reg_597);

assign select_ln935_fu_1418_p3 = ((icmp_ln935_reg_2409[0:0] === 1'b1) ? 32'd0 : bitcast_ln739_fu_1414_p1);

assign select_ln964_1_fu_1675_p3 = ((tmp_20_fu_1667_p3[0:0] === 1'b1) ? 8'd127 : 8'd126);

assign select_ln964_2_fu_2070_p3 = ((tmp_24_fu_2062_p3[0:0] === 1'b1) ? 8'd127 : 8'd126);

assign select_ln964_fu_1373_p3 = ((tmp_15_reg_2449[0:0] === 1'b1) ? 8'd127 : 8'd126);

assign sext_ln104_fu_1070_p1 = $signed(B4_V_q0);

assign sext_ln94_fu_850_p1 = $signed(B2_V_q0);

assign sext_ln99_fu_960_p1 = $signed(B3_V_q0);

assign shl_ln958_1_fu_1631_p2 = m_15_fu_1613_p1 << zext_ln958_3_fu_1628_p1;

assign shl_ln958_2_fu_2026_p2 = m_21_fu_2008_p1 << zext_ln958_5_fu_2023_p1;

assign shl_ln958_fu_1328_p2 = m_fu_1292_p1 << zext_ln958_1_fu_1324_p1;

assign sub_ln944_1_fu_1480_p2 = (32'd20 - l_1_reg_2492);

assign sub_ln944_2_fu_1804_p2 = (32'd20 - l_2_reg_2540);

assign sub_ln944_fu_1175_p2 = (32'd20 - l_fu_1167_p3);

assign sub_ln947_1_fu_1515_p2 = (5'd13 - trunc_ln947_1_fu_1511_p1);

assign sub_ln947_2_fu_1839_p2 = (5'd13 - trunc_ln947_2_fu_1835_p1);

assign sub_ln947_fu_1214_p2 = (5'd13 - trunc_ln947_reg_2434);

assign sub_ln958_1_fu_1607_p2 = (32'd25 - sub_ln944_1_fu_1480_p2);

assign sub_ln958_2_fu_1931_p2 = (32'd25 - sub_ln944_2_fu_1804_p2);

assign sub_ln958_fu_1319_p2 = (32'd25 - sub_ln944_reg_2422);

assign sub_ln964_1_fu_1683_p2 = (8'd6 - trunc_ln943_1_reg_2497);

assign sub_ln964_2_fu_2078_p2 = (8'd6 - trunc_ln943_2_reg_2545);

assign sub_ln964_fu_1380_p2 = (8'd6 - trunc_ln943_reg_2439);

assign tmp_10_fu_769_p3 = p_Val2_1_reg_476[32'd19];

assign tmp_11_fu_889_p3 = p_Val2_4_reg_509[32'd19];

assign tmp_13_fu_1198_p4 = {{lsb_index_fu_1193_p2[31:1]}};

assign tmp_14_fu_1246_p3 = lsb_index_fu_1193_p2[32'd31];

assign tmp_16_fu_999_p3 = p_Val2_9_reg_542[32'd19];

assign tmp_18_fu_1495_p4 = {{lsb_index_1_fu_1489_p2[31:1]}};

assign tmp_19_fu_1548_p3 = lsb_index_1_fu_1489_p2[32'd31];

assign tmp_1_fu_1778_p4 = {{bitcast_ln111_fu_1774_p1[30:23]}};

assign tmp_20_fu_1667_p3 = m_17_fu_1647_p2[32'd25];

assign tmp_22_fu_1819_p4 = {{lsb_index_2_fu_1813_p2[31:1]}};

assign tmp_23_fu_1872_p3 = lsb_index_2_fu_1813_p2[32'd31];

assign tmp_24_fu_2062_p3 = m_23_fu_2042_p2[32'd25];

assign tmp_3_fu_1941_p4 = {{bitcast_ln111_1_fu_1937_p1[30:23]}};

assign tmp_4_fu_1694_p3 = {{p_Result_24_reg_2479}, {add_ln964_1_fu_1688_p2}};

assign tmp_6_fu_2089_p3 = {{p_Result_27_reg_2527}, {add_ln964_2_fu_2083_p2}};

assign tmp_7_fu_832_p3 = {{j4_0_reg_497}, {2'd0}};

assign tmp_8_fu_948_p3 = {{j5_0_reg_530}, {3'd0}};

assign tmp_9_fu_1058_p3 = {{j6_0_reg_563}, {3'd0}};

assign tmp_V_10_fu_1142_p3 = ((p_Result_21_reg_2403[0:0] === 1'b1) ? tmp_V_fu_1136_p2 : reg_701);

assign tmp_V_12_fu_1442_p3 = ((grp_fu_687_p3[0:0] === 1'b1) ? grp_fu_695_p2 : z4_V_q0);

assign tmp_V_13_fu_1730_p3 = ((p_Result_27_fu_1722_p3[0:0] === 1'b1) ? grp_fu_695_p2 : reg_701);

assign tmp_V_fu_1136_p2 = (20'd0 - reg_701);

assign tmp_s_fu_1391_p3 = {{p_Result_21_reg_2403}, {add_ln964_fu_1385_p2}};

assign trunc_ln111_1_fu_1951_p1 = bitcast_ln111_1_fu_1937_p1[22:0];

assign trunc_ln111_fu_1788_p1 = bitcast_ln111_fu_1774_p1[22:0];

assign trunc_ln738_1_fu_1713_p1 = p_Result_26_fu_1701_p5[31:0];

assign trunc_ln738_2_fu_2108_p1 = p_Result_29_fu_2096_p5[31:0];

assign trunc_ln738_fu_1410_p1 = p_Result_23_fu_1398_p5[31:0];

assign trunc_ln943_1_fu_1476_p1 = l_1_fu_1468_p3[7:0];

assign trunc_ln943_2_fu_1764_p1 = l_2_fu_1756_p3[7:0];

assign trunc_ln943_fu_1189_p1 = l_fu_1167_p3[7:0];

assign trunc_ln944_1_fu_1485_p1 = sub_ln944_1_fu_1480_p2[19:0];

assign trunc_ln944_2_fu_1809_p1 = sub_ln944_2_fu_1804_p2[19:0];

assign trunc_ln944_fu_1181_p1 = sub_ln944_fu_1175_p2[19:0];

assign trunc_ln947_1_fu_1511_p1 = sub_ln944_1_fu_1480_p2[4:0];

assign trunc_ln947_2_fu_1835_p1 = sub_ln944_2_fu_1804_p2[4:0];

assign trunc_ln947_fu_1185_p1 = sub_ln944_fu_1175_p2[4:0];

assign xor_ln111_fu_1989_p2 = (1'd1 ^ and_ln111_1_fu_1983_p2);

assign xor_ln949_1_fu_1556_p2 = (tmp_19_fu_1548_p3 ^ 1'd1);

assign xor_ln949_2_fu_1880_p2 = (tmp_23_fu_1872_p3 ^ 1'd1);

assign xor_ln949_fu_1254_p2 = (tmp_14_fu_1246_p3 ^ 1'd1);

assign zext_ln104_1_fu_1066_p1 = tmp_9_fu_1058_p3;

assign zext_ln104_fu_1053_p1 = j6_0_reg_563;

assign zext_ln110_fu_1431_p1 = j7_0_reg_607;

assign zext_ln1117_1_fu_840_p1 = tmp_7_fu_832_p3;

assign zext_ln1117_2_fu_750_p1 = i_0_i_reg_486;

assign zext_ln1117_3_fu_760_p1 = add_ln1117_1_fu_754_p2;

assign zext_ln1117_4_fu_871_p1 = i_0_i10_reg_519;

assign zext_ln1117_5_fu_880_p1 = add_ln1117_2_fu_875_p2;

assign zext_ln1117_6_fu_981_p1 = i_0_i26_reg_552;

assign zext_ln1117_7_fu_990_p1 = add_ln1117_3_fu_985_p2;

assign zext_ln1117_8_fu_1091_p1 = i_0_i42_reg_586;

assign zext_ln1117_9_fu_1100_p1 = add_ln1117_4_fu_1095_p2;

assign zext_ln1117_fu_828_p1 = j4_0_reg_497;

assign zext_ln119_fu_2136_p1 = j8_0_reg_643;

assign zext_ln125_fu_2153_p1 = j9_0_reg_654;

assign zext_ln69_1_fu_866_p1 = i_0_i10_reg_519;

assign zext_ln69_2_fu_976_p1 = i_0_i26_reg_552;

assign zext_ln69_3_fu_1086_p1 = i_0_i42_reg_586;

assign zext_ln69_fu_745_p1 = i_0_i_reg_486;

assign zext_ln89_1_fu_729_p1 = B1_V_q0;

assign zext_ln89_fu_724_p1 = j_0_reg_453;

assign zext_ln947_1_fu_1521_p1 = sub_ln947_1_fu_1515_p2;

assign zext_ln947_2_fu_1845_p1 = sub_ln947_2_fu_1839_p2;

assign zext_ln947_fu_1219_p1 = sub_ln947_fu_1214_p2;

assign zext_ln94_fu_823_p1 = j4_0_reg_497;

assign zext_ln957_1_fu_1295_p1 = tmp_V_10_reg_2414;

assign zext_ln957_2_fu_1616_p1 = tmp_V_12_reg_2484;

assign zext_ln957_3_fu_2011_p1 = tmp_V_13_reg_2532;

assign zext_ln958_1_fu_1324_p1 = sub_ln958_fu_1319_p2;

assign zext_ln958_2_fu_1624_p1 = lshr_ln958_1_fu_1619_p2;

assign zext_ln958_3_fu_1628_p1 = sub_ln958_1_reg_2517;

assign zext_ln958_4_fu_2019_p1 = lshr_ln958_2_fu_2014_p2;

assign zext_ln958_5_fu_2023_p1 = sub_ln958_2_reg_2580;

assign zext_ln958_fu_1315_p1 = lshr_ln958_fu_1309_p2;

assign zext_ln961_1_fu_1644_p1 = or_ln949_2_reg_2502;

assign zext_ln961_2_fu_2039_p1 = or_ln949_4_reg_2565;

assign zext_ln961_fu_1342_p1 = or_ln_fu_1284_p3;

assign zext_ln99_1_fu_956_p1 = tmp_8_fu_948_p3;

assign zext_ln99_fu_943_p1 = j5_0_reg_530;

always @ (posedge ap_clk) begin
    zext_ln89_reg_2207[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln94_reg_2253[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln99_reg_2304[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln99_1_reg_2314[2:0] <= 3'b000;
    zext_ln99_1_reg_2314[7] <= 1'b0;
    zext_ln104_reg_2355[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln104_1_reg_2370[2:0] <= 3'b000;
    zext_ln104_1_reg_2370[7] <= 1'b0;
    zext_ln110_reg_2463[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    or_ln949_2_reg_2502[31:1] <= 31'b0000000000000000000000000000000;
    or_ln949_4_reg_2565[31:1] <= 31'b0000000000000000000000000000000;
    zext_ln119_reg_2598[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //mlp
