#!/usr/bin/env python3
"""
Hardware Architectures for AI - Lab 7, Step 1
============================================
Extract the weights / biases of the Lab 5 floating-point MLP and a few MNIST
test images (+ their golden softmax outputs) and splice them straight into the
Vivado HLS sources.  Everything lives in three files only:

    ../mlp_FP/mlp.cpp     <- weights + biases (between the AUTO-GEN markers)
    ../mlp_FP/mlp_tb.cpp  <- test images + golden outputs (between the markers)
    ../mlp_FP/mlp.h       <- data type + prototypes (hand written, untouched)

Model (Lab 5, first / floating-point model):
    Input(28,28) -> Flatten -> 784
      -> Dense(5)  -> ReLU
      -> Dense(8)  -> ReLU
      -> Dense(8)  -> ReLU
      -> Dense(10) -> softmax
"""
import os, re, datetime
import h5py, numpy as np
from tensorflow import keras

HERE   = os.path.dirname(os.path.abspath(__file__))
H5     = os.path.join(HERE, "..", "..", "Lab5", "weights_floatingpoint.weights.h5")
SRCDIR = os.path.join(HERE, "..", "mlp_FP")
N_TEST = 5

BEG = "/* ===== AUTO-GENERATED by deliverables/export_weights.py -- DO NOT EDIT ===== */"
END = "/* ===== END AUTO-GENERATED ===== */"

# ---------------------------------------------------------------- load weights
f  = h5py.File(H5, "r")
W1 = f["layers/dense/vars/0"][:];    b1 = f["layers/dense/vars/1"][:]   # (784,5)
W2 = f["layers/dense_1/vars/0"][:];  b2 = f["layers/dense_1/vars/1"][:] # (5,8)
W3 = f["layers/dense_2/vars/0"][:];  b3 = f["layers/dense_2/vars/1"][:] # (8,8)
W4 = f["layers/dense_3/vars/0"][:];  b4 = f["layers/dense_3/vars/1"][:] # (8,10)

# ---------------------------------------------------------------- MNIST inputs
(_, _), (x_test, y_test) = keras.datasets.mnist.load_data()
x_test_n = (x_test.astype("float32") / x_test.max()).astype("float32")   # /255

# ---------------------------------------------------------------- NumPy golden
relu = lambda x: np.maximum(x, 0.0)
def softmax(x):
    e = np.exp(x - x.max()); return e / e.sum()
def forward(img):
    x  = img.reshape(-1).astype("float32")
    a1 = relu(x  @ W1 + b1)
    a2 = relu(a1 @ W2 + b2)
    a3 = relu(a2 @ W3 + b3)
    z4 = a3 @ W4 + b4
    return z4.astype("float32"), softmax(z4).astype("float32")

imgs   = x_test_n[:N_TEST]
labels = y_test[:N_TEST]
golden = np.array([forward(im)[1] for im in imgs], dtype="float32")

# ---------------------------------------------------------------- C emitters
def vec(name, a):
    return "static const data_t {}[{}] = {{{}}};".format(
        name, len(a), ", ".join("{:.9e}f".format(float(v)) for v in a))

def mat_T(name, a):
    """emit a.T  ->  [n_out][n_in] so every neuron's weights are contiguous"""
    aT = a.T
    rows, cols = aT.shape
    lines = ["static const data_t {}[{}][{}] = {{".format(name, rows, cols)]
    for r in range(rows):
        lines.append("  {" + ", ".join("{:.9e}f".format(float(v)) for v in aT[r]) +
                     "}" + ("," if r < rows - 1 else ""))
    lines.append("};")
    return "\n".join(lines)

stamp = datetime.date.today().isoformat()

weights_block = "\n\n".join([
    "/* weights from Lab5/weights_floatingpoint.weights.h5  (generated %s)" % stamp,
    " * kernels transposed to W[n_out][n_in]:  y_j = sum_i x_i * W[j][i] + B[j] */",
    "/* ---- layer 1 : dense_1  (784 -> 5), ReLU ---- */\n" + mat_T("W1", W1) + "\n" + vec("B1", b1),
    "/* ---- layer 2 : dense_2  (5 -> 8), ReLU ---- */\n"   + mat_T("W2", W2) + "\n" + vec("B2", b2),
    "/* ---- layer 3 : dense_3  (8 -> 8), ReLU ---- */\n"   + mat_T("W3", W3) + "\n" + vec("B3", b3),
    "/* ---- layer 4 : output_layer  (8 -> 10), softmax ---- */\n" + mat_T("W4", W4) + "\n" + vec("B4", b4),
]).replace("/* weights", "\n/* weights", 1).lstrip("\n")

# test-data block for the testbench
tb_lines = []
tb_lines.append("/* first %d MNIST test images + NumPy golden softmax (generated %s) */" % (N_TEST, stamp))
tb_lines.append("#define N_TEST %d" % N_TEST)
tb_lines.append("")
tb_lines.append("static const int test_label[N_TEST]   = {%s};" %
                ", ".join(str(int(v)) for v in labels))
tb_lines.append("static const int golden_class[N_TEST] = {%s};" %
                ", ".join(str(int(golden[i].argmax())) for i in range(N_TEST)))
tb_lines.append("")
tb_lines.append("static const data_t test_input[N_TEST][IN_SIZE] = {")
for i in range(N_TEST):
    flat = imgs[i].reshape(-1)
    tb_lines.append("  { /* image %d  (label %d) */" % (i, int(labels[i])))
    tb_lines.append("    " + ", ".join("{:.7e}f".format(float(v)) for v in flat))
    tb_lines.append("  }" + ("," if i < N_TEST - 1 else ""))
tb_lines.append("};")
tb_lines.append("")
tb_lines.append("static const data_t golden_output[N_TEST][OUT_SIZE] = {")
for i in range(N_TEST):
    tb_lines.append("  {" + ", ".join("{:.9e}f".format(float(v)) for v in golden[i]) +
                    "}" + ("," if i < N_TEST - 1 else ""))
tb_lines.append("};")
tbdata_block = "\n".join(tb_lines)

# ---------------------------------------------------------------- splice in
def splice(path, block):
    txt = open(path).read()
    new = "{}\n{}\n{}".format(BEG, block, END)
    if BEG in txt and END in txt:
        txt = re.sub(re.escape(BEG) + r".*?" + re.escape(END), lambda m: new, txt, flags=re.S)
    else:
        raise SystemExit("markers not found in %s -- add:\n%s\n%s" % (path, BEG, END))
    open(path, "w").write(txt)
    print("  spliced:", os.path.normpath(path))

splice(os.path.join(SRCDIR, "mlp.cpp"),    weights_block)
splice(os.path.join(SRCDIR, "mlp_tb.cpp"), tbdata_block)

# ---------------------------------------------------------------- console / log
print("=" * 74)
print(" Lab 7 - Step 1 : weight / bias / input export")
print("=" * 74)
for n, a in [("dense_1 W", W1), ("dense_1 b", b1), ("dense_2 W", W2), ("dense_2 b", b2),
             ("dense_3 W", W3), ("dense_3 b", b3), ("output  W", W4), ("output  b", b4)]:
    print("  %-10s shape %-9s  min %+.6f  max %+.6f  mean %+.6f" %
          (n, str(a.shape), a.min(), a.max(), a.mean()))
print()
print("  MNIST test images exported : %d  (indices 0..%d)" % (N_TEST, N_TEST - 1))
for i in range(N_TEST):
    p = golden[i]
    print("    img %d: label %d  argmax %d  p(max)=%.5f" %
          (i, int(labels[i]), int(p.argmax()), p.max()))
