// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="neuron,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu3eg-sbva484-1-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.846000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=1,HLS_SYN_FF=0,HLS_SYN_LUT=0,HLS_VERSION=2019_1}" *)

module neuron (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        w_fxp_V,
        x_fxp_V,
        b_fxp_V,
        ap_return
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] w_fxp_V;
input  [15:0] x_fxp_V;
input  [15:0] b_fxp_V;
output  [15:0] ap_return;

wire  signed [21:0] grp_fu_69_p3;
wire   [21:0] grp_fu_69_p2;

neuron_mac_muladd_16s_16s_22ns_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 22 ),
    .dout_WIDTH( 22 ))
neuron_mac_muladd_16s_16s_22ns_22_1_1_U1(
    .din0(w_fxp_V),
    .din1(x_fxp_V),
    .din2(grp_fu_69_p2),
    .dout(grp_fu_69_p3)
);

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

assign ap_return = {{grp_fu_69_p3[21:6]}};

assign grp_fu_69_p2 = {{b_fxp_V}, {6'd0}};

endmodule //neuron
