-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matrix_vector_mult is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    mat_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    mat_ce0 : OUT STD_LOGIC;
    mat_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    vec_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    vec_ce0 : OUT STD_LOGIC;
    vec_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    result_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
    result_ce0 : OUT STD_LOGIC;
    result_we0 : OUT STD_LOGIC;
    result_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of matrix_vector_mult is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matrix_vector_mult,hls_ip_2019_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.873000,HLS_SYN_LAT=25,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=3,HLS_SYN_FF=51,HLS_SYN_LUT=177,HLS_VERSION=2019_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal i_fu_107_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal i_reg_186 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal sub_ln10_fu_134_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln10_reg_191 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln7_fu_101_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_addr_reg_196 : STD_LOGIC_VECTOR (1 downto 0);
    signal j_fu_146_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal j_reg_204 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln9_fu_140_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln10_fu_177_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal i_0_reg_66 : STD_LOGIC_VECTOR (1 downto 0);
    signal result_load_reg_77 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_0_reg_90 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln8_fu_113_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln10_fu_166_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln10_fu_152_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_fu_122_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln10_2_fu_130_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln10_1_fu_118_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln10_3_fu_157_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln10_1_fu_161_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln10_fu_171_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln10_fu_171_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln10_fu_171_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i_0_reg_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln9_fu_140_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_0_reg_66 <= i_reg_186;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_0_reg_66 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    j_0_reg_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                j_0_reg_90 <= j_reg_204;
            elsif (((icmp_ln7_fu_101_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                j_0_reg_90 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    result_load_reg_77_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                result_load_reg_77 <= add_ln10_fu_177_p2;
            elsif (((icmp_ln7_fu_101_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                result_load_reg_77 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_reg_186 <= i_fu_107_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                j_reg_204 <= j_fu_146_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln7_fu_101_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                result_addr_reg_196 <= zext_ln8_fu_113_p1(2 - 1 downto 0);
                sub_ln10_reg_191 <= sub_ln10_fu_134_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln7_fu_101_p2, ap_CS_fsm_state3, icmp_ln9_fu_140_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln7_fu_101_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln9_fu_140_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln10_1_fu_161_p2 <= std_logic_vector(unsigned(sub_ln10_reg_191) + unsigned(zext_ln10_3_fu_157_p1));
    add_ln10_fu_177_p2 <= std_logic_vector(unsigned(mul_ln10_fu_171_p2) + unsigned(result_load_reg_77));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_done_assign_proc : process(ap_CS_fsm_state2, icmp_ln7_fu_101_p2)
    begin
        if (((icmp_ln7_fu_101_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln7_fu_101_p2)
    begin
        if (((icmp_ln7_fu_101_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    i_fu_107_p2 <= std_logic_vector(unsigned(i_0_reg_66) + unsigned(ap_const_lv2_1));
    icmp_ln7_fu_101_p2 <= "1" when (i_0_reg_66 = ap_const_lv2_3) else "0";
    icmp_ln9_fu_140_p2 <= "1" when (j_0_reg_90 = ap_const_lv2_3) else "0";
    j_fu_146_p2 <= std_logic_vector(unsigned(j_0_reg_90) + unsigned(ap_const_lv2_1));
    mat_address0 <= sext_ln10_fu_166_p1(4 - 1 downto 0);

    mat_ce0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mat_ce0 <= ap_const_logic_1;
        else 
            mat_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln10_fu_171_p0 <= vec_q0;
    mul_ln10_fu_171_p1 <= mat_q0;
    mul_ln10_fu_171_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(mul_ln10_fu_171_p0) * signed(mul_ln10_fu_171_p1))), 32));
    result_address0 <= result_addr_reg_196;

    result_ce0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            result_ce0 <= ap_const_logic_1;
        else 
            result_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    result_d0 <= result_load_reg_77;

    result_we0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            result_we0 <= ap_const_logic_1;
        else 
            result_we0 <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln10_fu_166_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln10_1_fu_161_p2),64));

    sub_ln10_fu_134_p2 <= std_logic_vector(unsigned(zext_ln10_2_fu_130_p1) - unsigned(zext_ln10_1_fu_118_p1));
    tmp_fu_122_p3 <= (i_0_reg_66 & ap_const_lv2_0);
    vec_address0 <= zext_ln10_fu_152_p1(2 - 1 downto 0);

    vec_ce0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            vec_ce0 <= ap_const_logic_1;
        else 
            vec_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln10_1_fu_118_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_0_reg_66),5));
    zext_ln10_2_fu_130_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_122_p3),5));
    zext_ln10_3_fu_157_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_0_reg_90),5));
    zext_ln10_fu_152_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_0_reg_90),64));
    zext_ln8_fu_113_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_0_reg_66),64));
end behav;
