// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "neuron.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic neuron::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic neuron::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<7> neuron::ap_ST_fsm_state1 = "1";
const sc_lv<7> neuron::ap_ST_fsm_state2 = "10";
const sc_lv<7> neuron::ap_ST_fsm_state3 = "100";
const sc_lv<7> neuron::ap_ST_fsm_state4 = "1000";
const sc_lv<7> neuron::ap_ST_fsm_state5 = "10000";
const sc_lv<7> neuron::ap_ST_fsm_state6 = "100000";
const sc_lv<7> neuron::ap_ST_fsm_state7 = "1000000";
const sc_lv<32> neuron::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> neuron::ap_const_lv32_2 = "10";
const sc_lv<32> neuron::ap_const_lv32_3 = "11";
const sc_lv<32> neuron::ap_const_lv32_6 = "110";
const bool neuron::ap_const_boolean_1 = true;

neuron::neuron(sc_module_name name) : sc_module(name), mVcdFile(0) {
    neuron_fadd_32ns_32ns_32_4_full_dsp_1_U1 = new neuron_fadd_32ns_32ns_32_4_full_dsp_1<1,4,32,32,32>("neuron_fadd_32ns_32ns_32_4_full_dsp_1_U1");
    neuron_fadd_32ns_32ns_32_4_full_dsp_1_U1->clk(ap_clk);
    neuron_fadd_32ns_32ns_32_4_full_dsp_1_U1->reset(ap_rst);
    neuron_fadd_32ns_32ns_32_4_full_dsp_1_U1->din0(tmp_reg_55);
    neuron_fadd_32ns_32ns_32_4_full_dsp_1_U1->din1(b);
    neuron_fadd_32ns_32ns_32_4_full_dsp_1_U1->ce(ap_var_for_const0);
    neuron_fadd_32ns_32ns_32_4_full_dsp_1_U1->dout(grp_fu_34_p2);
    neuron_fmul_32ns_32ns_32_3_max_dsp_1_U2 = new neuron_fmul_32ns_32ns_32_3_max_dsp_1<1,3,32,32,32>("neuron_fmul_32ns_32ns_32_3_max_dsp_1_U2");
    neuron_fmul_32ns_32ns_32_3_max_dsp_1_U2->clk(ap_clk);
    neuron_fmul_32ns_32ns_32_3_max_dsp_1_U2->reset(ap_rst);
    neuron_fmul_32ns_32ns_32_3_max_dsp_1_U2->din0(w);
    neuron_fmul_32ns_32ns_32_3_max_dsp_1_U2->din1(x);
    neuron_fmul_32ns_32ns_32_3_max_dsp_1_U2->ce(ap_var_for_const0);
    neuron_fmul_32ns_32ns_32_3_max_dsp_1_U2->dout(grp_fu_39_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_ap_return);
    sensitive << ( grp_fu_34_p2 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "0000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "neuron_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, w, "(port)w");
    sc_trace(mVcdFile, x, "(port)x");
    sc_trace(mVcdFile, b, "(port)b");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, grp_fu_39_p2, "grp_fu_39_p2");
    sc_trace(mVcdFile, tmp_reg_55, "tmp_reg_55");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, grp_fu_34_p2, "grp_fu_34_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("neuron.hdltvin.dat");
    mHdltvoutHandle.open("neuron.hdltvout.dat");
}

neuron::~neuron() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete neuron_fadd_32ns_32ns_32_4_full_dsp_1_U1;
    delete neuron_fmul_32ns_32ns_32_3_max_dsp_1_U2;
}

void neuron::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void neuron::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        tmp_reg_55 = grp_fu_39_p2.read();
    }
}

void neuron::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void neuron::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void neuron::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void neuron::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void neuron::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void neuron::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void neuron::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void neuron::thread_ap_return() {
    ap_return = grp_fu_34_p2.read();
}

void neuron::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXXXXXX";
            break;
    }
}

void neuron::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"w\" :  \"" << w.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"x\" :  \"" << x.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"b\" :  \"" << b.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_return\" :  \"" << ap_return.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

