// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mlp,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-i,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.669400,HLS_SYN_LAT=62230,HLS_SYN_TPT=none,HLS_SYN_MEM=11,HLS_SYN_DSP=12,HLS_SYN_FF=3001,HLS_SYN_LUT=3918,HLS_VERSION=2019_1}" *)

module mlp (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0,
        output_r_q0
);

parameter    ap_ST_fsm_state1 = 129'd1;
parameter    ap_ST_fsm_state2 = 129'd2;
parameter    ap_ST_fsm_state3 = 129'd4;
parameter    ap_ST_fsm_state4 = 129'd8;
parameter    ap_ST_fsm_state5 = 129'd16;
parameter    ap_ST_fsm_state6 = 129'd32;
parameter    ap_ST_fsm_state7 = 129'd64;
parameter    ap_ST_fsm_state8 = 129'd128;
parameter    ap_ST_fsm_state9 = 129'd256;
parameter    ap_ST_fsm_state10 = 129'd512;
parameter    ap_ST_fsm_state11 = 129'd1024;
parameter    ap_ST_fsm_state12 = 129'd2048;
parameter    ap_ST_fsm_state13 = 129'd4096;
parameter    ap_ST_fsm_state14 = 129'd8192;
parameter    ap_ST_fsm_state15 = 129'd16384;
parameter    ap_ST_fsm_state16 = 129'd32768;
parameter    ap_ST_fsm_state17 = 129'd65536;
parameter    ap_ST_fsm_state18 = 129'd131072;
parameter    ap_ST_fsm_state19 = 129'd262144;
parameter    ap_ST_fsm_state20 = 129'd524288;
parameter    ap_ST_fsm_state21 = 129'd1048576;
parameter    ap_ST_fsm_state22 = 129'd2097152;
parameter    ap_ST_fsm_state23 = 129'd4194304;
parameter    ap_ST_fsm_state24 = 129'd8388608;
parameter    ap_ST_fsm_state25 = 129'd16777216;
parameter    ap_ST_fsm_state26 = 129'd33554432;
parameter    ap_ST_fsm_state27 = 129'd67108864;
parameter    ap_ST_fsm_state28 = 129'd134217728;
parameter    ap_ST_fsm_state29 = 129'd268435456;
parameter    ap_ST_fsm_state30 = 129'd536870912;
parameter    ap_ST_fsm_state31 = 129'd1073741824;
parameter    ap_ST_fsm_state32 = 129'd2147483648;
parameter    ap_ST_fsm_state33 = 129'd4294967296;
parameter    ap_ST_fsm_state34 = 129'd8589934592;
parameter    ap_ST_fsm_state35 = 129'd17179869184;
parameter    ap_ST_fsm_state36 = 129'd34359738368;
parameter    ap_ST_fsm_state37 = 129'd68719476736;
parameter    ap_ST_fsm_state38 = 129'd137438953472;
parameter    ap_ST_fsm_state39 = 129'd274877906944;
parameter    ap_ST_fsm_state40 = 129'd549755813888;
parameter    ap_ST_fsm_state41 = 129'd1099511627776;
parameter    ap_ST_fsm_state42 = 129'd2199023255552;
parameter    ap_ST_fsm_state43 = 129'd4398046511104;
parameter    ap_ST_fsm_state44 = 129'd8796093022208;
parameter    ap_ST_fsm_state45 = 129'd17592186044416;
parameter    ap_ST_fsm_state46 = 129'd35184372088832;
parameter    ap_ST_fsm_state47 = 129'd70368744177664;
parameter    ap_ST_fsm_state48 = 129'd140737488355328;
parameter    ap_ST_fsm_state49 = 129'd281474976710656;
parameter    ap_ST_fsm_state50 = 129'd562949953421312;
parameter    ap_ST_fsm_state51 = 129'd1125899906842624;
parameter    ap_ST_fsm_state52 = 129'd2251799813685248;
parameter    ap_ST_fsm_state53 = 129'd4503599627370496;
parameter    ap_ST_fsm_state54 = 129'd9007199254740992;
parameter    ap_ST_fsm_state55 = 129'd18014398509481984;
parameter    ap_ST_fsm_state56 = 129'd36028797018963968;
parameter    ap_ST_fsm_state57 = 129'd72057594037927936;
parameter    ap_ST_fsm_state58 = 129'd144115188075855872;
parameter    ap_ST_fsm_state59 = 129'd288230376151711744;
parameter    ap_ST_fsm_state60 = 129'd576460752303423488;
parameter    ap_ST_fsm_state61 = 129'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 129'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 129'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 129'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 129'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 129'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 129'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 129'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 129'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 129'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 129'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 129'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 129'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 129'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 129'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 129'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 129'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 129'd151115727451828646838272;
parameter    ap_ST_fsm_state79 = 129'd302231454903657293676544;
parameter    ap_ST_fsm_state80 = 129'd604462909807314587353088;
parameter    ap_ST_fsm_state81 = 129'd1208925819614629174706176;
parameter    ap_ST_fsm_state82 = 129'd2417851639229258349412352;
parameter    ap_ST_fsm_state83 = 129'd4835703278458516698824704;
parameter    ap_ST_fsm_state84 = 129'd9671406556917033397649408;
parameter    ap_ST_fsm_state85 = 129'd19342813113834066795298816;
parameter    ap_ST_fsm_state86 = 129'd38685626227668133590597632;
parameter    ap_ST_fsm_state87 = 129'd77371252455336267181195264;
parameter    ap_ST_fsm_state88 = 129'd154742504910672534362390528;
parameter    ap_ST_fsm_state89 = 129'd309485009821345068724781056;
parameter    ap_ST_fsm_state90 = 129'd618970019642690137449562112;
parameter    ap_ST_fsm_state91 = 129'd1237940039285380274899124224;
parameter    ap_ST_fsm_state92 = 129'd2475880078570760549798248448;
parameter    ap_ST_fsm_state93 = 129'd4951760157141521099596496896;
parameter    ap_ST_fsm_state94 = 129'd9903520314283042199192993792;
parameter    ap_ST_fsm_state95 = 129'd19807040628566084398385987584;
parameter    ap_ST_fsm_state96 = 129'd39614081257132168796771975168;
parameter    ap_ST_fsm_state97 = 129'd79228162514264337593543950336;
parameter    ap_ST_fsm_state98 = 129'd158456325028528675187087900672;
parameter    ap_ST_fsm_state99 = 129'd316912650057057350374175801344;
parameter    ap_ST_fsm_state100 = 129'd633825300114114700748351602688;
parameter    ap_ST_fsm_state101 = 129'd1267650600228229401496703205376;
parameter    ap_ST_fsm_state102 = 129'd2535301200456458802993406410752;
parameter    ap_ST_fsm_state103 = 129'd5070602400912917605986812821504;
parameter    ap_ST_fsm_state104 = 129'd10141204801825835211973625643008;
parameter    ap_ST_fsm_state105 = 129'd20282409603651670423947251286016;
parameter    ap_ST_fsm_state106 = 129'd40564819207303340847894502572032;
parameter    ap_ST_fsm_state107 = 129'd81129638414606681695789005144064;
parameter    ap_ST_fsm_state108 = 129'd162259276829213363391578010288128;
parameter    ap_ST_fsm_state109 = 129'd324518553658426726783156020576256;
parameter    ap_ST_fsm_state110 = 129'd649037107316853453566312041152512;
parameter    ap_ST_fsm_state111 = 129'd1298074214633706907132624082305024;
parameter    ap_ST_fsm_state112 = 129'd2596148429267413814265248164610048;
parameter    ap_ST_fsm_state113 = 129'd5192296858534827628530496329220096;
parameter    ap_ST_fsm_state114 = 129'd10384593717069655257060992658440192;
parameter    ap_ST_fsm_state115 = 129'd20769187434139310514121985316880384;
parameter    ap_ST_fsm_state116 = 129'd41538374868278621028243970633760768;
parameter    ap_ST_fsm_state117 = 129'd83076749736557242056487941267521536;
parameter    ap_ST_fsm_state118 = 129'd166153499473114484112975882535043072;
parameter    ap_ST_fsm_state119 = 129'd332306998946228968225951765070086144;
parameter    ap_ST_fsm_state120 = 129'd664613997892457936451903530140172288;
parameter    ap_ST_fsm_state121 = 129'd1329227995784915872903807060280344576;
parameter    ap_ST_fsm_state122 = 129'd2658455991569831745807614120560689152;
parameter    ap_ST_fsm_state123 = 129'd5316911983139663491615228241121378304;
parameter    ap_ST_fsm_state124 = 129'd10633823966279326983230456482242756608;
parameter    ap_ST_fsm_state125 = 129'd21267647932558653966460912964485513216;
parameter    ap_ST_fsm_state126 = 129'd42535295865117307932921825928971026432;
parameter    ap_ST_fsm_state127 = 129'd85070591730234615865843651857942052864;
parameter    ap_ST_fsm_state128 = 129'd170141183460469231731687303715884105728;
parameter    ap_ST_fsm_state129 = 129'd340282366920938463463374607431768211456;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] input_r_address0;
output   input_r_ce0;
input  [31:0] input_r_q0;
output  [3:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [31:0] output_r_d0;
input  [31:0] output_r_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_r_ce0;
reg[3:0] output_r_address0;
reg output_r_ce0;
reg output_r_we0;
reg[31:0] output_r_d0;

(* fsm_encoding = "none" *) reg   [128:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] B1_address0;
reg    B1_ce0;
wire   [31:0] B1_q0;
wire   [11:0] W1_address0;
reg    W1_ce0;
wire   [31:0] W1_q0;
wire   [2:0] B2_address0;
reg    B2_ce0;
wire   [31:0] B2_q0;
wire   [5:0] W2_address0;
reg    W2_ce0;
wire   [31:0] W2_q0;
wire   [2:0] B3_address0;
reg    B3_ce0;
wire   [31:0] B3_q0;
wire   [5:0] W3_address0;
reg    W3_ce0;
wire   [31:0] W3_q0;
wire   [3:0] B4_address0;
reg    B4_ce0;
wire   [31:0] B4_q0;
wire   [6:0] W4_address0;
reg    W4_ce0;
wire   [31:0] W4_q0;
wire   [31:0] grp_fu_558_p2;
reg   [31:0] reg_582;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state48;
wire    ap_CS_fsm_state67;
wire   [31:0] grp_fu_548_p2;
reg   [31:0] reg_587;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state37;
wire    ap_CS_fsm_state56;
wire    ap_CS_fsm_state75;
wire    ap_CS_fsm_state89;
wire   [31:0] z4_q0;
reg   [31:0] reg_596;
wire    ap_CS_fsm_state76;
wire    ap_CS_fsm_state81;
wire   [11:0] add_ln86_fu_602_p2;
reg   [11:0] add_ln86_reg_1138;
wire    ap_CS_fsm_state2;
wire   [2:0] j_fu_614_p2;
reg   [2:0] j_reg_1146;
wire   [63:0] zext_ln87_fu_620_p1;
reg   [63:0] zext_ln87_reg_1151;
wire   [0:0] icmp_ln86_fu_608_p2;
wire    ap_CS_fsm_state3;
wire   [9:0] i_fu_631_p2;
reg   [9:0] i_reg_1169;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln68_fu_625_p2;
reg   [31:0] input_load_reg_1184;
wire    ap_CS_fsm_state5;
reg   [31:0] W1_load_reg_1189;
wire   [0:0] grp_fu_567_p2;
reg   [0:0] tmp_1_reg_1194;
wire    ap_CS_fsm_state19;
wire   [3:0] j_1_fu_713_p2;
reg   [3:0] j_1_reg_1202;
wire    ap_CS_fsm_state21;
wire   [63:0] zext_ln91_fu_719_p1;
reg   [63:0] zext_ln91_reg_1207;
wire   [0:0] icmp_ln90_fu_707_p2;
wire   [6:0] add_ln69_fu_740_p2;
reg   [6:0] add_ln69_reg_1217;
wire    ap_CS_fsm_state22;
wire   [2:0] i_1_fu_752_p2;
reg   [2:0] i_1_reg_1230;
wire    ap_CS_fsm_state23;
wire   [0:0] icmp_ln68_1_fu_746_p2;
wire   [31:0] a1_q0;
reg   [31:0] a1_load_reg_1245;
wire    ap_CS_fsm_state24;
reg   [31:0] W2_load_reg_1250;
reg   [0:0] tmp_3_reg_1255;
wire    ap_CS_fsm_state38;
wire   [3:0] j_2_fu_833_p2;
reg   [3:0] j_2_reg_1263;
wire    ap_CS_fsm_state40;
wire   [63:0] zext_ln95_fu_839_p1;
reg   [63:0] zext_ln95_reg_1268;
wire   [0:0] icmp_ln94_fu_827_p2;
wire   [7:0] zext_ln95_1_fu_852_p1;
reg   [7:0] zext_ln95_1_reg_1278;
wire    ap_CS_fsm_state41;
wire   [3:0] i_2_fu_862_p2;
reg   [3:0] i_2_reg_1291;
wire    ap_CS_fsm_state42;
wire   [0:0] icmp_ln68_2_fu_856_p2;
wire   [31:0] a2_q0;
reg   [31:0] a2_load_reg_1306;
wire    ap_CS_fsm_state43;
reg   [31:0] W3_load_reg_1311;
reg   [0:0] tmp_5_reg_1316;
wire    ap_CS_fsm_state57;
wire   [3:0] j_4_fu_943_p2;
reg   [3:0] j_4_reg_1324;
wire    ap_CS_fsm_state59;
wire   [63:0] zext_ln99_fu_949_p1;
reg   [63:0] zext_ln99_reg_1329;
wire   [0:0] icmp_ln98_fu_937_p2;
wire   [7:0] zext_ln99_1_fu_962_p1;
reg   [7:0] zext_ln99_1_reg_1344;
wire    ap_CS_fsm_state60;
wire   [3:0] i_3_fu_972_p2;
reg   [3:0] i_3_reg_1357;
wire    ap_CS_fsm_state61;
wire   [0:0] icmp_ln68_3_fu_966_p2;
wire   [31:0] a3_q0;
reg   [31:0] a3_load_reg_1372;
wire    ap_CS_fsm_state62;
reg   [31:0] W4_load_reg_1377;
wire    ap_CS_fsm_state77;
wire   [0:0] icmp_ln103_fu_997_p2;
wire   [3:0] j_3_fu_1008_p2;
reg   [3:0] j_3_reg_1390;
reg   [31:0] maxv_1_reg_1395;
wire    ap_CS_fsm_state78;
wire   [31:0] maxv_2_fu_1097_p3;
wire    ap_CS_fsm_state79;
wire   [3:0] j_5_fu_1110_p2;
reg   [3:0] j_5_reg_1410;
wire    ap_CS_fsm_state80;
wire   [63:0] zext_ln110_fu_1116_p1;
reg   [63:0] zext_ln110_reg_1415;
wire   [0:0] icmp_ln109_fu_1104_p2;
wire   [31:0] grp_fu_577_p2;
reg   [31:0] e_reg_1425;
wire    ap_CS_fsm_state102;
wire    ap_CS_fsm_state110;
wire   [3:0] j_6_fu_1127_p2;
reg   [3:0] j_6_reg_1439;
wire    ap_CS_fsm_state111;
reg   [3:0] output_addr_1_reg_1444;
wire   [0:0] icmp_ln116_fu_1121_p2;
reg   [31:0] output_load_reg_1449;
wire    ap_CS_fsm_state112;
wire   [31:0] grp_fu_562_p2;
reg   [31:0] tmp_9_reg_1454;
wire    ap_CS_fsm_state128;
reg   [2:0] a1_address0;
reg    a1_ce0;
reg    a1_we0;
wire   [31:0] a1_d0;
reg   [2:0] a2_address0;
reg    a2_ce0;
reg    a2_we0;
wire   [31:0] a2_d0;
reg   [2:0] a3_address0;
reg    a3_ce0;
reg    a3_we0;
wire   [31:0] a3_d0;
reg   [3:0] z4_address0;
reg    z4_ce0;
reg    z4_we0;
reg   [2:0] j_0_reg_349;
wire    ap_CS_fsm_state20;
reg   [11:0] phi_mul_reg_360;
reg   [31:0] acc_0_i_reg_372;
reg   [9:0] i_0_i_reg_382;
reg   [3:0] j1_0_reg_393;
wire    ap_CS_fsm_state39;
reg   [31:0] acc_0_i6_reg_405;
reg   [2:0] i_0_i7_reg_415;
reg   [3:0] j2_0_reg_426;
wire    ap_CS_fsm_state58;
reg   [31:0] acc_0_i17_reg_438;
reg   [3:0] i_0_i18_reg_448;
reg   [3:0] j3_0_reg_459;
reg   [31:0] acc_0_i28_reg_471;
reg   [3:0] i_0_i29_reg_482;
reg   [3:0] j4_0_reg_493;
reg   [31:0] maxv_0_reg_504;
reg   [31:0] sum_0_reg_514;
reg   [3:0] j5_0_reg_526;
reg   [3:0] j6_0_reg_537;
wire    ap_CS_fsm_state129;
wire   [63:0] zext_ln69_7_fu_652_p1;
wire   [63:0] zext_ln69_fu_637_p1;
wire   [63:0] zext_ln69_9_fu_772_p1;
wire   [63:0] zext_ln69_1_fu_758_p1;
wire   [63:0] zext_ln69_11_fu_882_p1;
wire   [63:0] zext_ln69_2_fu_868_p1;
wire   [63:0] zext_ln69_13_fu_992_p1;
wire   [63:0] zext_ln69_3_fu_978_p1;
wire   [63:0] zext_ln104_fu_1003_p1;
wire    ap_CS_fsm_state103;
wire   [63:0] zext_ln117_fu_1133_p1;
reg   [31:0] grp_fu_548_p0;
reg   [31:0] grp_fu_548_p1;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state30;
wire    ap_CS_fsm_state49;
wire    ap_CS_fsm_state68;
wire    ap_CS_fsm_state82;
reg   [31:0] grp_fu_558_p0;
reg   [31:0] grp_fu_558_p1;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state44;
wire    ap_CS_fsm_state63;
wire    ap_CS_fsm_state113;
reg   [31:0] grp_fu_567_p0;
reg   [31:0] grp_fu_567_p1;
wire    ap_CS_fsm_state90;
wire   [11:0] zext_ln69_6_fu_642_p1;
wire   [11:0] add_ln69_1_fu_646_p2;
wire   [31:0] bitcast_ln72_fu_657_p1;
wire   [7:0] tmp_fu_661_p4;
wire   [22:0] trunc_ln72_fu_671_p1;
wire   [0:0] icmp_ln72_1_fu_681_p2;
wire   [0:0] icmp_ln72_fu_675_p2;
wire   [0:0] or_ln72_fu_687_p2;
wire   [0:0] and_ln72_fu_693_p2;
wire   [5:0] tmp_10_fu_728_p3;
wire   [6:0] zext_ln69_4_fu_724_p1;
wire   [6:0] zext_ln69_5_fu_736_p1;
wire   [6:0] zext_ln69_8_fu_763_p1;
wire   [6:0] add_ln69_2_fu_767_p2;
wire   [31:0] bitcast_ln72_1_fu_777_p1;
wire   [7:0] tmp_2_fu_781_p4;
wire   [22:0] trunc_ln72_1_fu_791_p1;
wire   [0:0] icmp_ln72_3_fu_801_p2;
wire   [0:0] icmp_ln72_2_fu_795_p2;
wire   [0:0] or_ln72_1_fu_807_p2;
wire   [0:0] and_ln72_1_fu_813_p2;
wire   [6:0] tmp_11_fu_844_p3;
wire   [7:0] zext_ln69_10_fu_873_p1;
wire   [7:0] add_ln69_3_fu_877_p2;
wire   [31:0] bitcast_ln72_2_fu_887_p1;
wire   [7:0] tmp_4_fu_891_p4;
wire   [22:0] trunc_ln72_2_fu_901_p1;
wire   [0:0] icmp_ln72_5_fu_911_p2;
wire   [0:0] icmp_ln72_4_fu_905_p2;
wire   [0:0] or_ln72_2_fu_917_p2;
wire   [0:0] and_ln72_2_fu_923_p2;
wire   [6:0] tmp_12_fu_954_p3;
wire   [7:0] zext_ln69_12_fu_983_p1;
wire   [7:0] add_ln69_4_fu_987_p2;
wire   [31:0] bitcast_ln104_fu_1014_p1;
wire   [31:0] bitcast_ln104_1_fu_1031_p1;
wire   [7:0] tmp_6_fu_1017_p4;
wire   [22:0] trunc_ln104_fu_1027_p1;
wire   [0:0] icmp_ln104_1_fu_1055_p2;
wire   [0:0] icmp_ln104_fu_1049_p2;
wire   [7:0] tmp_8_fu_1035_p4;
wire   [22:0] trunc_ln104_1_fu_1045_p1;
wire   [0:0] icmp_ln104_3_fu_1073_p2;
wire   [0:0] icmp_ln104_2_fu_1067_p2;
wire   [0:0] or_ln104_fu_1061_p2;
wire   [0:0] or_ln104_1_fu_1079_p2;
wire   [0:0] and_ln104_fu_1085_p2;
wire   [0:0] and_ln104_1_fu_1091_p2;
reg   [1:0] grp_fu_548_opcode;
reg   [4:0] grp_fu_567_opcode;
reg   [128:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 129'd1;
end

mlp_B1 #(
    .DataWidth( 32 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
B1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(B1_address0),
    .ce0(B1_ce0),
    .q0(B1_q0)
);

mlp_W1 #(
    .DataWidth( 32 ),
    .AddressRange( 3920 ),
    .AddressWidth( 12 ))
W1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W1_address0),
    .ce0(W1_ce0),
    .q0(W1_q0)
);

mlp_B2 #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
B2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(B2_address0),
    .ce0(B2_ce0),
    .q0(B2_q0)
);

mlp_W2 #(
    .DataWidth( 32 ),
    .AddressRange( 40 ),
    .AddressWidth( 6 ))
W2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W2_address0),
    .ce0(W2_ce0),
    .q0(W2_q0)
);

mlp_B3 #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
B3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(B3_address0),
    .ce0(B3_ce0),
    .q0(B3_q0)
);

mlp_W3 #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
W3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W3_address0),
    .ce0(W3_ce0),
    .q0(W3_q0)
);

mlp_B4 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
B4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(B4_address0),
    .ce0(B4_ce0),
    .q0(B4_q0)
);

mlp_W4 #(
    .DataWidth( 32 ),
    .AddressRange( 80 ),
    .AddressWidth( 7 ))
W4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W4_address0),
    .ce0(W4_ce0),
    .q0(W4_q0)
);

mlp_a1 #(
    .DataWidth( 32 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
a1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(a1_address0),
    .ce0(a1_ce0),
    .we0(a1_we0),
    .d0(a1_d0),
    .q0(a1_q0)
);

mlp_a2 #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
a2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(a2_address0),
    .ce0(a2_ce0),
    .we0(a2_we0),
    .d0(a2_d0),
    .q0(a2_q0)
);

mlp_a2 #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
a3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(a3_address0),
    .ce0(a3_ce0),
    .we0(a3_we0),
    .d0(a3_d0),
    .q0(a3_q0)
);

mlp_z4 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
z4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(z4_address0),
    .ce0(z4_ce0),
    .we0(z4_we0),
    .d0(acc_0_i28_reg_471),
    .q0(z4_q0)
);

mlp_faddfsub_32ns_32ns_32_8_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mlp_faddfsub_32ns_32ns_32_8_full_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_548_p0),
    .din1(grp_fu_548_p1),
    .opcode(grp_fu_548_opcode),
    .ce(1'b1),
    .dout(grp_fu_548_p2)
);

mlp_fmul_32ns_32ns_32_5_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mlp_fmul_32ns_32ns_32_5_max_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_558_p0),
    .din1(grp_fu_558_p1),
    .ce(1'b1),
    .dout(grp_fu_558_p2)
);

mlp_fdiv_32ns_32ns_32_16_1 #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mlp_fdiv_32ns_32ns_32_16_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(output_load_reg_1449),
    .din1(sum_0_reg_514),
    .ce(1'b1),
    .dout(grp_fu_562_p2)
);

mlp_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
mlp_fcmp_32ns_32ns_1_2_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_567_p0),
    .din1(grp_fu_567_p1),
    .ce(1'b1),
    .opcode(grp_fu_567_opcode),
    .dout(grp_fu_567_p2)
);

mlp_fexp_32ns_32ns_32_13_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 13 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mlp_fexp_32ns_32ns_32_13_full_dsp_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(reg_587),
    .ce(1'b1),
    .dout(grp_fu_577_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        acc_0_i17_reg_438 <= grp_fu_548_p2;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        acc_0_i17_reg_438 <= B3_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state75)) begin
        acc_0_i28_reg_471 <= grp_fu_548_p2;
    end else if ((1'b1 == ap_CS_fsm_state60)) begin
        acc_0_i28_reg_471 <= B4_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        acc_0_i6_reg_405 <= grp_fu_548_p2;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        acc_0_i6_reg_405 <= B2_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        acc_0_i_reg_372 <= grp_fu_548_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        acc_0_i_reg_372 <= B1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        i_0_i18_reg_448 <= i_2_reg_1291;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        i_0_i18_reg_448 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state75)) begin
        i_0_i29_reg_482 <= i_3_reg_1357;
    end else if ((1'b1 == ap_CS_fsm_state60)) begin
        i_0_i29_reg_482 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        i_0_i7_reg_415 <= i_1_reg_1230;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        i_0_i7_reg_415 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        i_0_i_reg_382 <= i_reg_1169;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        i_0_i_reg_382 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln86_fu_608_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        j1_0_reg_393 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        j1_0_reg_393 <= j_1_reg_1202;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln90_fu_707_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
        j2_0_reg_426 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state58)) begin
        j2_0_reg_426 <= j_2_reg_1263;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln94_fu_827_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state40))) begin
        j3_0_reg_459 <= 4'd0;
    end else if (((icmp_ln68_3_fu_966_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state61))) begin
        j3_0_reg_459 <= j_4_reg_1324;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state79)) begin
        j4_0_reg_493 <= j_3_reg_1390;
    end else if ((1'b1 == ap_CS_fsm_state76)) begin
        j4_0_reg_493 <= 4'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln103_fu_997_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state77))) begin
        j5_0_reg_526 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state110)) begin
        j5_0_reg_526 <= j_5_reg_1410;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_fu_1104_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state80))) begin
        j6_0_reg_537 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state129)) begin
        j6_0_reg_537 <= j_6_reg_1439;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        j_0_reg_349 <= j_reg_1146;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        j_0_reg_349 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state79)) begin
        maxv_0_reg_504 <= maxv_2_fu_1097_p3;
    end else if ((1'b1 == ap_CS_fsm_state76)) begin
        maxv_0_reg_504 <= z4_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        phi_mul_reg_360 <= add_ln86_reg_1138;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        phi_mul_reg_360 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln103_fu_997_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state77))) begin
        sum_0_reg_514 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state110)) begin
        sum_0_reg_514 <= grp_fu_548_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        W1_load_reg_1189 <= W1_q0;
        input_load_reg_1184 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        W2_load_reg_1250 <= W2_q0;
        a1_load_reg_1245 <= a1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        W3_load_reg_1311 <= W3_q0;
        a2_load_reg_1306 <= a2_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state62)) begin
        W4_load_reg_1377 <= W4_q0;
        a3_load_reg_1372 <= a3_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        add_ln69_reg_1217 <= add_ln69_fu_740_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln86_reg_1138 <= add_ln86_fu_602_p2;
        j_reg_1146 <= j_fu_614_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state102)) begin
        e_reg_1425 <= grp_fu_577_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        i_1_reg_1230 <= i_1_fu_752_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        i_2_reg_1291 <= i_2_fu_862_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state61)) begin
        i_3_reg_1357 <= i_3_fu_972_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        i_reg_1169 <= i_fu_631_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        j_1_reg_1202 <= j_1_fu_713_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state40)) begin
        j_2_reg_1263 <= j_2_fu_833_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln103_fu_997_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state77))) begin
        j_3_reg_1390 <= j_3_fu_1008_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state59)) begin
        j_4_reg_1324 <= j_4_fu_943_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state80)) begin
        j_5_reg_1410 <= j_5_fu_1110_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state111)) begin
        j_6_reg_1439 <= j_6_fu_1127_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state78)) begin
        maxv_1_reg_1395 <= z4_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln116_fu_1121_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state111))) begin
        output_addr_1_reg_1444 <= zext_ln117_fu_1133_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state112)) begin
        output_load_reg_1449 <= output_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state67) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state10))) begin
        reg_582 <= grp_fu_558_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state89) | (1'b1 == ap_CS_fsm_state75) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state18))) begin
        reg_587 <= grp_fu_548_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state81) | (1'b1 == ap_CS_fsm_state76))) begin
        reg_596 <= z4_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        tmp_1_reg_1194 <= grp_fu_567_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        tmp_3_reg_1255 <= grp_fu_567_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state57)) begin
        tmp_5_reg_1316 <= grp_fu_567_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state128)) begin
        tmp_9_reg_1454 <= grp_fu_562_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_fu_1104_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state80))) begin
        zext_ln110_reg_1415[3 : 0] <= zext_ln110_fu_1116_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln86_fu_608_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        zext_ln87_reg_1151[2 : 0] <= zext_ln87_fu_620_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln90_fu_707_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state21))) begin
        zext_ln91_reg_1207[3 : 0] <= zext_ln91_fu_719_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        zext_ln95_1_reg_1278[6 : 3] <= zext_ln95_1_fu_852_p1[6 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln94_fu_827_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state40))) begin
        zext_ln95_reg_1268[3 : 0] <= zext_ln95_fu_839_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state60)) begin
        zext_ln99_1_reg_1344[6 : 3] <= zext_ln99_1_fu_962_p1[6 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln98_fu_937_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state59))) begin
        zext_ln99_reg_1329[3 : 0] <= zext_ln99_fu_949_p1[3 : 0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        B1_ce0 = 1'b1;
    end else begin
        B1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        B2_ce0 = 1'b1;
    end else begin
        B2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state40)) begin
        B3_ce0 = 1'b1;
    end else begin
        B3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state59)) begin
        B4_ce0 = 1'b1;
    end else begin
        B4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        W1_ce0 = 1'b1;
    end else begin
        W1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        W2_ce0 = 1'b1;
    end else begin
        W2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        W3_ce0 = 1'b1;
    end else begin
        W3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state61)) begin
        W4_ce0 = 1'b1;
    end else begin
        W4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        a1_address0 = zext_ln69_1_fu_758_p1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        a1_address0 = zext_ln87_reg_1151;
    end else begin
        a1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state23))) begin
        a1_ce0 = 1'b1;
    end else begin
        a1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        a1_we0 = 1'b1;
    end else begin
        a1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        a2_address0 = zext_ln69_2_fu_868_p1;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        a2_address0 = zext_ln91_reg_1207;
    end else begin
        a2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state42))) begin
        a2_ce0 = 1'b1;
    end else begin
        a2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        a2_we0 = 1'b1;
    end else begin
        a2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state61)) begin
        a3_address0 = zext_ln69_3_fu_978_p1;
    end else if ((1'b1 == ap_CS_fsm_state58)) begin
        a3_address0 = zext_ln95_reg_1268;
    end else begin
        a3_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state58) | (1'b1 == ap_CS_fsm_state61))) begin
        a3_ce0 = 1'b1;
    end else begin
        a3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state58)) begin
        a3_we0 = 1'b1;
    end else begin
        a3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln116_fu_1121_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state111))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln116_fu_1121_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state111))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state82)) begin
        grp_fu_548_opcode = 2'd1;
    end else if (((1'b1 == ap_CS_fsm_state68) | (1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state103))) begin
        grp_fu_548_opcode = 2'd0;
    end else begin
        grp_fu_548_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state103)) begin
        grp_fu_548_p0 = sum_0_reg_514;
    end else if ((1'b1 == ap_CS_fsm_state82)) begin
        grp_fu_548_p0 = reg_596;
    end else if ((1'b1 == ap_CS_fsm_state68)) begin
        grp_fu_548_p0 = acc_0_i28_reg_471;
    end else if ((1'b1 == ap_CS_fsm_state49)) begin
        grp_fu_548_p0 = acc_0_i17_reg_438;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_548_p0 = acc_0_i6_reg_405;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_548_p0 = acc_0_i_reg_372;
    end else begin
        grp_fu_548_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state103)) begin
        grp_fu_548_p1 = e_reg_1425;
    end else if ((1'b1 == ap_CS_fsm_state82)) begin
        grp_fu_548_p1 = maxv_0_reg_504;
    end else if (((1'b1 == ap_CS_fsm_state68) | (1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state11))) begin
        grp_fu_548_p1 = reg_582;
    end else begin
        grp_fu_548_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state63)) begin
        grp_fu_558_p0 = a3_load_reg_1372;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        grp_fu_558_p0 = a2_load_reg_1306;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_558_p0 = a1_load_reg_1245;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_558_p0 = input_load_reg_1184;
    end else begin
        grp_fu_558_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state63)) begin
        grp_fu_558_p1 = W4_load_reg_1377;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        grp_fu_558_p1 = W3_load_reg_1311;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_558_p1 = W2_load_reg_1250;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_558_p1 = W1_load_reg_1189;
    end else begin
        grp_fu_558_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state78)) begin
        grp_fu_567_opcode = 5'd2;
    end else if ((((icmp_ln68_2_fu_856_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state42)) | ((icmp_ln68_1_fu_746_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state23)) | ((icmp_ln68_fu_625_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
        grp_fu_567_opcode = 5'd4;
    end else begin
        grp_fu_567_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state78)) begin
        grp_fu_567_p0 = z4_q0;
    end else if ((1'b1 == ap_CS_fsm_state42)) begin
        grp_fu_567_p0 = acc_0_i17_reg_438;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        grp_fu_567_p0 = acc_0_i6_reg_405;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_567_p0 = acc_0_i_reg_372;
    end else begin
        grp_fu_567_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state78)) begin
        grp_fu_567_p1 = maxv_0_reg_504;
    end else if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_567_p1 = 32'd0;
    end else begin
        grp_fu_567_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_r_ce0 = 1'b1;
    end else begin
        input_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state129)) begin
        output_r_address0 = output_addr_1_reg_1444;
    end else if ((1'b1 == ap_CS_fsm_state111)) begin
        output_r_address0 = zext_ln117_fu_1133_p1;
    end else if ((1'b1 == ap_CS_fsm_state103)) begin
        output_r_address0 = zext_ln110_reg_1415;
    end else begin
        output_r_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state103) | (1'b1 == ap_CS_fsm_state129) | (1'b1 == ap_CS_fsm_state111))) begin
        output_r_ce0 = 1'b1;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state129)) begin
        output_r_d0 = tmp_9_reg_1454;
    end else if ((1'b1 == ap_CS_fsm_state103)) begin
        output_r_d0 = e_reg_1425;
    end else begin
        output_r_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state103) | (1'b1 == ap_CS_fsm_state129))) begin
        output_r_we0 = 1'b1;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state80)) begin
        z4_address0 = zext_ln110_fu_1116_p1;
    end else if ((1'b1 == ap_CS_fsm_state77)) begin
        z4_address0 = zext_ln104_fu_1003_p1;
    end else if ((1'b1 == ap_CS_fsm_state61)) begin
        z4_address0 = zext_ln99_reg_1329;
    end else if ((1'b1 == ap_CS_fsm_state59)) begin
        z4_address0 = 64'd0;
    end else begin
        z4_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state80) | (1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state61) | (1'b1 == ap_CS_fsm_state59))) begin
        z4_ce0 = 1'b1;
    end else begin
        z4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln68_3_fu_966_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state61))) begin
        z4_we0 = 1'b1;
    end else begin
        z4_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln86_fu_608_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln68_fu_625_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state21 : begin
            if (((icmp_ln90_fu_707_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state40;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            if (((icmp_ln68_1_fu_746_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state40 : begin
            if (((icmp_ln94_fu_827_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state40))) begin
                ap_NS_fsm = ap_ST_fsm_state59;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state41;
            end
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            if (((icmp_ln68_2_fu_856_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state42))) begin
                ap_NS_fsm = ap_ST_fsm_state57;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state43;
            end
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state59 : begin
            if (((icmp_ln98_fu_937_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state59))) begin
                ap_NS_fsm = ap_ST_fsm_state76;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state60;
            end
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            if (((icmp_ln68_3_fu_966_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state61))) begin
                ap_NS_fsm = ap_ST_fsm_state59;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state62;
            end
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            if (((icmp_ln103_fu_997_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state77))) begin
                ap_NS_fsm = ap_ST_fsm_state80;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state78;
            end
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state79;
        end
        ap_ST_fsm_state79 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state80 : begin
            if (((icmp_ln109_fu_1104_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state80))) begin
                ap_NS_fsm = ap_ST_fsm_state111;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state81;
            end
        end
        ap_ST_fsm_state81 : begin
            ap_NS_fsm = ap_ST_fsm_state82;
        end
        ap_ST_fsm_state82 : begin
            ap_NS_fsm = ap_ST_fsm_state83;
        end
        ap_ST_fsm_state83 : begin
            ap_NS_fsm = ap_ST_fsm_state84;
        end
        ap_ST_fsm_state84 : begin
            ap_NS_fsm = ap_ST_fsm_state85;
        end
        ap_ST_fsm_state85 : begin
            ap_NS_fsm = ap_ST_fsm_state86;
        end
        ap_ST_fsm_state86 : begin
            ap_NS_fsm = ap_ST_fsm_state87;
        end
        ap_ST_fsm_state87 : begin
            ap_NS_fsm = ap_ST_fsm_state88;
        end
        ap_ST_fsm_state88 : begin
            ap_NS_fsm = ap_ST_fsm_state89;
        end
        ap_ST_fsm_state89 : begin
            ap_NS_fsm = ap_ST_fsm_state90;
        end
        ap_ST_fsm_state90 : begin
            ap_NS_fsm = ap_ST_fsm_state91;
        end
        ap_ST_fsm_state91 : begin
            ap_NS_fsm = ap_ST_fsm_state92;
        end
        ap_ST_fsm_state92 : begin
            ap_NS_fsm = ap_ST_fsm_state93;
        end
        ap_ST_fsm_state93 : begin
            ap_NS_fsm = ap_ST_fsm_state94;
        end
        ap_ST_fsm_state94 : begin
            ap_NS_fsm = ap_ST_fsm_state95;
        end
        ap_ST_fsm_state95 : begin
            ap_NS_fsm = ap_ST_fsm_state96;
        end
        ap_ST_fsm_state96 : begin
            ap_NS_fsm = ap_ST_fsm_state97;
        end
        ap_ST_fsm_state97 : begin
            ap_NS_fsm = ap_ST_fsm_state98;
        end
        ap_ST_fsm_state98 : begin
            ap_NS_fsm = ap_ST_fsm_state99;
        end
        ap_ST_fsm_state99 : begin
            ap_NS_fsm = ap_ST_fsm_state100;
        end
        ap_ST_fsm_state100 : begin
            ap_NS_fsm = ap_ST_fsm_state101;
        end
        ap_ST_fsm_state101 : begin
            ap_NS_fsm = ap_ST_fsm_state102;
        end
        ap_ST_fsm_state102 : begin
            ap_NS_fsm = ap_ST_fsm_state103;
        end
        ap_ST_fsm_state103 : begin
            ap_NS_fsm = ap_ST_fsm_state104;
        end
        ap_ST_fsm_state104 : begin
            ap_NS_fsm = ap_ST_fsm_state105;
        end
        ap_ST_fsm_state105 : begin
            ap_NS_fsm = ap_ST_fsm_state106;
        end
        ap_ST_fsm_state106 : begin
            ap_NS_fsm = ap_ST_fsm_state107;
        end
        ap_ST_fsm_state107 : begin
            ap_NS_fsm = ap_ST_fsm_state108;
        end
        ap_ST_fsm_state108 : begin
            ap_NS_fsm = ap_ST_fsm_state109;
        end
        ap_ST_fsm_state109 : begin
            ap_NS_fsm = ap_ST_fsm_state110;
        end
        ap_ST_fsm_state110 : begin
            ap_NS_fsm = ap_ST_fsm_state80;
        end
        ap_ST_fsm_state111 : begin
            if (((icmp_ln116_fu_1121_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state111))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state112;
            end
        end
        ap_ST_fsm_state112 : begin
            ap_NS_fsm = ap_ST_fsm_state113;
        end
        ap_ST_fsm_state113 : begin
            ap_NS_fsm = ap_ST_fsm_state114;
        end
        ap_ST_fsm_state114 : begin
            ap_NS_fsm = ap_ST_fsm_state115;
        end
        ap_ST_fsm_state115 : begin
            ap_NS_fsm = ap_ST_fsm_state116;
        end
        ap_ST_fsm_state116 : begin
            ap_NS_fsm = ap_ST_fsm_state117;
        end
        ap_ST_fsm_state117 : begin
            ap_NS_fsm = ap_ST_fsm_state118;
        end
        ap_ST_fsm_state118 : begin
            ap_NS_fsm = ap_ST_fsm_state119;
        end
        ap_ST_fsm_state119 : begin
            ap_NS_fsm = ap_ST_fsm_state120;
        end
        ap_ST_fsm_state120 : begin
            ap_NS_fsm = ap_ST_fsm_state121;
        end
        ap_ST_fsm_state121 : begin
            ap_NS_fsm = ap_ST_fsm_state122;
        end
        ap_ST_fsm_state122 : begin
            ap_NS_fsm = ap_ST_fsm_state123;
        end
        ap_ST_fsm_state123 : begin
            ap_NS_fsm = ap_ST_fsm_state124;
        end
        ap_ST_fsm_state124 : begin
            ap_NS_fsm = ap_ST_fsm_state125;
        end
        ap_ST_fsm_state125 : begin
            ap_NS_fsm = ap_ST_fsm_state126;
        end
        ap_ST_fsm_state126 : begin
            ap_NS_fsm = ap_ST_fsm_state127;
        end
        ap_ST_fsm_state127 : begin
            ap_NS_fsm = ap_ST_fsm_state128;
        end
        ap_ST_fsm_state128 : begin
            ap_NS_fsm = ap_ST_fsm_state129;
        end
        ap_ST_fsm_state129 : begin
            ap_NS_fsm = ap_ST_fsm_state111;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B1_address0 = zext_ln87_fu_620_p1;

assign B2_address0 = zext_ln91_fu_719_p1;

assign B3_address0 = zext_ln95_fu_839_p1;

assign B4_address0 = zext_ln99_fu_949_p1;

assign W1_address0 = zext_ln69_7_fu_652_p1;

assign W2_address0 = zext_ln69_9_fu_772_p1;

assign W3_address0 = zext_ln69_11_fu_882_p1;

assign W4_address0 = zext_ln69_13_fu_992_p1;

assign a1_d0 = ((and_ln72_fu_693_p2[0:0] === 1'b1) ? 32'd0 : acc_0_i_reg_372);

assign a2_d0 = ((and_ln72_1_fu_813_p2[0:0] === 1'b1) ? 32'd0 : acc_0_i6_reg_405);

assign a3_d0 = ((and_ln72_2_fu_923_p2[0:0] === 1'b1) ? 32'd0 : acc_0_i17_reg_438);

assign add_ln69_1_fu_646_p2 = (phi_mul_reg_360 + zext_ln69_6_fu_642_p1);

assign add_ln69_2_fu_767_p2 = (add_ln69_reg_1217 + zext_ln69_8_fu_763_p1);

assign add_ln69_3_fu_877_p2 = (zext_ln95_1_reg_1278 + zext_ln69_10_fu_873_p1);

assign add_ln69_4_fu_987_p2 = (zext_ln99_1_reg_1344 + zext_ln69_12_fu_983_p1);

assign add_ln69_fu_740_p2 = (zext_ln69_4_fu_724_p1 + zext_ln69_5_fu_736_p1);

assign add_ln86_fu_602_p2 = (phi_mul_reg_360 + 12'd784);

assign and_ln104_1_fu_1091_p2 = (grp_fu_567_p2 & and_ln104_fu_1085_p2);

assign and_ln104_fu_1085_p2 = (or_ln104_fu_1061_p2 & or_ln104_1_fu_1079_p2);

assign and_ln72_1_fu_813_p2 = (tmp_3_reg_1255 & or_ln72_1_fu_807_p2);

assign and_ln72_2_fu_923_p2 = (tmp_5_reg_1316 & or_ln72_2_fu_917_p2);

assign and_ln72_fu_693_p2 = (tmp_1_reg_1194 & or_ln72_fu_687_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state102 = ap_CS_fsm[32'd101];

assign ap_CS_fsm_state103 = ap_CS_fsm[32'd102];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state110 = ap_CS_fsm[32'd109];

assign ap_CS_fsm_state111 = ap_CS_fsm[32'd110];

assign ap_CS_fsm_state112 = ap_CS_fsm[32'd111];

assign ap_CS_fsm_state113 = ap_CS_fsm[32'd112];

assign ap_CS_fsm_state128 = ap_CS_fsm[32'd127];

assign ap_CS_fsm_state129 = ap_CS_fsm[32'd128];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state48 = ap_CS_fsm[32'd47];

assign ap_CS_fsm_state49 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state56 = ap_CS_fsm[32'd55];

assign ap_CS_fsm_state57 = ap_CS_fsm[32'd56];

assign ap_CS_fsm_state58 = ap_CS_fsm[32'd57];

assign ap_CS_fsm_state59 = ap_CS_fsm[32'd58];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state60 = ap_CS_fsm[32'd59];

assign ap_CS_fsm_state61 = ap_CS_fsm[32'd60];

assign ap_CS_fsm_state62 = ap_CS_fsm[32'd61];

assign ap_CS_fsm_state63 = ap_CS_fsm[32'd62];

assign ap_CS_fsm_state67 = ap_CS_fsm[32'd66];

assign ap_CS_fsm_state68 = ap_CS_fsm[32'd67];

assign ap_CS_fsm_state75 = ap_CS_fsm[32'd74];

assign ap_CS_fsm_state76 = ap_CS_fsm[32'd75];

assign ap_CS_fsm_state77 = ap_CS_fsm[32'd76];

assign ap_CS_fsm_state78 = ap_CS_fsm[32'd77];

assign ap_CS_fsm_state79 = ap_CS_fsm[32'd78];

assign ap_CS_fsm_state80 = ap_CS_fsm[32'd79];

assign ap_CS_fsm_state81 = ap_CS_fsm[32'd80];

assign ap_CS_fsm_state82 = ap_CS_fsm[32'd81];

assign ap_CS_fsm_state89 = ap_CS_fsm[32'd88];

assign ap_CS_fsm_state90 = ap_CS_fsm[32'd89];

assign bitcast_ln104_1_fu_1031_p1 = maxv_0_reg_504;

assign bitcast_ln104_fu_1014_p1 = maxv_1_reg_1395;

assign bitcast_ln72_1_fu_777_p1 = acc_0_i6_reg_405;

assign bitcast_ln72_2_fu_887_p1 = acc_0_i17_reg_438;

assign bitcast_ln72_fu_657_p1 = acc_0_i_reg_372;

assign i_1_fu_752_p2 = (i_0_i7_reg_415 + 3'd1);

assign i_2_fu_862_p2 = (i_0_i18_reg_448 + 4'd1);

assign i_3_fu_972_p2 = (i_0_i29_reg_482 + 4'd1);

assign i_fu_631_p2 = (i_0_i_reg_382 + 10'd1);

assign icmp_ln103_fu_997_p2 = ((j4_0_reg_493 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln104_1_fu_1055_p2 = ((trunc_ln104_fu_1027_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln104_2_fu_1067_p2 = ((tmp_8_fu_1035_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln104_3_fu_1073_p2 = ((trunc_ln104_1_fu_1045_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln104_fu_1049_p2 = ((tmp_6_fu_1017_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln109_fu_1104_p2 = ((j5_0_reg_526 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln116_fu_1121_p2 = ((j6_0_reg_537 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln68_1_fu_746_p2 = ((i_0_i7_reg_415 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln68_2_fu_856_p2 = ((i_0_i18_reg_448 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln68_3_fu_966_p2 = ((i_0_i29_reg_482 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln68_fu_625_p2 = ((i_0_i_reg_382 == 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln72_1_fu_681_p2 = ((trunc_ln72_fu_671_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln72_2_fu_795_p2 = ((tmp_2_fu_781_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln72_3_fu_801_p2 = ((trunc_ln72_1_fu_791_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln72_4_fu_905_p2 = ((tmp_4_fu_891_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln72_5_fu_911_p2 = ((trunc_ln72_2_fu_901_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln72_fu_675_p2 = ((tmp_fu_661_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_608_p2 = ((j_0_reg_349 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln90_fu_707_p2 = ((j1_0_reg_393 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln94_fu_827_p2 = ((j2_0_reg_426 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln98_fu_937_p2 = ((j3_0_reg_459 == 4'd10) ? 1'b1 : 1'b0);

assign input_r_address0 = zext_ln69_fu_637_p1;

assign j_1_fu_713_p2 = (j1_0_reg_393 + 4'd1);

assign j_2_fu_833_p2 = (j2_0_reg_426 + 4'd1);

assign j_3_fu_1008_p2 = (4'd1 + j4_0_reg_493);

assign j_4_fu_943_p2 = (j3_0_reg_459 + 4'd1);

assign j_5_fu_1110_p2 = (j5_0_reg_526 + 4'd1);

assign j_6_fu_1127_p2 = (j6_0_reg_537 + 4'd1);

assign j_fu_614_p2 = (j_0_reg_349 + 3'd1);

assign maxv_2_fu_1097_p3 = ((and_ln104_1_fu_1091_p2[0:0] === 1'b1) ? maxv_1_reg_1395 : maxv_0_reg_504);

assign or_ln104_1_fu_1079_p2 = (icmp_ln104_3_fu_1073_p2 | icmp_ln104_2_fu_1067_p2);

assign or_ln104_fu_1061_p2 = (icmp_ln104_fu_1049_p2 | icmp_ln104_1_fu_1055_p2);

assign or_ln72_1_fu_807_p2 = (icmp_ln72_3_fu_801_p2 | icmp_ln72_2_fu_795_p2);

assign or_ln72_2_fu_917_p2 = (icmp_ln72_5_fu_911_p2 | icmp_ln72_4_fu_905_p2);

assign or_ln72_fu_687_p2 = (icmp_ln72_fu_675_p2 | icmp_ln72_1_fu_681_p2);

assign tmp_10_fu_728_p3 = {{j1_0_reg_393}, {2'd0}};

assign tmp_11_fu_844_p3 = {{j2_0_reg_426}, {3'd0}};

assign tmp_12_fu_954_p3 = {{j3_0_reg_459}, {3'd0}};

assign tmp_2_fu_781_p4 = {{bitcast_ln72_1_fu_777_p1[30:23]}};

assign tmp_4_fu_891_p4 = {{bitcast_ln72_2_fu_887_p1[30:23]}};

assign tmp_6_fu_1017_p4 = {{bitcast_ln104_fu_1014_p1[30:23]}};

assign tmp_8_fu_1035_p4 = {{bitcast_ln104_1_fu_1031_p1[30:23]}};

assign tmp_fu_661_p4 = {{bitcast_ln72_fu_657_p1[30:23]}};

assign trunc_ln104_1_fu_1045_p1 = bitcast_ln104_1_fu_1031_p1[22:0];

assign trunc_ln104_fu_1027_p1 = bitcast_ln104_fu_1014_p1[22:0];

assign trunc_ln72_1_fu_791_p1 = bitcast_ln72_1_fu_777_p1[22:0];

assign trunc_ln72_2_fu_901_p1 = bitcast_ln72_2_fu_887_p1[22:0];

assign trunc_ln72_fu_671_p1 = bitcast_ln72_fu_657_p1[22:0];

assign zext_ln104_fu_1003_p1 = j4_0_reg_493;

assign zext_ln110_fu_1116_p1 = j5_0_reg_526;

assign zext_ln117_fu_1133_p1 = j6_0_reg_537;

assign zext_ln69_10_fu_873_p1 = i_0_i18_reg_448;

assign zext_ln69_11_fu_882_p1 = add_ln69_3_fu_877_p2;

assign zext_ln69_12_fu_983_p1 = i_0_i29_reg_482;

assign zext_ln69_13_fu_992_p1 = add_ln69_4_fu_987_p2;

assign zext_ln69_1_fu_758_p1 = i_0_i7_reg_415;

assign zext_ln69_2_fu_868_p1 = i_0_i18_reg_448;

assign zext_ln69_3_fu_978_p1 = i_0_i29_reg_482;

assign zext_ln69_4_fu_724_p1 = j1_0_reg_393;

assign zext_ln69_5_fu_736_p1 = tmp_10_fu_728_p3;

assign zext_ln69_6_fu_642_p1 = i_0_i_reg_382;

assign zext_ln69_7_fu_652_p1 = add_ln69_1_fu_646_p2;

assign zext_ln69_8_fu_763_p1 = i_0_i7_reg_415;

assign zext_ln69_9_fu_772_p1 = add_ln69_2_fu_767_p2;

assign zext_ln69_fu_637_p1 = i_0_i_reg_382;

assign zext_ln87_fu_620_p1 = j_0_reg_349;

assign zext_ln91_fu_719_p1 = j1_0_reg_393;

assign zext_ln95_1_fu_852_p1 = tmp_11_fu_844_p3;

assign zext_ln95_fu_839_p1 = j2_0_reg_426;

assign zext_ln99_1_fu_962_p1 = tmp_12_fu_954_p3;

assign zext_ln99_fu_949_p1 = j3_0_reg_459;

always @ (posedge ap_clk) begin
    zext_ln87_reg_1151[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln91_reg_1207[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln95_reg_1268[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln95_1_reg_1278[2:0] <= 3'b000;
    zext_ln95_1_reg_1278[7] <= 1'b0;
    zext_ln99_reg_1329[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln99_1_reg_1344[2:0] <= 3'b000;
    zext_ln99_1_reg_1344[7] <= 1'b0;
    zext_ln110_reg_1415[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //mlp
