// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mlp,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu3eg-sbva484-1-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.507000,HLS_SYN_LAT=8645,HLS_SYN_TPT=none,HLS_SYN_MEM=3,HLS_SYN_DSP=13,HLS_SYN_FF=2129,HLS_SYN_LUT=5673,HLS_VERSION=2019_1}" *)

module mlp (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_V_address0,
        input_V_ce0,
        input_V_q0,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0,
        output_r_q0
);

parameter    ap_ST_fsm_state1 = 53'd1;
parameter    ap_ST_fsm_state2 = 53'd2;
parameter    ap_ST_fsm_state3 = 53'd4;
parameter    ap_ST_fsm_state4 = 53'd8;
parameter    ap_ST_fsm_state5 = 53'd16;
parameter    ap_ST_fsm_state6 = 53'd32;
parameter    ap_ST_fsm_state7 = 53'd64;
parameter    ap_ST_fsm_state8 = 53'd128;
parameter    ap_ST_fsm_state9 = 53'd256;
parameter    ap_ST_fsm_state10 = 53'd512;
parameter    ap_ST_fsm_state11 = 53'd1024;
parameter    ap_ST_fsm_state12 = 53'd2048;
parameter    ap_ST_fsm_state13 = 53'd4096;
parameter    ap_ST_fsm_state14 = 53'd8192;
parameter    ap_ST_fsm_state15 = 53'd16384;
parameter    ap_ST_fsm_state16 = 53'd32768;
parameter    ap_ST_fsm_state17 = 53'd65536;
parameter    ap_ST_fsm_state18 = 53'd131072;
parameter    ap_ST_fsm_state19 = 53'd262144;
parameter    ap_ST_fsm_state20 = 53'd524288;
parameter    ap_ST_fsm_state21 = 53'd1048576;
parameter    ap_ST_fsm_state22 = 53'd2097152;
parameter    ap_ST_fsm_state23 = 53'd4194304;
parameter    ap_ST_fsm_state24 = 53'd8388608;
parameter    ap_ST_fsm_state25 = 53'd16777216;
parameter    ap_ST_fsm_state26 = 53'd33554432;
parameter    ap_ST_fsm_state27 = 53'd67108864;
parameter    ap_ST_fsm_state28 = 53'd134217728;
parameter    ap_ST_fsm_state29 = 53'd268435456;
parameter    ap_ST_fsm_state30 = 53'd536870912;
parameter    ap_ST_fsm_state31 = 53'd1073741824;
parameter    ap_ST_fsm_state32 = 53'd2147483648;
parameter    ap_ST_fsm_state33 = 53'd4294967296;
parameter    ap_ST_fsm_state34 = 53'd8589934592;
parameter    ap_ST_fsm_state35 = 53'd17179869184;
parameter    ap_ST_fsm_state36 = 53'd34359738368;
parameter    ap_ST_fsm_state37 = 53'd68719476736;
parameter    ap_ST_fsm_state38 = 53'd137438953472;
parameter    ap_ST_fsm_state39 = 53'd274877906944;
parameter    ap_ST_fsm_state40 = 53'd549755813888;
parameter    ap_ST_fsm_state41 = 53'd1099511627776;
parameter    ap_ST_fsm_state42 = 53'd2199023255552;
parameter    ap_ST_fsm_state43 = 53'd4398046511104;
parameter    ap_ST_fsm_state44 = 53'd8796093022208;
parameter    ap_ST_fsm_state45 = 53'd17592186044416;
parameter    ap_ST_fsm_state46 = 53'd35184372088832;
parameter    ap_ST_fsm_state47 = 53'd70368744177664;
parameter    ap_ST_fsm_state48 = 53'd140737488355328;
parameter    ap_ST_fsm_state49 = 53'd281474976710656;
parameter    ap_ST_fsm_state50 = 53'd562949953421312;
parameter    ap_ST_fsm_state51 = 53'd1125899906842624;
parameter    ap_ST_fsm_state52 = 53'd2251799813685248;
parameter    ap_ST_fsm_state53 = 53'd4503599627370496;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] input_V_address0;
output   input_V_ce0;
input  [15:0] input_V_q0;
output  [3:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [31:0] output_r_d0;
input  [31:0] output_r_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_V_ce0;
reg[3:0] output_r_address0;
reg output_r_ce0;
reg output_r_we0;
reg[31:0] output_r_d0;

(* fsm_encoding = "none" *) reg   [52:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] B1_V_address0;
reg    B1_V_ce0;
wire   [8:0] B1_V_q0;
wire   [11:0] W1_V_address0;
reg    W1_V_ce0;
wire  signed [11:0] W1_V_q0;
wire   [2:0] B2_V_address0;
reg    B2_V_ce0;
wire   [10:0] B2_V_q0;
wire   [5:0] W2_V_address0;
reg    W2_V_ce0;
wire  signed [11:0] W2_V_q0;
wire   [2:0] B3_V_address0;
reg    B3_V_ce0;
wire   [11:0] B3_V_q0;
wire   [5:0] W3_V_address0;
reg    W3_V_ce0;
wire  signed [10:0] W3_V_q0;
wire   [3:0] B4_V_address0;
reg    B4_V_ce0;
wire   [11:0] B4_V_q0;
wire   [6:0] W4_V_address0;
reg    W4_V_ce0;
wire  signed [11:0] W4_V_q0;
wire   [15:0] grp_fu_703_p3;
reg   [15:0] reg_721;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state21;
wire   [0:0] grp_fu_683_p2;
wire   [11:0] add_ln88_fu_725_p2;
reg   [11:0] add_ln88_reg_2178;
wire    ap_CS_fsm_state2;
wire   [2:0] j_fu_737_p2;
reg   [2:0] j_reg_2186;
wire   [63:0] zext_ln89_fu_743_p1;
reg   [63:0] zext_ln89_reg_2191;
wire   [0:0] icmp_ln88_fu_731_p2;
wire   [15:0] zext_ln89_1_fu_748_p1;
wire    ap_CS_fsm_state3;
wire   [9:0] i_fu_758_p2;
reg   [9:0] i_reg_2209;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln68_fu_752_p2;
wire    ap_CS_fsm_state5;
wire   [3:0] j_1_fu_836_p2;
reg   [3:0] j_1_reg_2232;
wire    ap_CS_fsm_state6;
wire   [63:0] zext_ln94_fu_842_p1;
reg   [63:0] zext_ln94_reg_2237;
wire   [0:0] icmp_ln93_fu_830_p2;
wire   [6:0] add_ln1117_fu_863_p2;
reg   [6:0] add_ln1117_reg_2247;
wire    ap_CS_fsm_state7;
wire  signed [15:0] sext_ln94_fu_869_p1;
wire   [2:0] i_1_fu_879_p2;
reg   [2:0] i_1_reg_2260;
wire    ap_CS_fsm_state8;
wire   [0:0] icmp_ln68_1_fu_873_p2;
wire    ap_CS_fsm_state9;
wire   [3:0] j_2_fu_956_p2;
reg   [3:0] j_2_reg_2283;
wire    ap_CS_fsm_state10;
wire   [63:0] zext_ln99_fu_962_p1;
reg   [63:0] zext_ln99_reg_2288;
wire   [0:0] icmp_ln98_fu_950_p2;
wire   [7:0] zext_ln99_1_fu_975_p1;
reg   [7:0] zext_ln99_1_reg_2298;
wire    ap_CS_fsm_state11;
wire  signed [15:0] sext_ln99_fu_979_p1;
wire   [3:0] i_2_fu_989_p2;
reg   [3:0] i_2_reg_2311;
wire    ap_CS_fsm_state12;
wire   [0:0] icmp_ln68_2_fu_983_p2;
wire    ap_CS_fsm_state13;
wire   [3:0] j_3_fu_1066_p2;
reg   [3:0] j_3_reg_2334;
wire    ap_CS_fsm_state14;
wire   [63:0] zext_ln104_fu_1072_p1;
reg   [63:0] zext_ln104_reg_2339;
wire   [0:0] icmp_ln103_fu_1060_p2;
wire   [7:0] zext_ln104_1_fu_1085_p1;
reg   [7:0] zext_ln104_1_reg_2354;
wire    ap_CS_fsm_state15;
wire  signed [15:0] sext_ln104_fu_1089_p1;
wire   [3:0] i_3_fu_1099_p2;
reg   [3:0] i_3_reg_2367;
wire    ap_CS_fsm_state16;
wire   [0:0] icmp_ln68_3_fu_1093_p2;
wire    ap_CS_fsm_state17;
reg   [0:0] icmp_ln935_reg_2387;
wire   [0:0] grp_fu_689_p3;
reg   [0:0] p_Result_21_reg_2392;
wire   [31:0] sub_ln944_fu_1165_p2;
reg   [31:0] sub_ln944_reg_2397;
wire   [31:0] or_ln_fu_1275_p3;
reg   [31:0] or_ln_reg_2403;
wire   [0:0] icmp_ln958_fu_1283_p2;
reg   [0:0] icmp_ln958_reg_2408;
wire   [7:0] trunc_ln943_fu_1289_p1;
reg   [7:0] trunc_ln943_reg_2413;
wire   [31:0] select_ln935_fu_1415_p3;
reg   [31:0] select_ln935_reg_2418;
wire    ap_CS_fsm_state19;
wire   [63:0] zext_ln110_fu_1428_p1;
reg   [63:0] zext_ln110_reg_2427;
wire    ap_CS_fsm_state20;
wire   [0:0] icmp_ln109_fu_1422_p2;
wire   [15:0] z4_V_q0;
reg   [15:0] tmp_V_11_reg_2438;
reg   [0:0] icmp_ln935_1_reg_2445;
reg   [0:0] p_Result_24_reg_2450;
wire   [31:0] sub_ln944_1_fu_1449_p2;
reg   [31:0] sub_ln944_1_reg_2455;
wire   [31:0] or_ln949_2_fu_1559_p3;
reg   [31:0] or_ln949_2_reg_2461;
wire   [0:0] icmp_ln958_1_fu_1567_p2;
reg   [0:0] icmp_ln958_1_reg_2466;
wire   [7:0] trunc_ln943_1_fu_1573_p1;
reg   [7:0] trunc_ln943_1_reg_2471;
wire   [31:0] bitcast_ln739_1_fu_1695_p1;
wire    ap_CS_fsm_state22;
wire   [3:0] j_5_fu_1700_p2;
reg   [3:0] j_5_reg_2481;
wire   [0:0] icmp_ln111_fu_1724_p2;
reg   [0:0] icmp_ln111_reg_2486;
wire    ap_CS_fsm_state23;
wire   [0:0] icmp_ln111_1_fu_1730_p2;
reg   [0:0] icmp_ln111_1_reg_2491;
wire   [0:0] p_Result_27_fu_1736_p3;
reg   [0:0] p_Result_27_reg_2496;
wire   [15:0] tmp_V_13_fu_1748_p3;
reg   [15:0] tmp_V_13_reg_2501;
wire   [31:0] sub_ln944_2_fu_1781_p2;
reg   [31:0] sub_ln944_2_reg_2507;
wire   [31:0] or_ln949_4_fu_1891_p3;
reg   [31:0] or_ln949_4_reg_2513;
wire   [0:0] icmp_ln958_2_fu_1899_p2;
reg   [0:0] icmp_ln958_2_reg_2518;
wire   [7:0] trunc_ln943_2_fu_1905_p1;
reg   [7:0] trunc_ln943_2_reg_2523;
wire   [31:0] select_ln111_1_fu_2100_p3;
wire    ap_CS_fsm_state24;
wire   [3:0] j_4_fu_2114_p2;
reg   [3:0] j_4_reg_2536;
wire    ap_CS_fsm_state25;
wire   [63:0] zext_ln119_fu_2120_p1;
reg   [63:0] zext_ln119_reg_2541;
wire   [0:0] icmp_ln118_fu_2108_p2;
wire   [31:0] logits_q0;
wire    ap_CS_fsm_state26;
wire   [31:0] grp_fu_659_p2;
reg   [31:0] tmp_reg_2556;
wire    ap_CS_fsm_state29;
wire   [31:0] grp_fu_677_p2;
reg   [31:0] e_reg_2561;
wire    ap_CS_fsm_state37;
wire    ap_CS_fsm_state41;
wire   [3:0] j_6_fu_2131_p2;
reg   [3:0] j_6_reg_2574;
wire    ap_CS_fsm_state42;
reg   [3:0] output_addr_1_reg_2579;
wire   [0:0] icmp_ln124_fu_2125_p2;
reg   [31:0] output_load_reg_2584;
wire    ap_CS_fsm_state43;
wire   [31:0] grp_fu_666_p2;
reg   [31:0] tmp_2_reg_2589;
wire    ap_CS_fsm_state52;
reg   [2:0] a1_V_address0;
reg    a1_V_ce0;
reg    a1_V_we0;
wire   [14:0] a1_V_d0;
wire   [14:0] a1_V_q0;
reg   [2:0] a2_V_address0;
reg    a2_V_ce0;
reg    a2_V_we0;
wire   [14:0] a2_V_d0;
wire   [14:0] a2_V_q0;
reg   [2:0] a3_V_address0;
reg    a3_V_ce0;
reg    a3_V_we0;
wire   [14:0] a3_V_d0;
wire   [14:0] a3_V_q0;
reg   [3:0] z4_V_address0;
reg    z4_V_ce0;
reg    z4_V_we0;
reg   [3:0] logits_address0;
reg    logits_ce0;
reg    logits_we0;
reg   [31:0] logits_d0;
reg   [2:0] j_0_reg_447;
reg   [11:0] phi_mul_reg_458;
reg   [15:0] p_Val2_1_reg_470;
reg   [9:0] i_0_i_reg_480;
reg   [3:0] j4_0_reg_491;
reg   [15:0] p_Val2_4_reg_503;
reg   [2:0] i_0_i10_reg_513;
reg   [3:0] j5_0_reg_524;
reg   [15:0] p_Val2_9_reg_536;
reg   [3:0] i_0_i26_reg_546;
reg   [3:0] j6_0_reg_557;
reg   [15:0] p_Val2_14_reg_569;
reg   [3:0] i_0_i42_reg_580;
reg   [31:0] maxv_0_reg_591;
reg   [3:0] j7_0_reg_601;
reg   [31:0] p_0202_reg_613;
reg   [31:0] sum_0_reg_625;
reg   [3:0] j8_0_reg_637;
reg   [3:0] j9_0_reg_648;
wire    ap_CS_fsm_state53;
wire   [63:0] zext_ln1117_3_fu_779_p1;
wire   [63:0] zext_ln69_fu_764_p1;
wire   [63:0] zext_ln1117_5_fu_899_p1;
wire   [63:0] zext_ln69_1_fu_885_p1;
wire   [63:0] zext_ln1117_7_fu_1009_p1;
wire   [63:0] zext_ln69_2_fu_995_p1;
wire   [63:0] zext_ln1117_9_fu_1119_p1;
wire   [63:0] zext_ln69_3_fu_1105_p1;
wire   [3:0] logits_addr_1_gep_fu_412_p3;
wire   [63:0] zext_ln125_fu_2137_p1;
reg   [31:0] grp_fu_659_p0;
reg   [31:0] grp_fu_659_p1;
wire    ap_CS_fsm_state38;
wire    ap_CS_fsm_state44;
wire    ap_CS_fsm_state30;
wire   [15:0] grp_fu_697_p2;
wire   [11:0] zext_ln1117_2_fu_769_p1;
wire   [11:0] add_ln1117_1_fu_773_p2;
wire   [0:0] tmp_10_fu_788_p3;
wire   [14:0] empty_16_fu_784_p1;
wire  signed [25:0] grp_fu_2142_p3;
wire   [5:0] tmp_7_fu_851_p3;
wire   [6:0] zext_ln1117_fu_847_p1;
wire   [6:0] zext_ln1117_1_fu_859_p1;
wire   [6:0] zext_ln1117_4_fu_890_p1;
wire   [6:0] add_ln1117_2_fu_894_p2;
wire   [0:0] tmp_11_fu_908_p3;
wire   [14:0] empty_19_fu_904_p1;
wire  signed [25:0] grp_fu_2151_p3;
wire   [6:0] tmp_8_fu_967_p3;
wire   [7:0] zext_ln1117_6_fu_1000_p1;
wire   [7:0] add_ln1117_3_fu_1004_p2;
wire   [0:0] tmp_16_fu_1018_p3;
wire   [14:0] empty_22_fu_1014_p1;
wire  signed [25:0] grp_fu_2160_p3;
wire   [6:0] tmp_9_fu_1077_p3;
wire   [7:0] zext_ln1117_8_fu_1110_p1;
wire   [7:0] add_ln1117_4_fu_1114_p2;
wire  signed [25:0] grp_fu_2169_p3;
reg   [15:0] grp_fu_711_p4;
wire   [31:0] p_Result_22_fu_1149_p3;
reg   [31:0] l_fu_1157_p3;
wire   [31:0] lsb_index_fu_1175_p2;
wire   [30:0] tmp_13_fu_1181_p4;
wire   [4:0] trunc_ln947_fu_1197_p1;
wire   [4:0] sub_ln947_fu_1201_p2;
wire   [15:0] zext_ln947_fu_1207_p1;
wire   [15:0] lshr_ln947_fu_1211_p2;
wire   [15:0] p_Result_4_fu_1217_p2;
wire   [0:0] icmp_ln947_fu_1191_p2;
wire   [0:0] icmp_ln947_1_fu_1223_p2;
wire   [0:0] tmp_14_fu_1235_p3;
wire   [15:0] trunc_ln944_fu_1171_p1;
wire   [15:0] add_ln949_fu_1249_p2;
wire   [0:0] p_Result_3_fu_1255_p3;
wire   [0:0] xor_ln949_fu_1243_p2;
wire   [0:0] and_ln949_fu_1263_p2;
wire   [0:0] a_fu_1229_p2;
wire   [0:0] or_ln949_fu_1269_p2;
wire   [31:0] zext_ln957_1_fu_1297_p1;
wire   [31:0] add_ln958_fu_1301_p2;
wire   [31:0] lshr_ln958_fu_1306_p2;
wire   [31:0] sub_ln958_fu_1316_p2;
wire   [63:0] m_fu_1293_p1;
wire   [63:0] zext_ln958_1_fu_1321_p1;
wire   [63:0] zext_ln958_fu_1312_p1;
wire   [63:0] shl_ln958_fu_1325_p2;
wire   [63:0] m_1_fu_1331_p3;
wire   [63:0] zext_ln961_fu_1338_p1;
wire   [63:0] m_2_fu_1341_p2;
wire   [62:0] m_s_fu_1347_p4;
wire   [0:0] tmp_15_fu_1361_p3;
wire   [7:0] select_ln964_fu_1369_p3;
wire   [7:0] sub_ln964_fu_1377_p2;
wire   [7:0] add_ln964_fu_1382_p2;
wire   [63:0] m_26_fu_1357_p1;
wire   [8:0] tmp_s_fu_1388_p3;
wire   [63:0] p_Result_23_fu_1395_p5;
wire   [31:0] trunc_ln738_fu_1407_p1;
wire   [31:0] bitcast_ln739_fu_1411_p1;
wire   [31:0] p_Result_25_fu_1433_p3;
reg   [31:0] l_1_fu_1441_p3;
wire   [31:0] lsb_index_1_fu_1459_p2;
wire   [30:0] tmp_18_fu_1465_p4;
wire   [4:0] trunc_ln947_1_fu_1481_p1;
wire   [4:0] sub_ln947_1_fu_1485_p2;
wire   [15:0] zext_ln947_1_fu_1491_p1;
wire   [15:0] lshr_ln947_1_fu_1495_p2;
wire   [15:0] p_Result_12_fu_1501_p2;
wire   [0:0] icmp_ln947_2_fu_1475_p2;
wire   [0:0] icmp_ln947_3_fu_1507_p2;
wire   [0:0] tmp_19_fu_1519_p3;
wire   [15:0] trunc_ln944_1_fu_1455_p1;
wire   [15:0] add_ln949_1_fu_1533_p2;
wire   [0:0] p_Result_13_fu_1539_p3;
wire   [0:0] xor_ln949_1_fu_1527_p2;
wire   [0:0] and_ln949_1_fu_1547_p2;
wire   [0:0] a_1_fu_1513_p2;
wire   [0:0] or_ln949_1_fu_1553_p2;
wire   [31:0] zext_ln957_2_fu_1581_p1;
wire   [31:0] add_ln958_1_fu_1585_p2;
wire   [31:0] lshr_ln958_1_fu_1590_p2;
wire   [31:0] sub_ln958_1_fu_1600_p2;
wire   [63:0] m_15_fu_1577_p1;
wire   [63:0] zext_ln958_3_fu_1605_p1;
wire   [63:0] zext_ln958_2_fu_1596_p1;
wire   [63:0] shl_ln958_1_fu_1609_p2;
wire   [63:0] m_16_fu_1615_p3;
wire   [63:0] zext_ln961_1_fu_1622_p1;
wire   [63:0] m_17_fu_1625_p2;
wire   [62:0] m_3_fu_1631_p4;
wire   [0:0] tmp_20_fu_1645_p3;
wire   [7:0] select_ln964_1_fu_1653_p3;
wire   [7:0] sub_ln964_1_fu_1661_p2;
wire   [7:0] add_ln964_1_fu_1666_p2;
wire   [63:0] m_27_fu_1641_p1;
wire   [8:0] tmp_4_fu_1672_p3;
wire   [63:0] p_Result_26_fu_1679_p5;
wire   [31:0] trunc_ln738_1_fu_1691_p1;
wire   [31:0] bitcast_ln111_fu_1706_p1;
wire   [7:0] tmp_1_fu_1710_p4;
wire   [22:0] trunc_ln111_fu_1720_p1;
wire   [15:0] tmp_V_7_fu_1743_p2;
reg   [15:0] p_Result_16_fu_1755_p4;
wire   [31:0] p_Result_28_fu_1765_p3;
reg   [31:0] l_2_fu_1773_p3;
wire   [31:0] lsb_index_2_fu_1791_p2;
wire   [30:0] tmp_22_fu_1797_p4;
wire   [4:0] trunc_ln947_2_fu_1813_p1;
wire   [4:0] sub_ln947_2_fu_1817_p2;
wire   [15:0] zext_ln947_2_fu_1823_p1;
wire   [15:0] lshr_ln947_2_fu_1827_p2;
wire   [15:0] p_Result_18_fu_1833_p2;
wire   [0:0] icmp_ln947_4_fu_1807_p2;
wire   [0:0] icmp_ln947_5_fu_1839_p2;
wire   [0:0] tmp_23_fu_1851_p3;
wire   [15:0] trunc_ln944_2_fu_1787_p1;
wire   [15:0] add_ln949_2_fu_1865_p2;
wire   [0:0] p_Result_19_fu_1871_p3;
wire   [0:0] xor_ln949_2_fu_1859_p2;
wire   [0:0] and_ln949_2_fu_1879_p2;
wire   [0:0] a_2_fu_1845_p2;
wire   [0:0] or_ln949_3_fu_1885_p2;
wire   [31:0] bitcast_ln111_1_fu_1909_p1;
wire   [7:0] tmp_3_fu_1913_p4;
wire   [22:0] trunc_ln111_1_fu_1923_p1;
wire   [0:0] icmp_ln111_3_fu_1937_p2;
wire   [0:0] icmp_ln111_2_fu_1931_p2;
wire   [0:0] or_ln111_1_fu_1927_p2;
wire   [0:0] or_ln111_2_fu_1943_p2;
wire   [0:0] and_ln111_fu_1949_p2;
wire   [0:0] grp_fu_671_p2;
wire   [0:0] and_ln111_1_fu_1955_p2;
wire   [0:0] xor_ln111_fu_1961_p2;
wire   [31:0] zext_ln957_3_fu_1983_p1;
wire   [31:0] add_ln958_2_fu_1986_p2;
wire   [31:0] lshr_ln958_2_fu_1991_p2;
wire   [31:0] sub_ln958_2_fu_2001_p2;
wire   [63:0] m_21_fu_1980_p1;
wire   [63:0] zext_ln958_5_fu_2006_p1;
wire   [63:0] zext_ln958_4_fu_1997_p1;
wire   [63:0] shl_ln958_2_fu_2010_p2;
wire   [63:0] m_22_fu_2016_p3;
wire   [63:0] zext_ln961_2_fu_2023_p1;
wire   [63:0] m_23_fu_2026_p2;
wire   [62:0] m_4_fu_2032_p4;
wire   [0:0] tmp_24_fu_2046_p3;
wire   [7:0] select_ln964_2_fu_2054_p3;
wire   [7:0] sub_ln964_2_fu_2062_p2;
wire   [7:0] add_ln964_2_fu_2067_p2;
wire   [63:0] m_28_fu_2042_p1;
wire   [8:0] tmp_6_fu_2073_p3;
wire   [63:0] p_Result_29_fu_2080_p5;
wire   [31:0] trunc_ln738_2_fu_2092_p1;
wire   [0:0] or_ln111_fu_1967_p2;
wire   [31:0] select_ln111_fu_1972_p3;
wire   [31:0] bitcast_ln739_2_fu_2096_p1;
wire   [25:0] grp_fu_2142_p2;
wire   [14:0] grp_fu_2151_p0;
wire   [25:0] grp_fu_2151_p2;
wire   [14:0] grp_fu_2160_p0;
wire   [25:0] grp_fu_2160_p2;
wire   [14:0] grp_fu_2169_p0;
wire   [25:0] grp_fu_2169_p2;
reg   [1:0] grp_fu_659_opcode;
reg   [52:0] ap_NS_fsm;
wire   [25:0] grp_fu_2151_p00;
wire   [25:0] grp_fu_2160_p00;
wire   [25:0] grp_fu_2169_p00;

// power-on initialization
initial begin
#0 ap_CS_fsm = 53'd1;
end

mlp_B1_V #(
    .DataWidth( 9 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
B1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(B1_V_address0),
    .ce0(B1_V_ce0),
    .q0(B1_V_q0)
);

mlp_W1_V #(
    .DataWidth( 12 ),
    .AddressRange( 3920 ),
    .AddressWidth( 12 ))
W1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W1_V_address0),
    .ce0(W1_V_ce0),
    .q0(W1_V_q0)
);

mlp_B2_V #(
    .DataWidth( 11 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
B2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(B2_V_address0),
    .ce0(B2_V_ce0),
    .q0(B2_V_q0)
);

mlp_W2_V #(
    .DataWidth( 12 ),
    .AddressRange( 40 ),
    .AddressWidth( 6 ))
W2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W2_V_address0),
    .ce0(W2_V_ce0),
    .q0(W2_V_q0)
);

mlp_B3_V #(
    .DataWidth( 12 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
B3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(B3_V_address0),
    .ce0(B3_V_ce0),
    .q0(B3_V_q0)
);

mlp_W3_V #(
    .DataWidth( 11 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
W3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W3_V_address0),
    .ce0(W3_V_ce0),
    .q0(W3_V_q0)
);

mlp_B4_V #(
    .DataWidth( 12 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
B4_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(B4_V_address0),
    .ce0(B4_V_ce0),
    .q0(B4_V_q0)
);

mlp_W4_V #(
    .DataWidth( 12 ),
    .AddressRange( 80 ),
    .AddressWidth( 7 ))
W4_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W4_V_address0),
    .ce0(W4_V_ce0),
    .q0(W4_V_q0)
);

mlp_a1_V #(
    .DataWidth( 15 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
a1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(a1_V_address0),
    .ce0(a1_V_ce0),
    .we0(a1_V_we0),
    .d0(a1_V_d0),
    .q0(a1_V_q0)
);

mlp_a2_V #(
    .DataWidth( 15 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
a2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(a2_V_address0),
    .ce0(a2_V_ce0),
    .we0(a2_V_we0),
    .d0(a2_V_d0),
    .q0(a2_V_q0)
);

mlp_a2_V #(
    .DataWidth( 15 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
a3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(a3_V_address0),
    .ce0(a3_V_ce0),
    .we0(a3_V_we0),
    .d0(a3_V_d0),
    .q0(a3_V_q0)
);

mlp_z4_V #(
    .DataWidth( 16 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
z4_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(z4_V_address0),
    .ce0(z4_V_ce0),
    .we0(z4_V_we0),
    .d0(p_Val2_14_reg_569),
    .q0(z4_V_q0)
);

mlp_logits #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
logits_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(logits_address0),
    .ce0(logits_ce0),
    .we0(logits_we0),
    .d0(logits_d0),
    .q0(logits_q0)
);

mlp_faddfsub_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mlp_faddfsub_32ns_32ns_32_4_full_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_659_p0),
    .din1(grp_fu_659_p1),
    .opcode(grp_fu_659_opcode),
    .ce(1'b1),
    .dout(grp_fu_659_p2)
);

mlp_fdiv_32ns_32ns_32_9_1 #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mlp_fdiv_32ns_32ns_32_9_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(output_load_reg_2584),
    .din1(sum_0_reg_625),
    .ce(1'b1),
    .dout(grp_fu_666_p2)
);

mlp_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
mlp_fcmp_32ns_32ns_1_2_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_0202_reg_613),
    .din1(maxv_0_reg_591),
    .ce(1'b1),
    .opcode(5'd2),
    .dout(grp_fu_671_p2)
);

mlp_fexp_32ns_32ns_32_8_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mlp_fexp_32ns_32ns_32_8_full_dsp_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(tmp_reg_2556),
    .ce(1'b1),
    .dout(grp_fu_677_p2)
);

mlp_mac_muladd_16s_12s_26ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mlp_mac_muladd_16s_12s_26ns_26_1_1_U5(
    .din0(input_V_q0),
    .din1(W1_V_q0),
    .din2(grp_fu_2142_p2),
    .dout(grp_fu_2142_p3)
);

mlp_mac_muladd_15ns_12s_26ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mlp_mac_muladd_15ns_12s_26ns_26_1_1_U6(
    .din0(grp_fu_2151_p0),
    .din1(W2_V_q0),
    .din2(grp_fu_2151_p2),
    .dout(grp_fu_2151_p3)
);

mlp_mac_muladd_15ns_11s_26ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 11 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mlp_mac_muladd_15ns_11s_26ns_26_1_1_U7(
    .din0(grp_fu_2160_p0),
    .din1(W3_V_q0),
    .din2(grp_fu_2160_p2),
    .dout(grp_fu_2160_p3)
);

mlp_mac_muladd_15ns_12s_26ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mlp_mac_muladd_15ns_12s_26ns_26_1_1_U8(
    .din0(grp_fu_2169_p0),
    .din1(W4_V_q0),
    .din2(grp_fu_2169_p2),
    .dout(grp_fu_2169_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        i_0_i10_reg_513 <= i_1_reg_2260;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        i_0_i10_reg_513 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        i_0_i26_reg_546 <= i_2_reg_2311;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        i_0_i26_reg_546 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        i_0_i42_reg_580 <= i_3_reg_2367;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        i_0_i42_reg_580 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i_0_i_reg_480 <= i_reg_2209;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        i_0_i_reg_480 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln88_fu_731_p2 == 1'd1))) begin
        j4_0_reg_491 <= 4'd0;
    end else if (((icmp_ln68_1_fu_873_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        j4_0_reg_491 <= j_1_reg_2232;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln93_fu_830_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        j5_0_reg_524 <= 4'd0;
    end else if (((icmp_ln68_2_fu_983_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
        j5_0_reg_524 <= j_2_reg_2283;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln98_fu_950_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
        j6_0_reg_557 <= 4'd0;
    end else if (((icmp_ln68_3_fu_1093_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        j6_0_reg_557 <= j_3_reg_2334;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        j7_0_reg_601 <= 4'd1;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        j7_0_reg_601 <= j_5_reg_2481;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        j8_0_reg_637 <= j_4_reg_2536;
    end else if (((icmp_ln109_fu_1422_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20))) begin
        j8_0_reg_637 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln118_fu_2108_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state25))) begin
        j9_0_reg_648 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state53)) begin
        j9_0_reg_648 <= j_6_reg_2574;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        j_0_reg_447 <= 3'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln68_fu_752_p2 == 1'd1))) begin
        j_0_reg_447 <= j_reg_2186;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        maxv_0_reg_591 <= select_ln935_fu_1415_p3;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        maxv_0_reg_591 <= select_ln111_1_fu_2100_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state21) & (grp_fu_683_p2 == 1'd1))) begin
        p_0202_reg_613 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state22) & (icmp_ln935_1_reg_2445 == 1'd0))) begin
        p_0202_reg_613 <= bitcast_ln739_1_fu_1695_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        p_Val2_14_reg_569 <= {{grp_fu_2169_p3[25:10]}};
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        p_Val2_14_reg_569 <= sext_ln104_fu_1089_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_Val2_1_reg_470 <= {{grp_fu_2142_p3[25:10]}};
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        p_Val2_1_reg_470 <= zext_ln89_1_fu_748_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        p_Val2_4_reg_503 <= {{grp_fu_2151_p3[25:10]}};
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        p_Val2_4_reg_503 <= sext_ln94_fu_869_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        p_Val2_9_reg_536 <= {{grp_fu_2160_p3[25:10]}};
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        p_Val2_9_reg_536 <= sext_ln99_fu_979_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_mul_reg_458 <= 12'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln68_fu_752_p2 == 1'd1))) begin
        phi_mul_reg_458 <= add_ln88_reg_2178;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        sum_0_reg_625 <= grp_fu_659_p2;
    end else if (((icmp_ln109_fu_1422_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20))) begin
        sum_0_reg_625 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln1117_reg_2247 <= add_ln1117_fu_863_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln88_reg_2178 <= add_ln88_fu_725_p2;
        j_reg_2186 <= j_fu_737_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        e_reg_2561 <= grp_fu_677_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        i_1_reg_2260 <= i_1_fu_879_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        i_2_reg_2311 <= i_2_fu_989_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        i_3_reg_2367 <= i_3_fu_1099_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        i_reg_2209 <= i_fu_758_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        icmp_ln111_1_reg_2491 <= icmp_ln111_1_fu_1730_p2;
        icmp_ln111_reg_2486 <= icmp_ln111_fu_1724_p2;
        icmp_ln958_2_reg_2518 <= icmp_ln958_2_fu_1899_p2;
        or_ln949_4_reg_2513[0] <= or_ln949_4_fu_1891_p3[0];
        p_Result_27_reg_2496 <= tmp_V_11_reg_2438[32'd15];
        sub_ln944_2_reg_2507 <= sub_ln944_2_fu_1781_p2;
        tmp_V_13_reg_2501 <= tmp_V_13_fu_1748_p3;
        trunc_ln943_2_reg_2523 <= trunc_ln943_2_fu_1905_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        icmp_ln935_1_reg_2445 <= grp_fu_683_p2;
        tmp_V_11_reg_2438 <= z4_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        icmp_ln935_reg_2387 <= grp_fu_683_p2;
        icmp_ln958_reg_2408 <= icmp_ln958_fu_1283_p2;
        or_ln_reg_2403[0] <= or_ln_fu_1275_p3[0];
        p_Result_21_reg_2392 <= z4_V_q0[32'd15];
        sub_ln944_reg_2397 <= sub_ln944_fu_1165_p2;
        trunc_ln943_reg_2413 <= trunc_ln943_fu_1289_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state21) & (grp_fu_683_p2 == 1'd0))) begin
        icmp_ln958_1_reg_2466 <= icmp_ln958_1_fu_1567_p2;
        or_ln949_2_reg_2461[0] <= or_ln949_2_fu_1559_p3[0];
        p_Result_24_reg_2450 <= z4_V_q0[32'd15];
        sub_ln944_1_reg_2455 <= sub_ln944_1_fu_1449_p2;
        trunc_ln943_1_reg_2471 <= trunc_ln943_1_fu_1573_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        j_1_reg_2232 <= j_1_fu_836_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        j_2_reg_2283 <= j_2_fu_956_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        j_3_reg_2334 <= j_3_fu_1066_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        j_4_reg_2536 <= j_4_fu_2114_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        j_5_reg_2481 <= j_5_fu_1700_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        j_6_reg_2574 <= j_6_fu_2131_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state42) & (icmp_ln124_fu_2125_p2 == 1'd0))) begin
        output_addr_1_reg_2579 <= zext_ln125_fu_2137_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        output_load_reg_2584 <= output_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state18) | ((1'b1 == ap_CS_fsm_state21) & (grp_fu_683_p2 == 1'd0)))) begin
        reg_721 <= grp_fu_703_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        select_ln935_reg_2418 <= select_ln935_fu_1415_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state52)) begin
        tmp_2_reg_2589 <= grp_fu_666_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        tmp_reg_2556 <= grp_fu_659_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        zext_ln104_1_reg_2354[6 : 3] <= zext_ln104_1_fu_1085_p1[6 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & (icmp_ln103_fu_1060_p2 == 1'd0))) begin
        zext_ln104_reg_2339[3 : 0] <= zext_ln104_fu_1072_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state20) & (icmp_ln109_fu_1422_p2 == 1'd0))) begin
        zext_ln110_reg_2427[3 : 0] <= zext_ln110_fu_1428_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state25) & (icmp_ln118_fu_2108_p2 == 1'd0))) begin
        zext_ln119_reg_2541[3 : 0] <= zext_ln119_fu_2120_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln88_fu_731_p2 == 1'd0))) begin
        zext_ln89_reg_2191[2 : 0] <= zext_ln89_fu_743_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln93_fu_830_p2 == 1'd0))) begin
        zext_ln94_reg_2237[3 : 0] <= zext_ln94_fu_842_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        zext_ln99_1_reg_2298[6 : 3] <= zext_ln99_1_fu_975_p1[6 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (icmp_ln98_fu_950_p2 == 1'd0))) begin
        zext_ln99_reg_2288[3 : 0] <= zext_ln99_fu_962_p1[3 : 0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        B1_V_ce0 = 1'b1;
    end else begin
        B1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B2_V_ce0 = 1'b1;
    end else begin
        B2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        B3_V_ce0 = 1'b1;
    end else begin
        B3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        B4_V_ce0 = 1'b1;
    end else begin
        B4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        W1_V_ce0 = 1'b1;
    end else begin
        W1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        W2_V_ce0 = 1'b1;
    end else begin
        W2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        W3_V_ce0 = 1'b1;
    end else begin
        W3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        W4_V_ce0 = 1'b1;
    end else begin
        W4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        a1_V_address0 = zext_ln69_1_fu_885_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        a1_V_address0 = zext_ln89_reg_2191;
    end else begin
        a1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state4))) begin
        a1_V_ce0 = 1'b1;
    end else begin
        a1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln68_fu_752_p2 == 1'd1))) begin
        a1_V_we0 = 1'b1;
    end else begin
        a1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        a2_V_address0 = zext_ln69_2_fu_995_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        a2_V_address0 = zext_ln94_reg_2237;
    end else begin
        a2_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state8))) begin
        a2_V_ce0 = 1'b1;
    end else begin
        a2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln68_1_fu_873_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
        a2_V_we0 = 1'b1;
    end else begin
        a2_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        a3_V_address0 = zext_ln69_3_fu_1105_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        a3_V_address0 = zext_ln99_reg_2288;
    end else begin
        a3_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state12))) begin
        a3_V_ce0 = 1'b1;
    end else begin
        a3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln68_2_fu_983_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
        a3_V_we0 = 1'b1;
    end else begin
        a3_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln124_fu_2125_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state42))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln124_fu_2125_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state42))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        grp_fu_659_opcode = 2'd1;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        grp_fu_659_opcode = 2'd0;
    end else begin
        grp_fu_659_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        grp_fu_659_p0 = sum_0_reg_625;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        grp_fu_659_p0 = logits_q0;
    end else begin
        grp_fu_659_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        grp_fu_659_p1 = e_reg_2561;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        grp_fu_659_p1 = maxv_0_reg_591;
    end else begin
        grp_fu_659_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_V_ce0 = 1'b1;
    end else begin
        input_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        logits_address0 = zext_ln119_fu_2120_p1;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        logits_address0 = logits_addr_1_gep_fu_412_p3;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        logits_address0 = zext_ln110_reg_2427;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        logits_address0 = 64'd0;
    end else begin
        logits_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state21))) begin
        logits_ce0 = 1'b1;
    end else begin
        logits_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        logits_d0 = bitcast_ln739_1_fu_1695_p1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        logits_d0 = 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        logits_d0 = select_ln935_reg_2418;
    end else begin
        logits_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state22) & (icmp_ln935_1_reg_2445 == 1'd0)) | ((icmp_ln109_fu_1422_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20)) | ((1'b1 == ap_CS_fsm_state21) & (grp_fu_683_p2 == 1'd1)))) begin
        logits_we0 = 1'b1;
    end else begin
        logits_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state53)) begin
        output_r_address0 = output_addr_1_reg_2579;
    end else if ((1'b1 == ap_CS_fsm_state42)) begin
        output_r_address0 = zext_ln125_fu_2137_p1;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        output_r_address0 = zext_ln119_reg_2541;
    end else begin
        output_r_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state37))) begin
        output_r_ce0 = 1'b1;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state53)) begin
        output_r_d0 = tmp_2_reg_2589;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        output_r_d0 = grp_fu_677_p2;
    end else begin
        output_r_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state37))) begin
        output_r_we0 = 1'b1;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        z4_V_address0 = zext_ln110_fu_1428_p1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        z4_V_address0 = zext_ln104_reg_2339;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        z4_V_address0 = 64'd0;
    end else begin
        z4_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state14))) begin
        z4_V_ce0 = 1'b1;
    end else begin
        z4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln68_3_fu_1093_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        z4_V_we0 = 1'b1;
    end else begin
        z4_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln88_fu_731_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln68_fu_752_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state6 : begin
            if (((icmp_ln93_fu_830_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((icmp_ln68_1_fu_873_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state10 : begin
            if (((icmp_ln98_fu_950_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((icmp_ln68_2_fu_983_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state14 : begin
            if (((icmp_ln103_fu_1060_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((icmp_ln68_3_fu_1093_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((icmp_ln109_fu_1422_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state25 : begin
            if (((icmp_ln118_fu_2108_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state25))) begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state42 : begin
            if (((icmp_ln124_fu_2125_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state42))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state43;
            end
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B1_V_address0 = zext_ln89_fu_743_p1;

assign B2_V_address0 = zext_ln94_fu_842_p1;

assign B3_V_address0 = zext_ln99_fu_962_p1;

assign B4_V_address0 = zext_ln104_fu_1072_p1;

assign W1_V_address0 = zext_ln1117_3_fu_779_p1;

assign W2_V_address0 = zext_ln1117_5_fu_899_p1;

assign W3_V_address0 = zext_ln1117_7_fu_1009_p1;

assign W4_V_address0 = zext_ln1117_9_fu_1119_p1;

assign a1_V_d0 = ((tmp_10_fu_788_p3[0:0] === 1'b1) ? 15'd0 : empty_16_fu_784_p1);

assign a2_V_d0 = ((tmp_11_fu_908_p3[0:0] === 1'b1) ? 15'd0 : empty_19_fu_904_p1);

assign a3_V_d0 = ((tmp_16_fu_1018_p3[0:0] === 1'b1) ? 15'd0 : empty_22_fu_1014_p1);

assign a_1_fu_1513_p2 = (icmp_ln947_3_fu_1507_p2 & icmp_ln947_2_fu_1475_p2);

assign a_2_fu_1845_p2 = (icmp_ln947_5_fu_1839_p2 & icmp_ln947_4_fu_1807_p2);

assign a_fu_1229_p2 = (icmp_ln947_fu_1191_p2 & icmp_ln947_1_fu_1223_p2);

assign add_ln1117_1_fu_773_p2 = (zext_ln1117_2_fu_769_p1 + phi_mul_reg_458);

assign add_ln1117_2_fu_894_p2 = (zext_ln1117_4_fu_890_p1 + add_ln1117_reg_2247);

assign add_ln1117_3_fu_1004_p2 = (zext_ln1117_6_fu_1000_p1 + zext_ln99_1_reg_2298);

assign add_ln1117_4_fu_1114_p2 = (zext_ln1117_8_fu_1110_p1 + zext_ln104_1_reg_2354);

assign add_ln1117_fu_863_p2 = (zext_ln1117_fu_847_p1 + zext_ln1117_1_fu_859_p1);

assign add_ln88_fu_725_p2 = (phi_mul_reg_458 + 12'd784);

assign add_ln949_1_fu_1533_p2 = ($signed(16'd65512) + $signed(trunc_ln944_1_fu_1455_p1));

assign add_ln949_2_fu_1865_p2 = ($signed(16'd65512) + $signed(trunc_ln944_2_fu_1787_p1));

assign add_ln949_fu_1249_p2 = ($signed(16'd65512) + $signed(trunc_ln944_fu_1171_p1));

assign add_ln958_1_fu_1585_p2 = ($signed(32'd4294967271) + $signed(sub_ln944_1_reg_2455));

assign add_ln958_2_fu_1986_p2 = ($signed(32'd4294967271) + $signed(sub_ln944_2_reg_2507));

assign add_ln958_fu_1301_p2 = ($signed(32'd4294967271) + $signed(sub_ln944_reg_2397));

assign add_ln964_1_fu_1666_p2 = (select_ln964_1_fu_1653_p3 + sub_ln964_1_fu_1661_p2);

assign add_ln964_2_fu_2067_p2 = (select_ln964_2_fu_2054_p3 + sub_ln964_2_fu_2062_p2);

assign add_ln964_fu_1382_p2 = (select_ln964_fu_1369_p3 + sub_ln964_fu_1377_p2);

assign and_ln111_1_fu_1955_p2 = (grp_fu_671_p2 & and_ln111_fu_1949_p2);

assign and_ln111_fu_1949_p2 = (or_ln111_2_fu_1943_p2 & or_ln111_1_fu_1927_p2);

assign and_ln949_1_fu_1547_p2 = (xor_ln949_1_fu_1527_p2 & p_Result_13_fu_1539_p3);

assign and_ln949_2_fu_1879_p2 = (xor_ln949_2_fu_1859_p2 & p_Result_19_fu_1871_p3);

assign and_ln949_fu_1263_p2 = (xor_ln949_fu_1243_p2 & p_Result_3_fu_1255_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state52 = ap_CS_fsm[32'd51];

assign ap_CS_fsm_state53 = ap_CS_fsm[32'd52];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign bitcast_ln111_1_fu_1909_p1 = maxv_0_reg_591;

assign bitcast_ln111_fu_1706_p1 = p_0202_reg_613;

assign bitcast_ln739_1_fu_1695_p1 = trunc_ln738_1_fu_1691_p1;

assign bitcast_ln739_2_fu_2096_p1 = trunc_ln738_2_fu_2092_p1;

assign bitcast_ln739_fu_1411_p1 = trunc_ln738_fu_1407_p1;

assign empty_16_fu_784_p1 = p_Val2_1_reg_470[14:0];

assign empty_19_fu_904_p1 = p_Val2_4_reg_503[14:0];

assign empty_22_fu_1014_p1 = p_Val2_9_reg_536[14:0];

assign grp_fu_2142_p2 = {{p_Val2_1_reg_470}, {10'd0}};

assign grp_fu_2151_p0 = grp_fu_2151_p00;

assign grp_fu_2151_p00 = a1_V_q0;

assign grp_fu_2151_p2 = {{p_Val2_4_reg_503}, {10'd0}};

assign grp_fu_2160_p0 = grp_fu_2160_p00;

assign grp_fu_2160_p00 = a2_V_q0;

assign grp_fu_2160_p2 = {{p_Val2_9_reg_536}, {10'd0}};

assign grp_fu_2169_p0 = grp_fu_2169_p00;

assign grp_fu_2169_p00 = a3_V_q0;

assign grp_fu_2169_p2 = {{p_Val2_14_reg_569}, {10'd0}};

assign grp_fu_683_p2 = ((z4_V_q0 == 16'd0) ? 1'b1 : 1'b0);

assign grp_fu_689_p3 = z4_V_q0[32'd15];

assign grp_fu_697_p2 = (16'd0 - z4_V_q0);

assign grp_fu_703_p3 = ((grp_fu_689_p3[0:0] === 1'b1) ? grp_fu_697_p2 : z4_V_q0);

integer ap_tvar_int_0;

always @ (grp_fu_703_p3) begin
    for (ap_tvar_int_0 = 16 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 15 - 0) begin
            grp_fu_711_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            grp_fu_711_p4[ap_tvar_int_0] = grp_fu_703_p3[15 - ap_tvar_int_0];
        end
    end
end

assign i_1_fu_879_p2 = (i_0_i10_reg_513 + 3'd1);

assign i_2_fu_989_p2 = (i_0_i26_reg_546 + 4'd1);

assign i_3_fu_1099_p2 = (i_0_i42_reg_580 + 4'd1);

assign i_fu_758_p2 = (i_0_i_reg_480 + 10'd1);

assign icmp_ln103_fu_1060_p2 = ((j6_0_reg_557 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln109_fu_1422_p2 = ((j7_0_reg_601 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln111_1_fu_1730_p2 = ((trunc_ln111_fu_1720_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln111_2_fu_1931_p2 = ((tmp_3_fu_1913_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln111_3_fu_1937_p2 = ((trunc_ln111_1_fu_1923_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln111_fu_1724_p2 = ((tmp_1_fu_1710_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln118_fu_2108_p2 = ((j8_0_reg_637 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln124_fu_2125_p2 = ((j9_0_reg_648 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln68_1_fu_873_p2 = ((i_0_i10_reg_513 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln68_2_fu_983_p2 = ((i_0_i26_reg_546 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln68_3_fu_1093_p2 = ((i_0_i42_reg_580 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln68_fu_752_p2 = ((i_0_i_reg_480 == 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln88_fu_731_p2 = ((j_0_reg_447 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln93_fu_830_p2 = ((j4_0_reg_491 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln947_1_fu_1223_p2 = ((p_Result_4_fu_1217_p2 != 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln947_2_fu_1475_p2 = (($signed(tmp_18_fu_1465_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln947_3_fu_1507_p2 = ((p_Result_12_fu_1501_p2 != 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln947_4_fu_1807_p2 = (($signed(tmp_22_fu_1797_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln947_5_fu_1839_p2 = ((p_Result_18_fu_1833_p2 != 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln947_fu_1191_p2 = (($signed(tmp_13_fu_1181_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln958_1_fu_1567_p2 = (($signed(lsb_index_1_fu_1459_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln958_2_fu_1899_p2 = (($signed(lsb_index_2_fu_1791_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln958_fu_1283_p2 = (($signed(lsb_index_fu_1175_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln98_fu_950_p2 = ((j5_0_reg_524 == 4'd8) ? 1'b1 : 1'b0);

assign input_V_address0 = zext_ln69_fu_764_p1;

assign j_1_fu_836_p2 = (j4_0_reg_491 + 4'd1);

assign j_2_fu_956_p2 = (j5_0_reg_524 + 4'd1);

assign j_3_fu_1066_p2 = (j6_0_reg_557 + 4'd1);

assign j_4_fu_2114_p2 = (j8_0_reg_637 + 4'd1);

assign j_5_fu_1700_p2 = (4'd1 + j7_0_reg_601);

assign j_6_fu_2131_p2 = (j9_0_reg_648 + 4'd1);

assign j_fu_737_p2 = (j_0_reg_447 + 3'd1);


always @ (p_Result_25_fu_1433_p3) begin
    if (p_Result_25_fu_1433_p3[0] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd0;
    end else if (p_Result_25_fu_1433_p3[1] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd1;
    end else if (p_Result_25_fu_1433_p3[2] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd2;
    end else if (p_Result_25_fu_1433_p3[3] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd3;
    end else if (p_Result_25_fu_1433_p3[4] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd4;
    end else if (p_Result_25_fu_1433_p3[5] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd5;
    end else if (p_Result_25_fu_1433_p3[6] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd6;
    end else if (p_Result_25_fu_1433_p3[7] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd7;
    end else if (p_Result_25_fu_1433_p3[8] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd8;
    end else if (p_Result_25_fu_1433_p3[9] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd9;
    end else if (p_Result_25_fu_1433_p3[10] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd10;
    end else if (p_Result_25_fu_1433_p3[11] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd11;
    end else if (p_Result_25_fu_1433_p3[12] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd12;
    end else if (p_Result_25_fu_1433_p3[13] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd13;
    end else if (p_Result_25_fu_1433_p3[14] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd14;
    end else if (p_Result_25_fu_1433_p3[15] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd15;
    end else if (p_Result_25_fu_1433_p3[16] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd16;
    end else if (p_Result_25_fu_1433_p3[17] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd17;
    end else if (p_Result_25_fu_1433_p3[18] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd18;
    end else if (p_Result_25_fu_1433_p3[19] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd19;
    end else if (p_Result_25_fu_1433_p3[20] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd20;
    end else if (p_Result_25_fu_1433_p3[21] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd21;
    end else if (p_Result_25_fu_1433_p3[22] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd22;
    end else if (p_Result_25_fu_1433_p3[23] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd23;
    end else if (p_Result_25_fu_1433_p3[24] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd24;
    end else if (p_Result_25_fu_1433_p3[25] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd25;
    end else if (p_Result_25_fu_1433_p3[26] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd26;
    end else if (p_Result_25_fu_1433_p3[27] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd27;
    end else if (p_Result_25_fu_1433_p3[28] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd28;
    end else if (p_Result_25_fu_1433_p3[29] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd29;
    end else if (p_Result_25_fu_1433_p3[30] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd30;
    end else if (p_Result_25_fu_1433_p3[31] == 1'b1) begin
        l_1_fu_1441_p3 = 32'd31;
    end else begin
        l_1_fu_1441_p3 = 32'd32;
    end
end


always @ (p_Result_28_fu_1765_p3) begin
    if (p_Result_28_fu_1765_p3[0] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd0;
    end else if (p_Result_28_fu_1765_p3[1] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd1;
    end else if (p_Result_28_fu_1765_p3[2] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd2;
    end else if (p_Result_28_fu_1765_p3[3] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd3;
    end else if (p_Result_28_fu_1765_p3[4] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd4;
    end else if (p_Result_28_fu_1765_p3[5] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd5;
    end else if (p_Result_28_fu_1765_p3[6] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd6;
    end else if (p_Result_28_fu_1765_p3[7] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd7;
    end else if (p_Result_28_fu_1765_p3[8] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd8;
    end else if (p_Result_28_fu_1765_p3[9] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd9;
    end else if (p_Result_28_fu_1765_p3[10] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd10;
    end else if (p_Result_28_fu_1765_p3[11] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd11;
    end else if (p_Result_28_fu_1765_p3[12] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd12;
    end else if (p_Result_28_fu_1765_p3[13] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd13;
    end else if (p_Result_28_fu_1765_p3[14] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd14;
    end else if (p_Result_28_fu_1765_p3[15] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd15;
    end else if (p_Result_28_fu_1765_p3[16] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd16;
    end else if (p_Result_28_fu_1765_p3[17] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd17;
    end else if (p_Result_28_fu_1765_p3[18] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd18;
    end else if (p_Result_28_fu_1765_p3[19] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd19;
    end else if (p_Result_28_fu_1765_p3[20] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd20;
    end else if (p_Result_28_fu_1765_p3[21] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd21;
    end else if (p_Result_28_fu_1765_p3[22] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd22;
    end else if (p_Result_28_fu_1765_p3[23] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd23;
    end else if (p_Result_28_fu_1765_p3[24] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd24;
    end else if (p_Result_28_fu_1765_p3[25] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd25;
    end else if (p_Result_28_fu_1765_p3[26] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd26;
    end else if (p_Result_28_fu_1765_p3[27] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd27;
    end else if (p_Result_28_fu_1765_p3[28] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd28;
    end else if (p_Result_28_fu_1765_p3[29] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd29;
    end else if (p_Result_28_fu_1765_p3[30] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd30;
    end else if (p_Result_28_fu_1765_p3[31] == 1'b1) begin
        l_2_fu_1773_p3 = 32'd31;
    end else begin
        l_2_fu_1773_p3 = 32'd32;
    end
end


always @ (p_Result_22_fu_1149_p3) begin
    if (p_Result_22_fu_1149_p3[0] == 1'b1) begin
        l_fu_1157_p3 = 32'd0;
    end else if (p_Result_22_fu_1149_p3[1] == 1'b1) begin
        l_fu_1157_p3 = 32'd1;
    end else if (p_Result_22_fu_1149_p3[2] == 1'b1) begin
        l_fu_1157_p3 = 32'd2;
    end else if (p_Result_22_fu_1149_p3[3] == 1'b1) begin
        l_fu_1157_p3 = 32'd3;
    end else if (p_Result_22_fu_1149_p3[4] == 1'b1) begin
        l_fu_1157_p3 = 32'd4;
    end else if (p_Result_22_fu_1149_p3[5] == 1'b1) begin
        l_fu_1157_p3 = 32'd5;
    end else if (p_Result_22_fu_1149_p3[6] == 1'b1) begin
        l_fu_1157_p3 = 32'd6;
    end else if (p_Result_22_fu_1149_p3[7] == 1'b1) begin
        l_fu_1157_p3 = 32'd7;
    end else if (p_Result_22_fu_1149_p3[8] == 1'b1) begin
        l_fu_1157_p3 = 32'd8;
    end else if (p_Result_22_fu_1149_p3[9] == 1'b1) begin
        l_fu_1157_p3 = 32'd9;
    end else if (p_Result_22_fu_1149_p3[10] == 1'b1) begin
        l_fu_1157_p3 = 32'd10;
    end else if (p_Result_22_fu_1149_p3[11] == 1'b1) begin
        l_fu_1157_p3 = 32'd11;
    end else if (p_Result_22_fu_1149_p3[12] == 1'b1) begin
        l_fu_1157_p3 = 32'd12;
    end else if (p_Result_22_fu_1149_p3[13] == 1'b1) begin
        l_fu_1157_p3 = 32'd13;
    end else if (p_Result_22_fu_1149_p3[14] == 1'b1) begin
        l_fu_1157_p3 = 32'd14;
    end else if (p_Result_22_fu_1149_p3[15] == 1'b1) begin
        l_fu_1157_p3 = 32'd15;
    end else if (p_Result_22_fu_1149_p3[16] == 1'b1) begin
        l_fu_1157_p3 = 32'd16;
    end else if (p_Result_22_fu_1149_p3[17] == 1'b1) begin
        l_fu_1157_p3 = 32'd17;
    end else if (p_Result_22_fu_1149_p3[18] == 1'b1) begin
        l_fu_1157_p3 = 32'd18;
    end else if (p_Result_22_fu_1149_p3[19] == 1'b1) begin
        l_fu_1157_p3 = 32'd19;
    end else if (p_Result_22_fu_1149_p3[20] == 1'b1) begin
        l_fu_1157_p3 = 32'd20;
    end else if (p_Result_22_fu_1149_p3[21] == 1'b1) begin
        l_fu_1157_p3 = 32'd21;
    end else if (p_Result_22_fu_1149_p3[22] == 1'b1) begin
        l_fu_1157_p3 = 32'd22;
    end else if (p_Result_22_fu_1149_p3[23] == 1'b1) begin
        l_fu_1157_p3 = 32'd23;
    end else if (p_Result_22_fu_1149_p3[24] == 1'b1) begin
        l_fu_1157_p3 = 32'd24;
    end else if (p_Result_22_fu_1149_p3[25] == 1'b1) begin
        l_fu_1157_p3 = 32'd25;
    end else if (p_Result_22_fu_1149_p3[26] == 1'b1) begin
        l_fu_1157_p3 = 32'd26;
    end else if (p_Result_22_fu_1149_p3[27] == 1'b1) begin
        l_fu_1157_p3 = 32'd27;
    end else if (p_Result_22_fu_1149_p3[28] == 1'b1) begin
        l_fu_1157_p3 = 32'd28;
    end else if (p_Result_22_fu_1149_p3[29] == 1'b1) begin
        l_fu_1157_p3 = 32'd29;
    end else if (p_Result_22_fu_1149_p3[30] == 1'b1) begin
        l_fu_1157_p3 = 32'd30;
    end else if (p_Result_22_fu_1149_p3[31] == 1'b1) begin
        l_fu_1157_p3 = 32'd31;
    end else begin
        l_fu_1157_p3 = 32'd32;
    end
end

assign logits_addr_1_gep_fu_412_p3 = zext_ln110_reg_2427;

assign lsb_index_1_fu_1459_p2 = ($signed(32'd4294967272) + $signed(sub_ln944_1_fu_1449_p2));

assign lsb_index_2_fu_1791_p2 = ($signed(32'd4294967272) + $signed(sub_ln944_2_fu_1781_p2));

assign lsb_index_fu_1175_p2 = ($signed(32'd4294967272) + $signed(sub_ln944_fu_1165_p2));

assign lshr_ln947_1_fu_1495_p2 = 16'd65535 >> zext_ln947_1_fu_1491_p1;

assign lshr_ln947_2_fu_1827_p2 = 16'd65535 >> zext_ln947_2_fu_1823_p1;

assign lshr_ln947_fu_1211_p2 = 16'd65535 >> zext_ln947_fu_1207_p1;

assign lshr_ln958_1_fu_1590_p2 = zext_ln957_2_fu_1581_p1 >> add_ln958_1_fu_1585_p2;

assign lshr_ln958_2_fu_1991_p2 = zext_ln957_3_fu_1983_p1 >> add_ln958_2_fu_1986_p2;

assign lshr_ln958_fu_1306_p2 = zext_ln957_1_fu_1297_p1 >> add_ln958_fu_1301_p2;

assign m_15_fu_1577_p1 = reg_721;

assign m_16_fu_1615_p3 = ((icmp_ln958_1_reg_2466[0:0] === 1'b1) ? zext_ln958_2_fu_1596_p1 : shl_ln958_1_fu_1609_p2);

assign m_17_fu_1625_p2 = (m_16_fu_1615_p3 + zext_ln961_1_fu_1622_p1);

assign m_1_fu_1331_p3 = ((icmp_ln958_reg_2408[0:0] === 1'b1) ? zext_ln958_fu_1312_p1 : shl_ln958_fu_1325_p2);

assign m_21_fu_1980_p1 = tmp_V_13_reg_2501;

assign m_22_fu_2016_p3 = ((icmp_ln958_2_reg_2518[0:0] === 1'b1) ? zext_ln958_4_fu_1997_p1 : shl_ln958_2_fu_2010_p2);

assign m_23_fu_2026_p2 = (m_22_fu_2016_p3 + zext_ln961_2_fu_2023_p1);

assign m_26_fu_1357_p1 = m_s_fu_1347_p4;

assign m_27_fu_1641_p1 = m_3_fu_1631_p4;

assign m_28_fu_2042_p1 = m_4_fu_2032_p4;

assign m_2_fu_1341_p2 = (m_1_fu_1331_p3 + zext_ln961_fu_1338_p1);

assign m_3_fu_1631_p4 = {{m_17_fu_1625_p2[63:1]}};

assign m_4_fu_2032_p4 = {{m_23_fu_2026_p2[63:1]}};

assign m_fu_1293_p1 = reg_721;

assign m_s_fu_1347_p4 = {{m_2_fu_1341_p2[63:1]}};

assign or_ln111_1_fu_1927_p2 = (icmp_ln111_reg_2486 | icmp_ln111_1_reg_2491);

assign or_ln111_2_fu_1943_p2 = (icmp_ln111_3_fu_1937_p2 | icmp_ln111_2_fu_1931_p2);

assign or_ln111_fu_1967_p2 = (xor_ln111_fu_1961_p2 | icmp_ln935_1_reg_2445);

assign or_ln949_1_fu_1553_p2 = (and_ln949_1_fu_1547_p2 | a_1_fu_1513_p2);

assign or_ln949_2_fu_1559_p3 = {{31'd0}, {or_ln949_1_fu_1553_p2}};

assign or_ln949_3_fu_1885_p2 = (and_ln949_2_fu_1879_p2 | a_2_fu_1845_p2);

assign or_ln949_4_fu_1891_p3 = {{31'd0}, {or_ln949_3_fu_1885_p2}};

assign or_ln949_fu_1269_p2 = (and_ln949_fu_1263_p2 | a_fu_1229_p2);

assign or_ln_fu_1275_p3 = {{31'd0}, {or_ln949_fu_1269_p2}};

assign p_Result_12_fu_1501_p2 = (lshr_ln947_1_fu_1495_p2 & grp_fu_703_p3);

assign p_Result_13_fu_1539_p3 = grp_fu_703_p3[add_ln949_1_fu_1533_p2];

integer ap_tvar_int_1;

always @ (tmp_V_13_fu_1748_p3) begin
    for (ap_tvar_int_1 = 16 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 15 - 0) begin
            p_Result_16_fu_1755_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            p_Result_16_fu_1755_p4[ap_tvar_int_1] = tmp_V_13_fu_1748_p3[15 - ap_tvar_int_1];
        end
    end
end

assign p_Result_18_fu_1833_p2 = (tmp_V_13_fu_1748_p3 & lshr_ln947_2_fu_1827_p2);

assign p_Result_19_fu_1871_p3 = tmp_V_13_fu_1748_p3[add_ln949_2_fu_1865_p2];

assign p_Result_22_fu_1149_p3 = {{16'd65535}, {grp_fu_711_p4}};

assign p_Result_23_fu_1395_p5 = {{m_26_fu_1357_p1[63:32]}, {tmp_s_fu_1388_p3}, {m_26_fu_1357_p1[22:0]}};

assign p_Result_25_fu_1433_p3 = {{16'd65535}, {grp_fu_711_p4}};

assign p_Result_26_fu_1679_p5 = {{m_27_fu_1641_p1[63:32]}, {tmp_4_fu_1672_p3}, {m_27_fu_1641_p1[22:0]}};

assign p_Result_27_fu_1736_p3 = tmp_V_11_reg_2438[32'd15];

assign p_Result_28_fu_1765_p3 = {{16'd65535}, {p_Result_16_fu_1755_p4}};

assign p_Result_29_fu_2080_p5 = {{m_28_fu_2042_p1[63:32]}, {tmp_6_fu_2073_p3}, {m_28_fu_2042_p1[22:0]}};

assign p_Result_3_fu_1255_p3 = grp_fu_703_p3[add_ln949_fu_1249_p2];

assign p_Result_4_fu_1217_p2 = (lshr_ln947_fu_1211_p2 & grp_fu_703_p3);

assign select_ln111_1_fu_2100_p3 = ((or_ln111_fu_1967_p2[0:0] === 1'b1) ? select_ln111_fu_1972_p3 : bitcast_ln739_2_fu_2096_p1);

assign select_ln111_fu_1972_p3 = ((and_ln111_1_fu_1955_p2[0:0] === 1'b1) ? 32'd0 : maxv_0_reg_591);

assign select_ln935_fu_1415_p3 = ((icmp_ln935_reg_2387[0:0] === 1'b1) ? 32'd0 : bitcast_ln739_fu_1411_p1);

assign select_ln964_1_fu_1653_p3 = ((tmp_20_fu_1645_p3[0:0] === 1'b1) ? 8'd127 : 8'd126);

assign select_ln964_2_fu_2054_p3 = ((tmp_24_fu_2046_p3[0:0] === 1'b1) ? 8'd127 : 8'd126);

assign select_ln964_fu_1369_p3 = ((tmp_15_fu_1361_p3[0:0] === 1'b1) ? 8'd127 : 8'd126);

assign sext_ln104_fu_1089_p1 = $signed(B4_V_q0);

assign sext_ln94_fu_869_p1 = $signed(B2_V_q0);

assign sext_ln99_fu_979_p1 = $signed(B3_V_q0);

assign shl_ln958_1_fu_1609_p2 = m_15_fu_1577_p1 << zext_ln958_3_fu_1605_p1;

assign shl_ln958_2_fu_2010_p2 = m_21_fu_1980_p1 << zext_ln958_5_fu_2006_p1;

assign shl_ln958_fu_1325_p2 = m_fu_1293_p1 << zext_ln958_1_fu_1321_p1;

assign sub_ln944_1_fu_1449_p2 = (32'd16 - l_1_fu_1441_p3);

assign sub_ln944_2_fu_1781_p2 = (32'd16 - l_2_fu_1773_p3);

assign sub_ln944_fu_1165_p2 = (32'd16 - l_fu_1157_p3);

assign sub_ln947_1_fu_1485_p2 = (5'd9 - trunc_ln947_1_fu_1481_p1);

assign sub_ln947_2_fu_1817_p2 = (5'd9 - trunc_ln947_2_fu_1813_p1);

assign sub_ln947_fu_1201_p2 = (5'd9 - trunc_ln947_fu_1197_p1);

assign sub_ln958_1_fu_1600_p2 = (32'd25 - sub_ln944_1_reg_2455);

assign sub_ln958_2_fu_2001_p2 = (32'd25 - sub_ln944_2_reg_2507);

assign sub_ln958_fu_1316_p2 = (32'd25 - sub_ln944_reg_2397);

assign sub_ln964_1_fu_1661_p2 = (8'd6 - trunc_ln943_1_reg_2471);

assign sub_ln964_2_fu_2062_p2 = (8'd6 - trunc_ln943_2_reg_2523);

assign sub_ln964_fu_1377_p2 = (8'd6 - trunc_ln943_reg_2413);

assign tmp_10_fu_788_p3 = p_Val2_1_reg_470[32'd15];

assign tmp_11_fu_908_p3 = p_Val2_4_reg_503[32'd15];

assign tmp_13_fu_1181_p4 = {{lsb_index_fu_1175_p2[31:1]}};

assign tmp_14_fu_1235_p3 = lsb_index_fu_1175_p2[32'd31];

assign tmp_15_fu_1361_p3 = m_2_fu_1341_p2[32'd25];

assign tmp_16_fu_1018_p3 = p_Val2_9_reg_536[32'd15];

assign tmp_18_fu_1465_p4 = {{lsb_index_1_fu_1459_p2[31:1]}};

assign tmp_19_fu_1519_p3 = lsb_index_1_fu_1459_p2[32'd31];

assign tmp_1_fu_1710_p4 = {{bitcast_ln111_fu_1706_p1[30:23]}};

assign tmp_20_fu_1645_p3 = m_17_fu_1625_p2[32'd25];

assign tmp_22_fu_1797_p4 = {{lsb_index_2_fu_1791_p2[31:1]}};

assign tmp_23_fu_1851_p3 = lsb_index_2_fu_1791_p2[32'd31];

assign tmp_24_fu_2046_p3 = m_23_fu_2026_p2[32'd25];

assign tmp_3_fu_1913_p4 = {{bitcast_ln111_1_fu_1909_p1[30:23]}};

assign tmp_4_fu_1672_p3 = {{p_Result_24_reg_2450}, {add_ln964_1_fu_1666_p2}};

assign tmp_6_fu_2073_p3 = {{p_Result_27_reg_2496}, {add_ln964_2_fu_2067_p2}};

assign tmp_7_fu_851_p3 = {{j4_0_reg_491}, {2'd0}};

assign tmp_8_fu_967_p3 = {{j5_0_reg_524}, {3'd0}};

assign tmp_9_fu_1077_p3 = {{j6_0_reg_557}, {3'd0}};

assign tmp_V_13_fu_1748_p3 = ((p_Result_27_fu_1736_p3[0:0] === 1'b1) ? tmp_V_7_fu_1743_p2 : tmp_V_11_reg_2438);

assign tmp_V_7_fu_1743_p2 = (16'd0 - tmp_V_11_reg_2438);

assign tmp_s_fu_1388_p3 = {{p_Result_21_reg_2392}, {add_ln964_fu_1382_p2}};

assign trunc_ln111_1_fu_1923_p1 = bitcast_ln111_1_fu_1909_p1[22:0];

assign trunc_ln111_fu_1720_p1 = bitcast_ln111_fu_1706_p1[22:0];

assign trunc_ln738_1_fu_1691_p1 = p_Result_26_fu_1679_p5[31:0];

assign trunc_ln738_2_fu_2092_p1 = p_Result_29_fu_2080_p5[31:0];

assign trunc_ln738_fu_1407_p1 = p_Result_23_fu_1395_p5[31:0];

assign trunc_ln943_1_fu_1573_p1 = l_1_fu_1441_p3[7:0];

assign trunc_ln943_2_fu_1905_p1 = l_2_fu_1773_p3[7:0];

assign trunc_ln943_fu_1289_p1 = l_fu_1157_p3[7:0];

assign trunc_ln944_1_fu_1455_p1 = sub_ln944_1_fu_1449_p2[15:0];

assign trunc_ln944_2_fu_1787_p1 = sub_ln944_2_fu_1781_p2[15:0];

assign trunc_ln944_fu_1171_p1 = sub_ln944_fu_1165_p2[15:0];

assign trunc_ln947_1_fu_1481_p1 = sub_ln944_1_fu_1449_p2[4:0];

assign trunc_ln947_2_fu_1813_p1 = sub_ln944_2_fu_1781_p2[4:0];

assign trunc_ln947_fu_1197_p1 = sub_ln944_fu_1165_p2[4:0];

assign xor_ln111_fu_1961_p2 = (1'd1 ^ and_ln111_1_fu_1955_p2);

assign xor_ln949_1_fu_1527_p2 = (tmp_19_fu_1519_p3 ^ 1'd1);

assign xor_ln949_2_fu_1859_p2 = (tmp_23_fu_1851_p3 ^ 1'd1);

assign xor_ln949_fu_1243_p2 = (tmp_14_fu_1235_p3 ^ 1'd1);

assign zext_ln104_1_fu_1085_p1 = tmp_9_fu_1077_p3;

assign zext_ln104_fu_1072_p1 = j6_0_reg_557;

assign zext_ln110_fu_1428_p1 = j7_0_reg_601;

assign zext_ln1117_1_fu_859_p1 = tmp_7_fu_851_p3;

assign zext_ln1117_2_fu_769_p1 = i_0_i_reg_480;

assign zext_ln1117_3_fu_779_p1 = add_ln1117_1_fu_773_p2;

assign zext_ln1117_4_fu_890_p1 = i_0_i10_reg_513;

assign zext_ln1117_5_fu_899_p1 = add_ln1117_2_fu_894_p2;

assign zext_ln1117_6_fu_1000_p1 = i_0_i26_reg_546;

assign zext_ln1117_7_fu_1009_p1 = add_ln1117_3_fu_1004_p2;

assign zext_ln1117_8_fu_1110_p1 = i_0_i42_reg_580;

assign zext_ln1117_9_fu_1119_p1 = add_ln1117_4_fu_1114_p2;

assign zext_ln1117_fu_847_p1 = j4_0_reg_491;

assign zext_ln119_fu_2120_p1 = j8_0_reg_637;

assign zext_ln125_fu_2137_p1 = j9_0_reg_648;

assign zext_ln69_1_fu_885_p1 = i_0_i10_reg_513;

assign zext_ln69_2_fu_995_p1 = i_0_i26_reg_546;

assign zext_ln69_3_fu_1105_p1 = i_0_i42_reg_580;

assign zext_ln69_fu_764_p1 = i_0_i_reg_480;

assign zext_ln89_1_fu_748_p1 = B1_V_q0;

assign zext_ln89_fu_743_p1 = j_0_reg_447;

assign zext_ln947_1_fu_1491_p1 = sub_ln947_1_fu_1485_p2;

assign zext_ln947_2_fu_1823_p1 = sub_ln947_2_fu_1817_p2;

assign zext_ln947_fu_1207_p1 = sub_ln947_fu_1201_p2;

assign zext_ln94_fu_842_p1 = j4_0_reg_491;

assign zext_ln957_1_fu_1297_p1 = reg_721;

assign zext_ln957_2_fu_1581_p1 = reg_721;

assign zext_ln957_3_fu_1983_p1 = tmp_V_13_reg_2501;

assign zext_ln958_1_fu_1321_p1 = sub_ln958_fu_1316_p2;

assign zext_ln958_2_fu_1596_p1 = lshr_ln958_1_fu_1590_p2;

assign zext_ln958_3_fu_1605_p1 = sub_ln958_1_fu_1600_p2;

assign zext_ln958_4_fu_1997_p1 = lshr_ln958_2_fu_1991_p2;

assign zext_ln958_5_fu_2006_p1 = sub_ln958_2_fu_2001_p2;

assign zext_ln958_fu_1312_p1 = lshr_ln958_fu_1306_p2;

assign zext_ln961_1_fu_1622_p1 = or_ln949_2_reg_2461;

assign zext_ln961_2_fu_2023_p1 = or_ln949_4_reg_2513;

assign zext_ln961_fu_1338_p1 = or_ln_reg_2403;

assign zext_ln99_1_fu_975_p1 = tmp_8_fu_967_p3;

assign zext_ln99_fu_962_p1 = j5_0_reg_524;

always @ (posedge ap_clk) begin
    zext_ln89_reg_2191[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln94_reg_2237[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln99_reg_2288[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln99_1_reg_2298[2:0] <= 3'b000;
    zext_ln99_1_reg_2298[7] <= 1'b0;
    zext_ln104_reg_2339[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln104_1_reg_2354[2:0] <= 3'b000;
    zext_ln104_1_reg_2354[7] <= 1'b0;
    or_ln_reg_2403[31:1] <= 31'b0000000000000000000000000000000;
    zext_ln110_reg_2427[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    or_ln949_2_reg_2461[31:1] <= 31'b0000000000000000000000000000000;
    or_ln949_4_reg_2513[31:1] <= 31'b0000000000000000000000000000000;
    zext_ln119_reg_2541[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //mlp
