// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mlp,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.991400,HLS_SYN_LAT=37375,HLS_SYN_TPT=none,HLS_SYN_MEM=11,HLS_SYN_DSP=12,HLS_SYN_FF=2419,HLS_SYN_LUT=3620,HLS_VERSION=2019_1}" *)

module mlp (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0,
        output_r_q0
);

parameter    ap_ST_fsm_state1 = 81'd1;
parameter    ap_ST_fsm_state2 = 81'd2;
parameter    ap_ST_fsm_state3 = 81'd4;
parameter    ap_ST_fsm_state4 = 81'd8;
parameter    ap_ST_fsm_state5 = 81'd16;
parameter    ap_ST_fsm_state6 = 81'd32;
parameter    ap_ST_fsm_state7 = 81'd64;
parameter    ap_ST_fsm_state8 = 81'd128;
parameter    ap_ST_fsm_state9 = 81'd256;
parameter    ap_ST_fsm_state10 = 81'd512;
parameter    ap_ST_fsm_state11 = 81'd1024;
parameter    ap_ST_fsm_state12 = 81'd2048;
parameter    ap_ST_fsm_state13 = 81'd4096;
parameter    ap_ST_fsm_state14 = 81'd8192;
parameter    ap_ST_fsm_state15 = 81'd16384;
parameter    ap_ST_fsm_state16 = 81'd32768;
parameter    ap_ST_fsm_state17 = 81'd65536;
parameter    ap_ST_fsm_state18 = 81'd131072;
parameter    ap_ST_fsm_state19 = 81'd262144;
parameter    ap_ST_fsm_state20 = 81'd524288;
parameter    ap_ST_fsm_state21 = 81'd1048576;
parameter    ap_ST_fsm_state22 = 81'd2097152;
parameter    ap_ST_fsm_state23 = 81'd4194304;
parameter    ap_ST_fsm_state24 = 81'd8388608;
parameter    ap_ST_fsm_state25 = 81'd16777216;
parameter    ap_ST_fsm_state26 = 81'd33554432;
parameter    ap_ST_fsm_state27 = 81'd67108864;
parameter    ap_ST_fsm_state28 = 81'd134217728;
parameter    ap_ST_fsm_state29 = 81'd268435456;
parameter    ap_ST_fsm_state30 = 81'd536870912;
parameter    ap_ST_fsm_state31 = 81'd1073741824;
parameter    ap_ST_fsm_state32 = 81'd2147483648;
parameter    ap_ST_fsm_state33 = 81'd4294967296;
parameter    ap_ST_fsm_state34 = 81'd8589934592;
parameter    ap_ST_fsm_state35 = 81'd17179869184;
parameter    ap_ST_fsm_state36 = 81'd34359738368;
parameter    ap_ST_fsm_state37 = 81'd68719476736;
parameter    ap_ST_fsm_state38 = 81'd137438953472;
parameter    ap_ST_fsm_state39 = 81'd274877906944;
parameter    ap_ST_fsm_state40 = 81'd549755813888;
parameter    ap_ST_fsm_state41 = 81'd1099511627776;
parameter    ap_ST_fsm_state42 = 81'd2199023255552;
parameter    ap_ST_fsm_state43 = 81'd4398046511104;
parameter    ap_ST_fsm_state44 = 81'd8796093022208;
parameter    ap_ST_fsm_state45 = 81'd17592186044416;
parameter    ap_ST_fsm_state46 = 81'd35184372088832;
parameter    ap_ST_fsm_state47 = 81'd70368744177664;
parameter    ap_ST_fsm_state48 = 81'd140737488355328;
parameter    ap_ST_fsm_state49 = 81'd281474976710656;
parameter    ap_ST_fsm_state50 = 81'd562949953421312;
parameter    ap_ST_fsm_state51 = 81'd1125899906842624;
parameter    ap_ST_fsm_state52 = 81'd2251799813685248;
parameter    ap_ST_fsm_state53 = 81'd4503599627370496;
parameter    ap_ST_fsm_state54 = 81'd9007199254740992;
parameter    ap_ST_fsm_state55 = 81'd18014398509481984;
parameter    ap_ST_fsm_state56 = 81'd36028797018963968;
parameter    ap_ST_fsm_state57 = 81'd72057594037927936;
parameter    ap_ST_fsm_state58 = 81'd144115188075855872;
parameter    ap_ST_fsm_state59 = 81'd288230376151711744;
parameter    ap_ST_fsm_state60 = 81'd576460752303423488;
parameter    ap_ST_fsm_state61 = 81'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 81'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 81'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 81'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 81'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 81'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 81'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 81'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 81'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 81'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 81'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 81'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 81'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 81'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 81'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 81'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 81'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 81'd151115727451828646838272;
parameter    ap_ST_fsm_state79 = 81'd302231454903657293676544;
parameter    ap_ST_fsm_state80 = 81'd604462909807314587353088;
parameter    ap_ST_fsm_state81 = 81'd1208925819614629174706176;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] input_r_address0;
output   input_r_ce0;
input  [31:0] input_r_q0;
output  [3:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [31:0] output_r_d0;
input  [31:0] output_r_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_r_ce0;
reg[3:0] output_r_address0;
reg output_r_ce0;
reg output_r_we0;
reg[31:0] output_r_d0;

(* fsm_encoding = "none" *) reg   [80:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] B1_address0;
reg    B1_ce0;
wire   [31:0] B1_q0;
wire   [11:0] W1_address0;
reg    W1_ce0;
wire   [31:0] W1_q0;
wire   [2:0] B2_address0;
reg    B2_ce0;
wire   [31:0] B2_q0;
wire   [5:0] W2_address0;
reg    W2_ce0;
wire   [31:0] W2_q0;
wire   [2:0] B3_address0;
reg    B3_ce0;
wire   [31:0] B3_q0;
wire   [5:0] W3_address0;
reg    W3_ce0;
wire   [31:0] W3_q0;
wire   [3:0] B4_address0;
reg    B4_ce0;
wire   [31:0] B4_q0;
wire   [6:0] W4_address0;
reg    W4_ce0;
wire   [31:0] W4_q0;
wire   [31:0] grp_fu_559_p2;
reg   [31:0] reg_584;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state32;
wire    ap_CS_fsm_state44;
wire   [31:0] grp_fu_548_p2;
reg   [31:0] reg_589;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state36;
wire    ap_CS_fsm_state48;
wire    ap_CS_fsm_state57;
wire   [31:0] z4_q0;
wire    ap_CS_fsm_state49;
wire    ap_CS_fsm_state54;
wire   [11:0] add_ln86_fu_604_p2;
reg   [11:0] add_ln86_reg_1143;
wire    ap_CS_fsm_state2;
wire   [2:0] j_fu_616_p2;
reg   [2:0] j_reg_1151;
wire   [63:0] zext_ln87_fu_622_p1;
reg   [63:0] zext_ln87_reg_1156;
wire   [0:0] icmp_ln86_fu_610_p2;
wire    ap_CS_fsm_state3;
wire   [9:0] i_fu_633_p2;
reg   [9:0] i_reg_1174;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln68_fu_627_p2;
reg   [31:0] input_load_reg_1189;
wire    ap_CS_fsm_state5;
reg   [31:0] W1_load_reg_1194;
wire   [3:0] j_1_fu_716_p2;
reg   [3:0] j_1_reg_1202;
wire    ap_CS_fsm_state14;
wire   [63:0] zext_ln91_fu_722_p1;
reg   [63:0] zext_ln91_reg_1207;
wire   [0:0] icmp_ln90_fu_710_p2;
wire   [6:0] add_ln69_fu_743_p2;
reg   [6:0] add_ln69_reg_1217;
wire    ap_CS_fsm_state15;
wire   [2:0] i_1_fu_755_p2;
reg   [2:0] i_1_reg_1230;
wire    ap_CS_fsm_state16;
wire   [0:0] icmp_ln68_1_fu_749_p2;
wire   [31:0] a1_q0;
reg   [31:0] a1_load_reg_1245;
wire    ap_CS_fsm_state17;
reg   [31:0] W2_load_reg_1250;
wire   [3:0] j_2_fu_837_p2;
reg   [3:0] j_2_reg_1258;
wire    ap_CS_fsm_state26;
wire   [63:0] zext_ln95_fu_843_p1;
reg   [63:0] zext_ln95_reg_1263;
wire   [0:0] icmp_ln94_fu_831_p2;
wire   [7:0] zext_ln95_1_fu_856_p1;
reg   [7:0] zext_ln95_1_reg_1273;
wire    ap_CS_fsm_state27;
wire   [3:0] i_2_fu_866_p2;
reg   [3:0] i_2_reg_1286;
wire    ap_CS_fsm_state28;
wire   [0:0] icmp_ln68_2_fu_860_p2;
wire   [31:0] a2_q0;
reg   [31:0] a2_load_reg_1301;
wire    ap_CS_fsm_state29;
reg   [31:0] W3_load_reg_1306;
wire   [3:0] j_4_fu_948_p2;
reg   [3:0] j_4_reg_1314;
wire    ap_CS_fsm_state38;
wire   [63:0] zext_ln99_fu_954_p1;
reg   [63:0] zext_ln99_reg_1319;
wire   [0:0] icmp_ln98_fu_942_p2;
wire   [7:0] zext_ln99_1_fu_967_p1;
reg   [7:0] zext_ln99_1_reg_1334;
wire    ap_CS_fsm_state39;
wire   [3:0] i_3_fu_977_p2;
reg   [3:0] i_3_reg_1347;
wire    ap_CS_fsm_state40;
wire   [0:0] icmp_ln68_3_fu_971_p2;
wire   [31:0] a3_q0;
reg   [31:0] a3_load_reg_1362;
wire    ap_CS_fsm_state41;
reg   [31:0] W4_load_reg_1367;
wire    ap_CS_fsm_state50;
wire   [0:0] icmp_ln103_fu_1002_p2;
wire   [3:0] j_3_fu_1013_p2;
reg   [3:0] j_3_reg_1380;
reg   [31:0] maxv_1_reg_1385;
wire    ap_CS_fsm_state51;
wire   [31:0] maxv_2_fu_1102_p3;
wire    ap_CS_fsm_state52;
wire   [3:0] j_5_fu_1115_p2;
reg   [3:0] j_5_reg_1400;
wire    ap_CS_fsm_state53;
wire   [63:0] zext_ln110_fu_1121_p1;
reg   [63:0] zext_ln110_reg_1405;
wire   [0:0] icmp_ln109_fu_1109_p2;
wire   [31:0] grp_fu_578_p2;
reg   [31:0] e_reg_1415;
wire    ap_CS_fsm_state65;
wire    ap_CS_fsm_state69;
wire   [3:0] j_6_fu_1132_p2;
reg   [3:0] j_6_reg_1428;
wire    ap_CS_fsm_state70;
reg   [3:0] output_addr_1_reg_1433;
wire   [0:0] icmp_ln116_fu_1126_p2;
reg   [31:0] output_load_reg_1438;
wire    ap_CS_fsm_state71;
wire   [31:0] grp_fu_563_p2;
reg   [31:0] tmp_9_reg_1443;
wire    ap_CS_fsm_state80;
reg   [2:0] a1_address0;
reg    a1_ce0;
reg    a1_we0;
wire   [31:0] a1_d0;
reg   [2:0] a2_address0;
reg    a2_ce0;
reg    a2_we0;
wire   [31:0] a2_d0;
reg   [2:0] a3_address0;
reg    a3_ce0;
reg    a3_we0;
wire   [31:0] a3_d0;
reg   [3:0] z4_address0;
reg    z4_ce0;
reg    z4_we0;
reg   [2:0] j_0_reg_349;
wire    ap_CS_fsm_state13;
reg   [11:0] phi_mul_reg_360;
reg   [31:0] acc_0_i_reg_372;
reg   [9:0] i_0_i_reg_382;
reg   [3:0] j1_0_reg_393;
wire    ap_CS_fsm_state25;
reg   [31:0] acc_0_i6_reg_405;
reg   [2:0] i_0_i7_reg_415;
reg   [3:0] j2_0_reg_426;
wire    ap_CS_fsm_state37;
reg   [31:0] acc_0_i17_reg_438;
reg   [3:0] i_0_i18_reg_448;
reg   [3:0] j3_0_reg_459;
reg   [31:0] acc_0_i28_reg_471;
reg   [3:0] i_0_i29_reg_482;
reg   [3:0] j4_0_reg_493;
reg   [31:0] maxv_0_reg_504;
reg   [31:0] sum_0_reg_514;
reg   [3:0] j5_0_reg_526;
reg   [3:0] j6_0_reg_537;
wire    ap_CS_fsm_state81;
wire   [63:0] zext_ln69_7_fu_654_p1;
wire   [63:0] zext_ln69_fu_639_p1;
wire   [63:0] zext_ln69_9_fu_775_p1;
wire   [63:0] zext_ln69_1_fu_761_p1;
wire   [63:0] zext_ln69_11_fu_886_p1;
wire   [63:0] zext_ln69_2_fu_872_p1;
wire   [63:0] zext_ln69_13_fu_997_p1;
wire   [63:0] zext_ln69_3_fu_983_p1;
wire   [63:0] zext_ln104_fu_1008_p1;
wire   [63:0] zext_ln117_fu_1138_p1;
reg   [31:0] grp_fu_548_p0;
reg   [31:0] grp_fu_548_p1;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state33;
wire    ap_CS_fsm_state45;
wire    ap_CS_fsm_state66;
reg   [31:0] grp_fu_559_p0;
reg   [31:0] grp_fu_559_p1;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state30;
wire    ap_CS_fsm_state42;
wire    ap_CS_fsm_state72;
reg   [31:0] grp_fu_568_p0;
reg   [31:0] grp_fu_568_p1;
wire    ap_CS_fsm_state58;
wire   [11:0] zext_ln69_6_fu_644_p1;
wire   [11:0] add_ln69_1_fu_648_p2;
wire   [31:0] bitcast_ln72_fu_659_p1;
wire   [7:0] tmp_fu_663_p4;
wire   [22:0] trunc_ln72_fu_673_p1;
wire   [0:0] icmp_ln72_1_fu_683_p2;
wire   [0:0] icmp_ln72_fu_677_p2;
wire   [0:0] or_ln72_fu_689_p2;
wire   [0:0] grp_fu_568_p2;
wire   [0:0] and_ln72_fu_695_p2;
wire   [5:0] tmp_10_fu_731_p3;
wire   [6:0] zext_ln69_4_fu_727_p1;
wire   [6:0] zext_ln69_5_fu_739_p1;
wire   [6:0] zext_ln69_8_fu_766_p1;
wire   [6:0] add_ln69_2_fu_770_p2;
wire   [31:0] bitcast_ln72_1_fu_780_p1;
wire   [7:0] tmp_2_fu_784_p4;
wire   [22:0] trunc_ln72_1_fu_794_p1;
wire   [0:0] icmp_ln72_3_fu_804_p2;
wire   [0:0] icmp_ln72_2_fu_798_p2;
wire   [0:0] or_ln72_1_fu_810_p2;
wire   [0:0] and_ln72_1_fu_816_p2;
wire   [6:0] tmp_11_fu_848_p3;
wire   [7:0] zext_ln69_10_fu_877_p1;
wire   [7:0] add_ln69_3_fu_881_p2;
wire   [31:0] bitcast_ln72_2_fu_891_p1;
wire   [7:0] tmp_4_fu_895_p4;
wire   [22:0] trunc_ln72_2_fu_905_p1;
wire   [0:0] icmp_ln72_5_fu_915_p2;
wire   [0:0] icmp_ln72_4_fu_909_p2;
wire   [0:0] or_ln72_2_fu_921_p2;
wire   [0:0] and_ln72_2_fu_927_p2;
wire   [6:0] tmp_12_fu_959_p3;
wire   [7:0] zext_ln69_12_fu_988_p1;
wire   [7:0] add_ln69_4_fu_992_p2;
wire   [31:0] bitcast_ln104_fu_1019_p1;
wire   [31:0] bitcast_ln104_1_fu_1036_p1;
wire   [7:0] tmp_6_fu_1022_p4;
wire   [22:0] trunc_ln104_fu_1032_p1;
wire   [0:0] icmp_ln104_1_fu_1060_p2;
wire   [0:0] icmp_ln104_fu_1054_p2;
wire   [7:0] tmp_8_fu_1040_p4;
wire   [22:0] trunc_ln104_1_fu_1050_p1;
wire   [0:0] icmp_ln104_3_fu_1078_p2;
wire   [0:0] icmp_ln104_2_fu_1072_p2;
wire   [0:0] or_ln104_fu_1066_p2;
wire   [0:0] or_ln104_1_fu_1084_p2;
wire   [0:0] and_ln104_fu_1090_p2;
wire   [0:0] and_ln104_1_fu_1096_p2;
reg   [1:0] grp_fu_548_opcode;
reg   [4:0] grp_fu_568_opcode;
reg   [80:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 81'd1;
end

mlp_B1 #(
    .DataWidth( 32 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
B1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(B1_address0),
    .ce0(B1_ce0),
    .q0(B1_q0)
);

mlp_W1 #(
    .DataWidth( 32 ),
    .AddressRange( 3920 ),
    .AddressWidth( 12 ))
W1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W1_address0),
    .ce0(W1_ce0),
    .q0(W1_q0)
);

mlp_B2 #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
B2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(B2_address0),
    .ce0(B2_ce0),
    .q0(B2_q0)
);

mlp_W2 #(
    .DataWidth( 32 ),
    .AddressRange( 40 ),
    .AddressWidth( 6 ))
W2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W2_address0),
    .ce0(W2_ce0),
    .q0(W2_q0)
);

mlp_B3 #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
B3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(B3_address0),
    .ce0(B3_ce0),
    .q0(B3_q0)
);

mlp_W3 #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
W3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W3_address0),
    .ce0(W3_ce0),
    .q0(W3_q0)
);

mlp_B4 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
B4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(B4_address0),
    .ce0(B4_ce0),
    .q0(B4_q0)
);

mlp_W4 #(
    .DataWidth( 32 ),
    .AddressRange( 80 ),
    .AddressWidth( 7 ))
W4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W4_address0),
    .ce0(W4_ce0),
    .q0(W4_q0)
);

mlp_a1 #(
    .DataWidth( 32 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
a1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(a1_address0),
    .ce0(a1_ce0),
    .we0(a1_we0),
    .d0(a1_d0),
    .q0(a1_q0)
);

mlp_a2 #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
a2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(a2_address0),
    .ce0(a2_ce0),
    .we0(a2_we0),
    .d0(a2_d0),
    .q0(a2_q0)
);

mlp_a2 #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
a3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(a3_address0),
    .ce0(a3_ce0),
    .we0(a3_we0),
    .d0(a3_d0),
    .q0(a3_q0)
);

mlp_z4 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
z4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(z4_address0),
    .ce0(z4_ce0),
    .we0(z4_we0),
    .d0(acc_0_i28_reg_471),
    .q0(z4_q0)
);

mlp_faddfsub_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mlp_faddfsub_32ns_32ns_32_4_full_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_548_p0),
    .din1(grp_fu_548_p1),
    .opcode(grp_fu_548_opcode),
    .ce(1'b1),
    .dout(grp_fu_548_p2)
);

mlp_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mlp_fmul_32ns_32ns_32_3_max_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_559_p0),
    .din1(grp_fu_559_p1),
    .ce(1'b1),
    .dout(grp_fu_559_p2)
);

mlp_fdiv_32ns_32ns_32_9_1 #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mlp_fdiv_32ns_32ns_32_9_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(output_load_reg_1438),
    .din1(sum_0_reg_514),
    .ce(1'b1),
    .dout(grp_fu_563_p2)
);

mlp_fcmp_32ns_32ns_1_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
mlp_fcmp_32ns_32ns_1_2_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_568_p0),
    .din1(grp_fu_568_p1),
    .ce(1'b1),
    .opcode(grp_fu_568_opcode),
    .dout(grp_fu_568_p2)
);

mlp_fexp_32ns_32ns_32_8_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mlp_fexp_32ns_32ns_32_8_full_dsp_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(reg_589),
    .ce(1'b1),
    .dout(grp_fu_578_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        acc_0_i17_reg_438 <= grp_fu_548_p2;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        acc_0_i17_reg_438 <= B3_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state48)) begin
        acc_0_i28_reg_471 <= grp_fu_548_p2;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        acc_0_i28_reg_471 <= B4_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        acc_0_i6_reg_405 <= grp_fu_548_p2;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        acc_0_i6_reg_405 <= B2_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        acc_0_i_reg_372 <= grp_fu_548_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        acc_0_i_reg_372 <= B1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        i_0_i18_reg_448 <= i_2_reg_1286;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        i_0_i18_reg_448 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state48)) begin
        i_0_i29_reg_482 <= i_3_reg_1347;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        i_0_i29_reg_482 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        i_0_i7_reg_415 <= i_1_reg_1230;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        i_0_i7_reg_415 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        i_0_i_reg_382 <= i_reg_1174;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        i_0_i_reg_382 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln86_fu_610_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        j1_0_reg_393 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        j1_0_reg_393 <= j_1_reg_1202;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln90_fu_710_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        j2_0_reg_426 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        j2_0_reg_426 <= j_2_reg_1258;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln94_fu_831_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state26))) begin
        j3_0_reg_459 <= 4'd0;
    end else if (((icmp_ln68_3_fu_971_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state40))) begin
        j3_0_reg_459 <= j_4_reg_1314;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state52)) begin
        j4_0_reg_493 <= j_3_reg_1380;
    end else if ((1'b1 == ap_CS_fsm_state49)) begin
        j4_0_reg_493 <= 4'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln103_fu_1002_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state50))) begin
        j5_0_reg_526 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state69)) begin
        j5_0_reg_526 <= j_5_reg_1400;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_fu_1109_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state53))) begin
        j6_0_reg_537 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state81)) begin
        j6_0_reg_537 <= j_6_reg_1428;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        j_0_reg_349 <= j_reg_1151;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        j_0_reg_349 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state52)) begin
        maxv_0_reg_504 <= maxv_2_fu_1102_p3;
    end else if ((1'b1 == ap_CS_fsm_state49)) begin
        maxv_0_reg_504 <= z4_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        phi_mul_reg_360 <= add_ln86_reg_1143;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_mul_reg_360 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln103_fu_1002_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state50))) begin
        sum_0_reg_514 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state69)) begin
        sum_0_reg_514 <= grp_fu_548_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        W1_load_reg_1194 <= W1_q0;
        input_load_reg_1189 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        W2_load_reg_1250 <= W2_q0;
        a1_load_reg_1245 <= a1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        W3_load_reg_1306 <= W3_q0;
        a2_load_reg_1301 <= a2_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        W4_load_reg_1367 <= W4_q0;
        a3_load_reg_1362 <= a3_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        add_ln69_reg_1217 <= add_ln69_fu_743_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln86_reg_1143 <= add_ln86_fu_604_p2;
        j_reg_1151 <= j_fu_616_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state65)) begin
        e_reg_1415 <= grp_fu_578_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        i_1_reg_1230 <= i_1_fu_755_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        i_2_reg_1286 <= i_2_fu_866_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state40)) begin
        i_3_reg_1347 <= i_3_fu_977_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        i_reg_1174 <= i_fu_633_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        j_1_reg_1202 <= j_1_fu_716_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        j_2_reg_1258 <= j_2_fu_837_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln103_fu_1002_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state50))) begin
        j_3_reg_1380 <= j_3_fu_1013_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        j_4_reg_1314 <= j_4_fu_948_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state53)) begin
        j_5_reg_1400 <= j_5_fu_1115_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state70)) begin
        j_6_reg_1428 <= j_6_fu_1132_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state51)) begin
        maxv_1_reg_1385 <= z4_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln116_fu_1126_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state70))) begin
        output_addr_1_reg_1433 <= zext_ln117_fu_1138_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state71)) begin
        output_load_reg_1438 <= output_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state8))) begin
        reg_584 <= grp_fu_559_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state12))) begin
        reg_589 <= grp_fu_548_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state80)) begin
        tmp_9_reg_1443 <= grp_fu_563_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_fu_1109_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state53))) begin
        zext_ln110_reg_1405[3 : 0] <= zext_ln110_fu_1121_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln86_fu_610_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        zext_ln87_reg_1156[2 : 0] <= zext_ln87_fu_622_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln90_fu_710_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
        zext_ln91_reg_1207[3 : 0] <= zext_ln91_fu_722_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        zext_ln95_1_reg_1273[6 : 3] <= zext_ln95_1_fu_856_p1[6 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln94_fu_831_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state26))) begin
        zext_ln95_reg_1263[3 : 0] <= zext_ln95_fu_843_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        zext_ln99_1_reg_1334[6 : 3] <= zext_ln99_1_fu_967_p1[6 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln98_fu_942_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state38))) begin
        zext_ln99_reg_1319[3 : 0] <= zext_ln99_fu_954_p1[3 : 0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        B1_ce0 = 1'b1;
    end else begin
        B1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        B2_ce0 = 1'b1;
    end else begin
        B2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        B3_ce0 = 1'b1;
    end else begin
        B3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        B4_ce0 = 1'b1;
    end else begin
        B4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        W1_ce0 = 1'b1;
    end else begin
        W1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        W2_ce0 = 1'b1;
    end else begin
        W2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        W3_ce0 = 1'b1;
    end else begin
        W3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state40)) begin
        W4_ce0 = 1'b1;
    end else begin
        W4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        a1_address0 = zext_ln69_1_fu_761_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        a1_address0 = zext_ln87_reg_1156;
    end else begin
        a1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state16))) begin
        a1_ce0 = 1'b1;
    end else begin
        a1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        a1_we0 = 1'b1;
    end else begin
        a1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        a2_address0 = zext_ln69_2_fu_872_p1;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        a2_address0 = zext_ln91_reg_1207;
    end else begin
        a2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state28))) begin
        a2_ce0 = 1'b1;
    end else begin
        a2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        a2_we0 = 1'b1;
    end else begin
        a2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state40)) begin
        a3_address0 = zext_ln69_3_fu_983_p1;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        a3_address0 = zext_ln95_reg_1263;
    end else begin
        a3_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state40))) begin
        a3_ce0 = 1'b1;
    end else begin
        a3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        a3_we0 = 1'b1;
    end else begin
        a3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln116_fu_1126_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state70))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln116_fu_1126_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state70))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state54)) begin
        grp_fu_548_opcode = 2'd1;
    end else if (((1'b1 == ap_CS_fsm_state66) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state9))) begin
        grp_fu_548_opcode = 2'd0;
    end else begin
        grp_fu_548_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state66)) begin
        grp_fu_548_p0 = sum_0_reg_514;
    end else if ((1'b1 == ap_CS_fsm_state54)) begin
        grp_fu_548_p0 = z4_q0;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        grp_fu_548_p0 = acc_0_i28_reg_471;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        grp_fu_548_p0 = acc_0_i17_reg_438;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_548_p0 = acc_0_i6_reg_405;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_548_p0 = acc_0_i_reg_372;
    end else begin
        grp_fu_548_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state66)) begin
        grp_fu_548_p1 = e_reg_1415;
    end else if ((1'b1 == ap_CS_fsm_state54)) begin
        grp_fu_548_p1 = maxv_0_reg_504;
    end else if (((1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state9))) begin
        grp_fu_548_p1 = reg_584;
    end else begin
        grp_fu_548_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        grp_fu_559_p0 = a3_load_reg_1362;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_559_p0 = a2_load_reg_1301;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_559_p0 = a1_load_reg_1245;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_559_p0 = input_load_reg_1189;
    end else begin
        grp_fu_559_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        grp_fu_559_p1 = W4_load_reg_1367;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_559_p1 = W3_load_reg_1306;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_559_p1 = W2_load_reg_1250;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_559_p1 = W1_load_reg_1194;
    end else begin
        grp_fu_559_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state51)) begin
        grp_fu_568_opcode = 5'd2;
    end else if ((((icmp_ln68_2_fu_860_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state28)) | ((icmp_ln68_1_fu_749_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16)) | ((icmp_ln68_fu_627_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
        grp_fu_568_opcode = 5'd4;
    end else begin
        grp_fu_568_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state51)) begin
        grp_fu_568_p0 = z4_q0;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        grp_fu_568_p0 = acc_0_i17_reg_438;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_568_p0 = acc_0_i6_reg_405;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_568_p0 = acc_0_i_reg_372;
    end else begin
        grp_fu_568_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state51)) begin
        grp_fu_568_p1 = maxv_0_reg_504;
    end else if (((1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state4))) begin
        grp_fu_568_p1 = 32'd0;
    end else begin
        grp_fu_568_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_r_ce0 = 1'b1;
    end else begin
        input_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state81)) begin
        output_r_address0 = output_addr_1_reg_1433;
    end else if ((1'b1 == ap_CS_fsm_state70)) begin
        output_r_address0 = zext_ln117_fu_1138_p1;
    end else if ((1'b1 == ap_CS_fsm_state65)) begin
        output_r_address0 = zext_ln110_reg_1405;
    end else begin
        output_r_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state81) | (1'b1 == ap_CS_fsm_state70) | (1'b1 == ap_CS_fsm_state65))) begin
        output_r_ce0 = 1'b1;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state81)) begin
        output_r_d0 = tmp_9_reg_1443;
    end else if ((1'b1 == ap_CS_fsm_state65)) begin
        output_r_d0 = grp_fu_578_p2;
    end else begin
        output_r_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state81) | (1'b1 == ap_CS_fsm_state65))) begin
        output_r_we0 = 1'b1;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state53)) begin
        z4_address0 = zext_ln110_fu_1121_p1;
    end else if ((1'b1 == ap_CS_fsm_state50)) begin
        z4_address0 = zext_ln104_fu_1008_p1;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        z4_address0 = zext_ln99_reg_1319;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        z4_address0 = 64'd0;
    end else begin
        z4_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state50) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state38))) begin
        z4_ce0 = 1'b1;
    end else begin
        z4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln68_3_fu_971_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state40))) begin
        z4_we0 = 1'b1;
    end else begin
        z4_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln86_fu_610_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln68_fu_627_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state14 : begin
            if (((icmp_ln90_fu_710_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((icmp_ln68_1_fu_749_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state26 : begin
            if (((icmp_ln94_fu_831_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state26))) begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            if (((icmp_ln68_2_fu_860_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state28))) begin
                ap_NS_fsm = ap_ST_fsm_state37;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state38 : begin
            if (((icmp_ln98_fu_942_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state38))) begin
                ap_NS_fsm = ap_ST_fsm_state49;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state39;
            end
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            if (((icmp_ln68_3_fu_971_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state40))) begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state41;
            end
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            if (((icmp_ln103_fu_1002_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state50))) begin
                ap_NS_fsm = ap_ST_fsm_state53;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state51;
            end
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state53 : begin
            if (((icmp_ln109_fu_1109_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state53))) begin
                ap_NS_fsm = ap_ST_fsm_state70;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state54;
            end
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state70 : begin
            if (((icmp_ln116_fu_1126_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state70))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state71;
            end
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            ap_NS_fsm = ap_ST_fsm_state78;
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state79;
        end
        ap_ST_fsm_state79 : begin
            ap_NS_fsm = ap_ST_fsm_state80;
        end
        ap_ST_fsm_state80 : begin
            ap_NS_fsm = ap_ST_fsm_state81;
        end
        ap_ST_fsm_state81 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B1_address0 = zext_ln87_fu_622_p1;

assign B2_address0 = zext_ln91_fu_722_p1;

assign B3_address0 = zext_ln95_fu_843_p1;

assign B4_address0 = zext_ln99_fu_954_p1;

assign W1_address0 = zext_ln69_7_fu_654_p1;

assign W2_address0 = zext_ln69_9_fu_775_p1;

assign W3_address0 = zext_ln69_11_fu_886_p1;

assign W4_address0 = zext_ln69_13_fu_997_p1;

assign a1_d0 = ((and_ln72_fu_695_p2[0:0] === 1'b1) ? 32'd0 : acc_0_i_reg_372);

assign a2_d0 = ((and_ln72_1_fu_816_p2[0:0] === 1'b1) ? 32'd0 : acc_0_i6_reg_405);

assign a3_d0 = ((and_ln72_2_fu_927_p2[0:0] === 1'b1) ? 32'd0 : acc_0_i17_reg_438);

assign add_ln69_1_fu_648_p2 = (phi_mul_reg_360 + zext_ln69_6_fu_644_p1);

assign add_ln69_2_fu_770_p2 = (add_ln69_reg_1217 + zext_ln69_8_fu_766_p1);

assign add_ln69_3_fu_881_p2 = (zext_ln95_1_reg_1273 + zext_ln69_10_fu_877_p1);

assign add_ln69_4_fu_992_p2 = (zext_ln99_1_reg_1334 + zext_ln69_12_fu_988_p1);

assign add_ln69_fu_743_p2 = (zext_ln69_4_fu_727_p1 + zext_ln69_5_fu_739_p1);

assign add_ln86_fu_604_p2 = (phi_mul_reg_360 + 12'd784);

assign and_ln104_1_fu_1096_p2 = (grp_fu_568_p2 & and_ln104_fu_1090_p2);

assign and_ln104_fu_1090_p2 = (or_ln104_fu_1066_p2 & or_ln104_1_fu_1084_p2);

assign and_ln72_1_fu_816_p2 = (or_ln72_1_fu_810_p2 & grp_fu_568_p2);

assign and_ln72_2_fu_927_p2 = (or_ln72_2_fu_921_p2 & grp_fu_568_p2);

assign and_ln72_fu_695_p2 = (or_ln72_fu_689_p2 & grp_fu_568_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state48 = ap_CS_fsm[32'd47];

assign ap_CS_fsm_state49 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state50 = ap_CS_fsm[32'd49];

assign ap_CS_fsm_state51 = ap_CS_fsm[32'd50];

assign ap_CS_fsm_state52 = ap_CS_fsm[32'd51];

assign ap_CS_fsm_state53 = ap_CS_fsm[32'd52];

assign ap_CS_fsm_state54 = ap_CS_fsm[32'd53];

assign ap_CS_fsm_state57 = ap_CS_fsm[32'd56];

assign ap_CS_fsm_state58 = ap_CS_fsm[32'd57];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state65 = ap_CS_fsm[32'd64];

assign ap_CS_fsm_state66 = ap_CS_fsm[32'd65];

assign ap_CS_fsm_state69 = ap_CS_fsm[32'd68];

assign ap_CS_fsm_state70 = ap_CS_fsm[32'd69];

assign ap_CS_fsm_state71 = ap_CS_fsm[32'd70];

assign ap_CS_fsm_state72 = ap_CS_fsm[32'd71];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state80 = ap_CS_fsm[32'd79];

assign ap_CS_fsm_state81 = ap_CS_fsm[32'd80];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign bitcast_ln104_1_fu_1036_p1 = maxv_0_reg_504;

assign bitcast_ln104_fu_1019_p1 = maxv_1_reg_1385;

assign bitcast_ln72_1_fu_780_p1 = acc_0_i6_reg_405;

assign bitcast_ln72_2_fu_891_p1 = acc_0_i17_reg_438;

assign bitcast_ln72_fu_659_p1 = acc_0_i_reg_372;

assign i_1_fu_755_p2 = (i_0_i7_reg_415 + 3'd1);

assign i_2_fu_866_p2 = (i_0_i18_reg_448 + 4'd1);

assign i_3_fu_977_p2 = (i_0_i29_reg_482 + 4'd1);

assign i_fu_633_p2 = (i_0_i_reg_382 + 10'd1);

assign icmp_ln103_fu_1002_p2 = ((j4_0_reg_493 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln104_1_fu_1060_p2 = ((trunc_ln104_fu_1032_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln104_2_fu_1072_p2 = ((tmp_8_fu_1040_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln104_3_fu_1078_p2 = ((trunc_ln104_1_fu_1050_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln104_fu_1054_p2 = ((tmp_6_fu_1022_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln109_fu_1109_p2 = ((j5_0_reg_526 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln116_fu_1126_p2 = ((j6_0_reg_537 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln68_1_fu_749_p2 = ((i_0_i7_reg_415 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln68_2_fu_860_p2 = ((i_0_i18_reg_448 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln68_3_fu_971_p2 = ((i_0_i29_reg_482 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln68_fu_627_p2 = ((i_0_i_reg_382 == 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln72_1_fu_683_p2 = ((trunc_ln72_fu_673_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln72_2_fu_798_p2 = ((tmp_2_fu_784_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln72_3_fu_804_p2 = ((trunc_ln72_1_fu_794_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln72_4_fu_909_p2 = ((tmp_4_fu_895_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln72_5_fu_915_p2 = ((trunc_ln72_2_fu_905_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln72_fu_677_p2 = ((tmp_fu_663_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_610_p2 = ((j_0_reg_349 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln90_fu_710_p2 = ((j1_0_reg_393 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln94_fu_831_p2 = ((j2_0_reg_426 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln98_fu_942_p2 = ((j3_0_reg_459 == 4'd10) ? 1'b1 : 1'b0);

assign input_r_address0 = zext_ln69_fu_639_p1;

assign j_1_fu_716_p2 = (j1_0_reg_393 + 4'd1);

assign j_2_fu_837_p2 = (j2_0_reg_426 + 4'd1);

assign j_3_fu_1013_p2 = (4'd1 + j4_0_reg_493);

assign j_4_fu_948_p2 = (j3_0_reg_459 + 4'd1);

assign j_5_fu_1115_p2 = (j5_0_reg_526 + 4'd1);

assign j_6_fu_1132_p2 = (j6_0_reg_537 + 4'd1);

assign j_fu_616_p2 = (j_0_reg_349 + 3'd1);

assign maxv_2_fu_1102_p3 = ((and_ln104_1_fu_1096_p2[0:0] === 1'b1) ? maxv_1_reg_1385 : maxv_0_reg_504);

assign or_ln104_1_fu_1084_p2 = (icmp_ln104_3_fu_1078_p2 | icmp_ln104_2_fu_1072_p2);

assign or_ln104_fu_1066_p2 = (icmp_ln104_fu_1054_p2 | icmp_ln104_1_fu_1060_p2);

assign or_ln72_1_fu_810_p2 = (icmp_ln72_3_fu_804_p2 | icmp_ln72_2_fu_798_p2);

assign or_ln72_2_fu_921_p2 = (icmp_ln72_5_fu_915_p2 | icmp_ln72_4_fu_909_p2);

assign or_ln72_fu_689_p2 = (icmp_ln72_fu_677_p2 | icmp_ln72_1_fu_683_p2);

assign tmp_10_fu_731_p3 = {{j1_0_reg_393}, {2'd0}};

assign tmp_11_fu_848_p3 = {{j2_0_reg_426}, {3'd0}};

assign tmp_12_fu_959_p3 = {{j3_0_reg_459}, {3'd0}};

assign tmp_2_fu_784_p4 = {{bitcast_ln72_1_fu_780_p1[30:23]}};

assign tmp_4_fu_895_p4 = {{bitcast_ln72_2_fu_891_p1[30:23]}};

assign tmp_6_fu_1022_p4 = {{bitcast_ln104_fu_1019_p1[30:23]}};

assign tmp_8_fu_1040_p4 = {{bitcast_ln104_1_fu_1036_p1[30:23]}};

assign tmp_fu_663_p4 = {{bitcast_ln72_fu_659_p1[30:23]}};

assign trunc_ln104_1_fu_1050_p1 = bitcast_ln104_1_fu_1036_p1[22:0];

assign trunc_ln104_fu_1032_p1 = bitcast_ln104_fu_1019_p1[22:0];

assign trunc_ln72_1_fu_794_p1 = bitcast_ln72_1_fu_780_p1[22:0];

assign trunc_ln72_2_fu_905_p1 = bitcast_ln72_2_fu_891_p1[22:0];

assign trunc_ln72_fu_673_p1 = bitcast_ln72_fu_659_p1[22:0];

assign zext_ln104_fu_1008_p1 = j4_0_reg_493;

assign zext_ln110_fu_1121_p1 = j5_0_reg_526;

assign zext_ln117_fu_1138_p1 = j6_0_reg_537;

assign zext_ln69_10_fu_877_p1 = i_0_i18_reg_448;

assign zext_ln69_11_fu_886_p1 = add_ln69_3_fu_881_p2;

assign zext_ln69_12_fu_988_p1 = i_0_i29_reg_482;

assign zext_ln69_13_fu_997_p1 = add_ln69_4_fu_992_p2;

assign zext_ln69_1_fu_761_p1 = i_0_i7_reg_415;

assign zext_ln69_2_fu_872_p1 = i_0_i18_reg_448;

assign zext_ln69_3_fu_983_p1 = i_0_i29_reg_482;

assign zext_ln69_4_fu_727_p1 = j1_0_reg_393;

assign zext_ln69_5_fu_739_p1 = tmp_10_fu_731_p3;

assign zext_ln69_6_fu_644_p1 = i_0_i_reg_382;

assign zext_ln69_7_fu_654_p1 = add_ln69_1_fu_648_p2;

assign zext_ln69_8_fu_766_p1 = i_0_i7_reg_415;

assign zext_ln69_9_fu_775_p1 = add_ln69_2_fu_770_p2;

assign zext_ln69_fu_639_p1 = i_0_i_reg_382;

assign zext_ln87_fu_622_p1 = j_0_reg_349;

assign zext_ln91_fu_722_p1 = j1_0_reg_393;

assign zext_ln95_1_fu_856_p1 = tmp_11_fu_848_p3;

assign zext_ln95_fu_843_p1 = j2_0_reg_426;

assign zext_ln99_1_fu_967_p1 = tmp_12_fu_959_p3;

assign zext_ln99_fu_954_p1 = j3_0_reg_459;

always @ (posedge ap_clk) begin
    zext_ln87_reg_1156[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln91_reg_1207[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln95_reg_1263[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln95_1_reg_1273[2:0] <= 3'b000;
    zext_ln95_1_reg_1273[7] <= 1'b0;
    zext_ln99_reg_1319[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
    zext_ln99_1_reg_1334[2:0] <= 3'b000;
    zext_ln99_1_reg_1334[7] <= 1'b0;
    zext_ln110_reg_1405[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //mlp
