// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "neuron.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic neuron::ap_const_logic_1 = sc_dt::Log_1;
const bool neuron::ap_const_boolean_1 = true;
const sc_lv<6> neuron::ap_const_lv6_0 = "000000";
const sc_lv<32> neuron::ap_const_lv32_6 = "110";
const sc_lv<32> neuron::ap_const_lv32_15 = "10101";
const sc_logic neuron::ap_const_logic_0 = sc_dt::Log_0;

neuron::neuron(sc_module_name name) : sc_module(name), mVcdFile(0) {
    neuron_mac_muladd_16s_16s_22ns_22_1_1_U1 = new neuron_mac_muladd_16s_16s_22ns_22_1_1<1,1,16,16,22,22>("neuron_mac_muladd_16s_16s_22ns_22_1_1_U1");
    neuron_mac_muladd_16s_16s_22ns_22_1_1_U1->din0(w_fxp_V);
    neuron_mac_muladd_16s_16s_22ns_22_1_1_U1->din1(x_fxp_V);
    neuron_mac_muladd_16s_16s_22ns_22_1_1_U1->din2(grp_fu_69_p2);
    neuron_mac_muladd_16s_16s_22ns_22_1_1_U1->dout(grp_fu_69_p3);

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_start );
    sensitive << ( grp_fu_69_p3 );

    SC_METHOD(thread_grp_fu_69_p2);
    sensitive << ( b_fxp_V );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_virtual_clock.pos() );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "neuron_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, w_fxp_V, "(port)w_fxp_V");
    sc_trace(mVcdFile, x_fxp_V, "(port)x_fxp_V");
    sc_trace(mVcdFile, b_fxp_V, "(port)b_fxp_V");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, grp_fu_69_p3, "grp_fu_69_p3");
    sc_trace(mVcdFile, grp_fu_69_p2, "grp_fu_69_p2");
#endif

    }
    mHdltvinHandle.open("neuron.hdltvin.dat");
    mHdltvoutHandle.open("neuron.hdltvout.dat");
}

neuron::~neuron() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete neuron_mac_muladd_16s_16s_22ns_22_1_1_U1;
}

void neuron::thread_ap_done() {
    ap_done = ap_start.read();
}

void neuron::thread_ap_idle() {
    ap_idle = ap_const_logic_1;
}

void neuron::thread_ap_ready() {
    ap_ready = ap_start.read();
}

void neuron::thread_ap_return() {
    ap_return = grp_fu_69_p3.read().range(21, 6);
}

void neuron::thread_grp_fu_69_p2() {
    grp_fu_69_p2 = esl_concat<16,6>(b_fxp_V.read(), ap_const_lv6_0);
}

void neuron::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"w_fxp_V\" :  \"" << w_fxp_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"x_fxp_V\" :  \"" << x_fxp_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"b_fxp_V\" :  \"" << b_fxp_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_return\" :  \"" << ap_return.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

