// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _neuron_HH_
#define _neuron_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "neuron_mac_muladd_16s_16s_22ns_22_1_1.h"

namespace ap_rtl {

struct neuron : public sc_module {
    // Port declarations 8
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<16> > w_fxp_V;
    sc_in< sc_lv<16> > x_fxp_V;
    sc_in< sc_lv<16> > b_fxp_V;
    sc_out< sc_lv<16> > ap_return;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    neuron(sc_module_name name);
    SC_HAS_PROCESS(neuron);

    ~neuron();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    neuron_mac_muladd_16s_16s_22ns_22_1_1<1,1,16,16,22,22>* neuron_mac_muladd_16s_16s_22ns_22_1_1_U1;
    sc_signal< sc_lv<22> > grp_fu_69_p3;
    sc_signal< sc_lv<22> > grp_fu_69_p2;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_grp_fu_69_p2();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
