#!/usr/bin/env python3
"""
Hardware Architectures for AI - Lab 7  (pruned MLP)
=================================================
Splice the Lab 6 magnitude-pruned MLP and a few MNIST test images + golden
softmax outputs into the three Vivado HLS sources of the 'pruned_mlp' project:

    ../pruned_mlp/mlp.cpp     <- pruned weights + biases  (between the markers)
    ../pruned_mlp/mlp_tb.cpp  <- test images + golden softmax (between the markers)
    ../pruned_mlp/mlp.h       <- ap_fixed word length (hand written, untouched)

Pruned model = trained FP32 kernels (Lab6/weights_floatingpoint.weights.h5)
with |w| < THRESHOLD forced to 0 (one global magnitude threshold, exactly the
Lab 6 deliverable reconstruction).  Biases are not pruned.
Golden reference = float forward pass with those pruned weights.
"""
import os, re, datetime
import h5py, numpy as np
from tensorflow import keras

HERE   = os.path.dirname(os.path.abspath(__file__))
H5FP   = os.path.join(HERE, "..", "..", "Lab6", "weights_floatingpoint.weights.h5")
SRCDIR = os.path.join(HERE, "..", "pruned_mlp")
N_TEST = 5
THRESHOLD = 0.24091238          # Lab 6 global magnitude threshold (~78.95 % kernel sparsity)

BEG = "/* ===== AUTO-GENERATED by deliverables/prune_export.py -- DO NOT EDIT ===== */"
END = "/* ===== END AUTO-GENERATED ===== */"

# ---------------------------------------------------------------- load + prune
f  = h5py.File(H5FP, "r")
W1 = f["layers/dense/vars/0"][:];    b1 = f["layers/dense/vars/1"][:]
W2 = f["layers/dense_1/vars/0"][:];  b2 = f["layers/dense_1/vars/1"][:]
W3 = f["layers/dense_2/vars/0"][:];  b3 = f["layers/dense_2/vars/1"][:]
W4 = f["layers/dense_3/vars/0"][:];  b4 = f["layers/dense_3/vars/1"][:]

def prune(w):
    return np.where(np.abs(w) >= THRESHOLD, w, 0.0).astype("float32")
W1, W2, W3, W4 = prune(W1), prune(W2), prune(W3), prune(W4)

# ---------------------------------------------------------------- MNIST inputs
(_, _), (x_test, y_test) = keras.datasets.mnist.load_data()
x_test_n = (x_test.astype("float32") / x_test.max()).astype("float32")

# ---------------------------------------------------------------- Python golden (pruned model)
relu = lambda x: np.maximum(x, 0.0)
def softmax(x):
    e = np.exp(x - x.max()); return e / e.sum()
def forward(img):
    a  = img.reshape(-1).astype("float64")
    a1 = relu(a  @ W1 + b1)
    a2 = relu(a1 @ W2 + b2)
    a3 = relu(a2 @ W3 + b3)
    z4 = a3 @ W4 + b4
    return softmax(z4).astype("float32")

imgs   = x_test_n[:N_TEST]
labels = y_test[:N_TEST]
golden = np.array([forward(im) for im in imgs], dtype="float32")

# ---------------------------------------------------------------- C emitters
def vec(name, a):
    return "static const data_t {}[{}] = {{{}}};".format(
        name, len(a), ", ".join("{:.9e}f".format(float(v)) for v in a))

def mat_T(name, a):
    aT = a.T; rows, cols = aT.shape
    lines = ["static const data_t {}[{}][{}] = {{".format(name, rows, cols)]
    for r in range(rows):
        lines.append("  {" + ", ".join("{:.9e}f".format(float(v)) for v in aT[r]) +
                     "}" + ("," if r < rows - 1 else ""))
    lines.append("};")
    return "\n".join(lines)

stamp = datetime.date.today().isoformat()
spars = [100.0 * (1.0 - (w != 0).mean()) for w in (W1, W2, W3, W4)]

weights_block = "\n\n".join([
    "/* Lab 6 magnitude-pruned FP32 weights  (|w| < %.8f -> 0)  generated %s" % (THRESHOLD, stamp),
    " * per-layer sparsity: %.2f / %.2f / %.2f / %.2f %% ; kernels transposed to W[n_out][n_in]. */"
    % tuple(spars),
    "/* ---- layer 1 : dense_1  (784 -> 5), ReLU ---- */\n" + mat_T("W1", W1) + "\n" + vec("B1", b1),
    "/* ---- layer 2 : dense_2  (5 -> 8), ReLU ---- */\n"   + mat_T("W2", W2) + "\n" + vec("B2", b2),
    "/* ---- layer 3 : dense_3  (8 -> 8), ReLU ---- */\n"   + mat_T("W3", W3) + "\n" + vec("B3", b3),
    "/* ---- layer 4 : output_layer  (8 -> 10), softmax ---- */\n" + mat_T("W4", W4) + "\n" + vec("B4", b4),
]).lstrip("\n")

tb = []
tb.append("/* first %d MNIST test images + Python pruned-model golden softmax (generated %s) */" % (N_TEST, stamp))
tb.append("#define N_TEST %d" % N_TEST)
tb.append("")
tb.append("static const int test_label[N_TEST]   = {%s};" % ", ".join(str(int(v)) for v in labels))
tb.append("static const int golden_class[N_TEST] = {%s};" % ", ".join(str(int(golden[i].argmax())) for i in range(N_TEST)))
tb.append("")
tb.append("static const float test_input[N_TEST][IN_SIZE] = {")
for i in range(N_TEST):
    tb.append("  { /* image %d  (label %d) */" % (i, int(labels[i])))
    tb.append("    " + ", ".join("{:.7e}f".format(float(v)) for v in imgs[i].reshape(-1)))
    tb.append("  }" + ("," if i < N_TEST - 1 else ""))
tb.append("};")
tb.append("")
tb.append("static const float golden_output[N_TEST][OUT_SIZE] = {")
for i in range(N_TEST):
    tb.append("  {" + ", ".join("{:.9e}f".format(float(v)) for v in golden[i]) +
              "}" + ("," if i < N_TEST - 1 else ""))
tb.append("};")
tbdata_block = "\n".join(tb)

# ---------------------------------------------------------------- splice
def splice(path, block):
    txt = open(path).read()
    if BEG not in txt or END not in txt:
        raise SystemExit("markers not found in %s" % path)
    txt = re.sub(re.escape(BEG) + r".*?" + re.escape(END),
                 lambda m: "{}\n{}\n{}".format(BEG, block, END), txt, flags=re.S)
    open(path, "w").write(txt)
    print("  spliced:", os.path.normpath(path))

splice(os.path.join(SRCDIR, "mlp.cpp"),    weights_block)
splice(os.path.join(SRCDIR, "mlp_tb.cpp"), tbdata_block)

# ---------------------------------------------------------------- console / log
tot = sum(w.size for w in (W1, W2, W3, W4)); nz = sum(int((w != 0).sum()) for w in (W1, W2, W3, W4))
print("=" * 74)
print(" Lab 7 - pruned MLP : export magnitude-pruned weights + golden")
print("=" * 74)
print("  threshold |w| >= %.8f" % THRESHOLD)
print("  global kernel sparsity : %.3f %%   (%d non-zero of %d)" % (100 * (1 - nz / tot), nz, tot))
print("  per-layer sparsity     : %.2f / %.2f / %.2f / %.2f %%" % tuple(spars))
for i in range(N_TEST):
    p = golden[i]
    print("    img %d: label %d  Python-pruned argmax %d  p(max)=%.5f" %
          (i, int(labels[i]), int(p.argmax()), p.max()))
